
help:  ## Show help
	@grep -E '^[.a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

clean: ## Clean autogenerated files
	rm -rf dist
	find . -type f -name "*.DS_Store" -ls -delete
	find . | grep -E "(__pycache__|\.pyc|\.pyo)" | xargs rm -rf
	find . | grep -E ".pytest_cache" | xargs rm -rf
	find . | grep -E ".ipynb_checkpoints" | xargs rm -rf
	rm -f .coverage

clean-logs: ## Clean logs
	rm -rf logs/**

format: ## Run pre-commit hooks
	uv run pre-commit run -a

sync: ## Merge changes from main branch to your current branch
	git pull
	git pull origin main

uv-sync: ## Install/update the uv environment
	uv sync --group dev

uv-lock: ## Refresh the uv lockfile
	uv lock

test: ## Run not slow tests
	uv run pytest -k "not slow"

test-full: ## Run all tests
	uv run pytest

train: ## Train the model
	uv run python src/train.py

train-demo: ## Run a short CIFAR-10 AE smoke training
	uv run python src/train.py experiment=demo/cifar10_ae

train-l1-demos: ## Run short synthetic L1 smoke trainings
	uv run python src/train.py experiment=demo/l1_vae
	uv run python src/train.py experiment=demo/l1_vicreg
	uv run python src/train.py experiment=demo/l1_wnae
	uv run python src/train.py experiment=demo/l1_rvae
