
SHELL := /usr/bin/env bash
.DEFAULT_GOAL := help

UV ?= uv
MLFLOW_PORT ?= 5000
ANALYTICAL_OUTPUT_DIR ?= figures/section3
ANALYTICAL_SMOKE_OUTPUT_DIR ?= results/analytical-smoke
PREFLIGHT_LAUNCHER ?= submitit_slurm_clariden

.PHONY: help clean format uv-sync uv-lock test test-full train train-demo train-synthetic smoke model-smoke pairing-smoke cchamber-pairing-smoke preflight-local preflight-cloud analytical analytical-smoke mlflow

help:  ## Show help
	@grep -E '^[.a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

clean: ## Clean autogenerated files
	rm -rf dist
	find . -type f -name "*.DS_Store" -delete
	find . -type d -name "__pycache__" -prune -exec rm -rf {} +
	find . -type d -name ".pytest_cache" -prune -exec rm -rf {} +
	find . -type d -name ".ipynb_checkpoints" -prune -exec rm -rf {} +
	rm -f .coverage

format: ## Run pre-commit hooks
	$(UV) run pre-commit run -a

uv-sync: ## Install/update the uv environment
	$(UV) sync --group dev

uv-lock: ## Refresh the uv lockfile
	$(UV) lock

test: ## Run not slow tests
	$(UV) run pytest -k "not slow"

test-full: ## Run all tests
	$(UV) run pytest

train: ## Train the model
	$(UV) run python src/train.py

train-demo: ## Run a short CIFAR-10 AE smoke training
	$(UV) run python tests/train.py experiment=demo/cifar10_ae

train-synthetic: ## Run the logged synthetic VAE smoke experiment
	scripts/synthetic/run_vae_smoke.sh

smoke: analytical-smoke model-smoke pairing-smoke cchamber-pairing-smoke ## Run the complete smoke suite

model-smoke: ## Smoke-test checkpoints/reporting on four models and three seeds
	$(UV) run python scripts/synthetic/smoke.py

pairing-smoke: ## Smoke-test encoder pairing, fixed tables, and CAP consumption
	$(UV) run python scripts/synthetic/pairing_smoke.py

cchamber-pairing-smoke: ## Smoke-test fixed pairing on real public Causal Chamber data
	$(UV) run python scripts/cchamber_pairing_smoke.py

preflight-local: ## Validate all core experiment configs and generated shell scripts
	$(UV) run python scripts/preflight.py --profile local

preflight-cloud: ## Enforce data, pair-table, git, config, and shell deployment gates
	$(UV) run python scripts/preflight.py --profile cloud --launcher $(PREFLIGHT_LAUNCHER)

analytical: ## Generate the publication-scale Section 3 analytical artifacts
	$(UV) run python src/analytical.py --profile paper --output-dir $(ANALYTICAL_OUTPUT_DIR)

analytical-smoke: ## Run the fast Section 3 artifact-pipeline check
	$(UV) run python src/analytical.py --profile smoke --output-dir $(ANALYTICAL_SMOKE_OUTPUT_DIR)

mlflow: ## Launch local MLflow UI using LOG_DIR from .env
	@test -f .env || (echo "Missing .env. Run scripts/setup.sh or create one first." >&2; exit 1)
	@set -eu -a; \
	. ./.env; \
	set +a; \
	: "$${LOG_DIR:?LOG_DIR must be set in .env}"; \
	$(UV) run mlflow ui \
		--backend-store-uri "$$LOG_DIR/mlflow/mlruns" \
		--host 127.0.0.1 \
		--port $(MLFLOW_PORT)
