# @package evaluation.callbacks.main

# The metric names need be specified like they are given by the model.
_target_: src.evaluation.callbacks.efficiency.AnomalyEfficiencyCallback
output_name: "loss/total/full"
target_rates: [0.01, 0.1, 0.25, 0.5, 1]
base_rate: 28608.8064
log_raw_mlflow: true
pure_thres: false
cvar_summary: 0.25
ds: ???
