# @package evaluation.callbacks.main

_target_: src.evaluation.callbacks.reco.ReconstructionPlots
output_name: reconstructed_data
warmup_batches: 0.2
datamodule: true
ckpts:
  last: true
datasets: ['main_test']
log_raw_mlflow: true
name: 'reco'
