# ========================================================================
# AE PARETO-FRONT TRAINING COMMANDS
# ========================================================================
# These are the training commands for every point on the Pareto front of
# each validation strategy. Generated by scripts/make_pareto_scripts.py from
# notebooks/paretos/robustad/ -- regenerate rather than edit by hand.
#
# Run from the repository root. All commands are commented out -- uncomment
# the points you want to run locally (taskset pinning, GPUs cycling 0-3).
# To run the WHOLE file on clariden instead, use the single submit command
# at the bottom: it sends every point above to slurm, one job each, via
# scripts/submit_pareto.sh (submitit launcher).

# ========================================================================
# CVAR25 TRAINING  (study: cvar25eff_vs_mse, 1 Pareto points)
# ========================================================================
# ------------------------------------------------------------------------
# trial 526: cvar25eff=1000, mse=0.0043474  << ORIGINAL PICK | BEST cvar25eff
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     experiment=robustad/ae \
#     experiment_name=robustad_ae_pareto \
#     run_name=cvar25_t526 \
#     data.image_size=[128,128] \
#     algorithm.delta=3.0 \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.batchnorm=True \
#     algorithm.encoder.nodes='[32,64,128]' \
#     algorithm.encoder.strides='[2,2]' \
#     algorithm.input_noise_std=0.03 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0009996069181833229 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[0]

# ========================================================================
# CAP TRAINING  (study: cap_vs_mse, 13 Pareto points)
# ========================================================================
# ------------------------------------------------------------------------
# trial 231: cap=-0.72751, mse=0.0044335
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     experiment=robustad/ae_agnostic \
#     experiment_name=robustad_ae_pareto \
#     run_name=cap_t231 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_shifted_normal_all \
#     data.image_size=[128,128] \
#     algorithm.delta=1.0 \
#     algorithm.encoder.activation=silu \
#     algorithm.encoder.batchnorm=True \
#     algorithm.encoder.nodes='[32,64,128]' \
#     algorithm.encoder.strides='[2,2]' \
#     algorithm.input_noise_std=0.03 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0009995664218927257 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 321: cap=-0.72774, mse=0.004416
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     experiment=robustad/ae_agnostic \
#     experiment_name=robustad_ae_pareto \
#     run_name=cap_t321 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_shifted_normal_all \
#     data.image_size=[128,128] \
#     algorithm.delta=1.0 \
#     algorithm.encoder.activation=silu \
#     algorithm.encoder.batchnorm=True \
#     algorithm.encoder.nodes='[32,64,128]' \
#     algorithm.encoder.strides='[2,2]' \
#     algorithm.input_noise_std=0.03 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0009997662446602459 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 324: cap=-0.72738, mse=0.004493
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     experiment=robustad/ae_agnostic \
#     experiment_name=robustad_ae_pareto \
#     run_name=cap_t324 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_shifted_normal_all \
#     data.image_size=[128,128] \
#     algorithm.delta=1.0 \
#     algorithm.encoder.activation=silu \
#     algorithm.encoder.batchnorm=True \
#     algorithm.encoder.nodes='[32,64,128]' \
#     algorithm.encoder.strides='[2,2]' \
#     algorithm.input_noise_std=0.03 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.00099985665172534 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 341: cap=-0.7263, mse=0.0052865
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     experiment=robustad/ae_agnostic \
#     experiment_name=robustad_ae_pareto \
#     run_name=cap_t341 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_shifted_normal_all \
#     data.image_size=[128,128] \
#     algorithm.delta=1.0 \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.batchnorm=True \
#     algorithm.encoder.nodes='[32,64,128]' \
#     algorithm.encoder.strides='[2,2]' \
#     algorithm.input_noise_std=0.03 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.000999907222115485 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[3]

# ------------------------------------------------------------------------
# trial 350: cap=-0.72581, mse=0.0057402  << ORIGINAL PICK | BEST cap
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     experiment=robustad/ae_agnostic \
#     experiment_name=robustad_ae_pareto \
#     run_name=cap_t350 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_shifted_normal_all \
#     data.image_size=[128,128] \
#     algorithm.delta=1.0 \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.batchnorm=True \
#     algorithm.encoder.nodes='[32,64,128]' \
#     algorithm.encoder.strides='[2,2]' \
#     algorithm.input_noise_std=0.03 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0009997251226802227 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 352: cap=-0.72605, mse=0.0057379
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     experiment=robustad/ae_agnostic \
#     experiment_name=robustad_ae_pareto \
#     run_name=cap_t352 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_shifted_normal_all \
#     data.image_size=[128,128] \
#     algorithm.delta=1.0 \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.batchnorm=True \
#     algorithm.encoder.nodes='[32,64,128]' \
#     algorithm.encoder.strides='[2,2]' \
#     algorithm.input_noise_std=0.03 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0009997121791823203 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 391: cap=-0.72605, mse=0.0056365
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     experiment=robustad/ae_agnostic \
#     experiment_name=robustad_ae_pareto \
#     run_name=cap_t391 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_shifted_normal_all \
#     data.image_size=[128,128] \
#     algorithm.delta=1.0 \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.batchnorm=True \
#     algorithm.encoder.nodes='[32,64,128]' \
#     algorithm.encoder.strides='[2,2]' \
#     algorithm.input_noise_std=0.03 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.000999848065288982 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 416: cap=-0.72627, mse=0.0055717
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     experiment=robustad/ae_agnostic \
#     experiment_name=robustad_ae_pareto \
#     run_name=cap_t416 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_shifted_normal_all \
#     data.image_size=[128,128] \
#     algorithm.delta=1.0 \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.batchnorm=True \
#     algorithm.encoder.nodes='[32,64,128]' \
#     algorithm.encoder.strides='[2,2]' \
#     algorithm.input_noise_std=0.03 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0009990729212818407 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[3]

# ------------------------------------------------------------------------
# trial 480: cap=-0.72815, mse=0.0044022
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     experiment=robustad/ae_agnostic \
#     experiment_name=robustad_ae_pareto \
#     run_name=cap_t480 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_shifted_normal_all \
#     data.image_size=[128,128] \
#     algorithm.delta=1.0 \
#     algorithm.encoder.activation=silu \
#     algorithm.encoder.batchnorm=True \
#     algorithm.encoder.nodes='[32,64,128]' \
#     algorithm.encoder.strides='[2,2]' \
#     algorithm.input_noise_std=0.03 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0009992102726907647 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 553: cap=-0.72751, mse=0.0044859
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     experiment=robustad/ae_agnostic \
#     experiment_name=robustad_ae_pareto \
#     run_name=cap_t553 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_shifted_normal_all \
#     data.image_size=[128,128] \
#     algorithm.delta=1.0 \
#     algorithm.encoder.activation=silu \
#     algorithm.encoder.batchnorm=True \
#     algorithm.encoder.nodes='[32,64,128]' \
#     algorithm.encoder.strides='[2,2]' \
#     algorithm.input_noise_std=0.03 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0009994959606933645 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 554: cap=-0.72719, mse=0.0045473
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     experiment=robustad/ae_agnostic \
#     experiment_name=robustad_ae_pareto \
#     run_name=cap_t554 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_shifted_normal_all \
#     data.image_size=[128,128] \
#     algorithm.delta=1.0 \
#     algorithm.encoder.activation=silu \
#     algorithm.encoder.batchnorm=True \
#     algorithm.encoder.nodes='[32,64,128]' \
#     algorithm.encoder.strides='[2,2]' \
#     algorithm.input_noise_std=0.005 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.000999543189412038 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 561: cap=-0.7273, mse=0.0044955
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     experiment=robustad/ae_agnostic \
#     experiment_name=robustad_ae_pareto \
#     run_name=cap_t561 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_shifted_normal_all \
#     data.image_size=[128,128] \
#     algorithm.delta=1.0 \
#     algorithm.encoder.activation=silu \
#     algorithm.encoder.batchnorm=True \
#     algorithm.encoder.nodes='[32,64,128]' \
#     algorithm.encoder.strides='[2,2]' \
#     algorithm.input_noise_std=0.005 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0009999284616064215 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[3]

# ------------------------------------------------------------------------
# trial 563: cap=-0.72726, mse=0.0044958  << KNEE
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     experiment=robustad/ae_agnostic \
#     experiment_name=robustad_ae_pareto \
#     run_name=cap_t563 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_shifted_normal_all \
#     data.image_size=[128,128] \
#     algorithm.delta=1.0 \
#     algorithm.encoder.activation=silu \
#     algorithm.encoder.batchnorm=True \
#     algorithm.encoder.nodes='[32,64,128]' \
#     algorithm.encoder.strides='[2,2]' \
#     algorithm.input_noise_std=0.005 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0009998706203862894 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[0]

# ========================================================================
# STABILITY TRAINING  (study: drift_vs_mse, 2 Pareto points)
# ========================================================================
# ------------------------------------------------------------------------
# trial 440: drift=1.0296, mse=0.0044779
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     experiment=robustad/ae_agnostic \
#     experiment_name=robustad_ae_pareto \
#     run_name=stability_t440 \
#     callbacks.wasserstein_dist=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_shifted_normal_all \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_shifted_normal_all \
#     data.image_size=[128,128] \
#     algorithm.delta=0.5 \
#     algorithm.encoder.activation=silu \
#     algorithm.encoder.batchnorm=True \
#     algorithm.encoder.nodes='[32,64,128]' \
#     algorithm.encoder.strides='[2,2]' \
#     algorithm.input_noise_std=0.01 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0007764918226520768 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 568: drift=0.068993, mse=0.05061  << ORIGINAL PICK | BEST drift
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     experiment=robustad/ae_agnostic \
#     experiment_name=robustad_ae_pareto \
#     run_name=stability_t568 \
#     callbacks.wasserstein_dist=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_shifted_normal_all \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_shifted_normal_all \
#     data.image_size=[128,128] \
#     algorithm.delta=2.0 \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.batchnorm=True \
#     algorithm.encoder.nodes='[16,32,64]' \
#     algorithm.encoder.strides='[2,2]' \
#     algorithm.input_noise_std=0.005 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=3.175029085053806e-05 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[1]

# ========================================================================
# WASSERSTEIN TRAINING  (study: wasserstein_vs_mse, 126 Pareto points, trimmed to 12 around the knee (endpoints kept))
# ========================================================================
# ------------------------------------------------------------------------
# trial 59: wasserstein=0.14142, mse=0.0045564
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     experiment=robustad/ae_agnostic \
#     experiment_name=robustad_ae_pareto \
#     run_name=wasserstein_t59 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_shifted_normal_all \
#     data.image_size=[128,128] \
#     algorithm.delta=1.0 \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.batchnorm=True \
#     algorithm.encoder.nodes='[32,64,128]' \
#     algorithm.encoder.strides='[2,2]' \
#     algorithm.input_noise_std=0.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0008929621055948098 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 168: wasserstein=0.13054, mse=0.12572
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     experiment=robustad/ae_agnostic \
#     experiment_name=robustad_ae_pareto \
#     run_name=wasserstein_t168 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_shifted_normal_all \
#     data.image_size=[128,128] \
#     algorithm.delta=1.0 \
#     algorithm.encoder.activation=silu \
#     algorithm.encoder.batchnorm=False \
#     algorithm.encoder.nodes='[8,16,32]' \
#     algorithm.encoder.strides='[2,2]' \
#     algorithm.input_noise_std=0.005 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=3.694569188265505e-05 \
#     algorithm.optimizer.weight_decay=0.001 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 169: wasserstein=0.13049, mse=0.12583
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     experiment=robustad/ae_agnostic \
#     experiment_name=robustad_ae_pareto \
#     run_name=wasserstein_t169 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_shifted_normal_all \
#     data.image_size=[128,128] \
#     algorithm.delta=1.0 \
#     algorithm.encoder.activation=silu \
#     algorithm.encoder.batchnorm=False \
#     algorithm.encoder.nodes='[8,16,32]' \
#     algorithm.encoder.strides='[2,2]' \
#     algorithm.input_noise_std=0.005 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=3.690469495439858e-05 \
#     algorithm.optimizer.weight_decay=0.001 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 173: wasserstein=0.13105, mse=0.12454  << KNEE
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     experiment=robustad/ae_agnostic \
#     experiment_name=robustad_ae_pareto \
#     run_name=wasserstein_t173 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_shifted_normal_all \
#     data.image_size=[128,128] \
#     algorithm.delta=1.0 \
#     algorithm.encoder.activation=silu \
#     algorithm.encoder.batchnorm=False \
#     algorithm.encoder.nodes='[8,16,32]' \
#     algorithm.encoder.strides='[2,2]' \
#     algorithm.input_noise_std=0.005 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=3.735656185083139e-05 \
#     algorithm.optimizer.weight_decay=0.001 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[3]

# ------------------------------------------------------------------------
# trial 174: wasserstein=0.13084, mse=0.12507
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     experiment=robustad/ae_agnostic \
#     experiment_name=robustad_ae_pareto \
#     run_name=wasserstein_t174 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_shifted_normal_all \
#     data.image_size=[128,128] \
#     algorithm.delta=1.0 \
#     algorithm.encoder.activation=silu \
#     algorithm.encoder.batchnorm=False \
#     algorithm.encoder.nodes='[8,16,32]' \
#     algorithm.encoder.strides='[2,2]' \
#     algorithm.input_noise_std=0.005 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=3.7169410261795384e-05 \
#     algorithm.optimizer.weight_decay=0.001 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 175: wasserstein=0.13063, mse=0.12551
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     experiment=robustad/ae_agnostic \
#     experiment_name=robustad_ae_pareto \
#     run_name=wasserstein_t175 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_shifted_normal_all \
#     data.image_size=[128,128] \
#     algorithm.delta=1.0 \
#     algorithm.encoder.activation=silu \
#     algorithm.encoder.batchnorm=False \
#     algorithm.encoder.nodes='[8,16,32]' \
#     algorithm.encoder.strides='[2,2]' \
#     algorithm.input_noise_std=0.005 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=3.7018558082613986e-05 \
#     algorithm.optimizer.weight_decay=0.001 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 299: wasserstein=0.13511, mse=0.0063479  << ORIGINAL PICK
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     experiment=robustad/ae_agnostic \
#     experiment_name=robustad_ae_pareto \
#     run_name=wasserstein_t299 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_shifted_normal_all \
#     data.image_size=[128,128] \
#     algorithm.delta=0.5 \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.batchnorm=False \
#     algorithm.encoder.nodes='[32,64,128]' \
#     algorithm.encoder.strides='[2,2]' \
#     algorithm.input_noise_std=0.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0008732384971448825 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 302: wasserstein=0.13624, mse=0.0062128
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     experiment=robustad/ae_agnostic \
#     experiment_name=robustad_ae_pareto \
#     run_name=wasserstein_t302 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_shifted_normal_all \
#     data.image_size=[128,128] \
#     algorithm.delta=0.5 \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.batchnorm=False \
#     algorithm.encoder.nodes='[32,64,128]' \
#     algorithm.encoder.strides='[2,2]' \
#     algorithm.input_noise_std=0.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0008785093438031058 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[3]

# ------------------------------------------------------------------------
# trial 445: wasserstein=0.070693, mse=0.32492  << BEST wasserstein
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     experiment=robustad/ae_agnostic \
#     experiment_name=robustad_ae_pareto \
#     run_name=wasserstein_t445 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_shifted_normal_all \
#     data.image_size=[128,128] \
#     algorithm.delta=0.5 \
#     algorithm.encoder.activation=silu \
#     algorithm.encoder.batchnorm=False \
#     algorithm.encoder.nodes='[8,16,32]' \
#     algorithm.encoder.strides='[2,2]' \
#     algorithm.input_noise_std=0.03 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=3.0025944429716033e-05 \
#     algorithm.optimizer.weight_decay=0.001 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 486: wasserstein=0.13256, mse=0.11368
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     experiment=robustad/ae_agnostic \
#     experiment_name=robustad_ae_pareto \
#     run_name=wasserstein_t486 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_shifted_normal_all \
#     data.image_size=[128,128] \
#     algorithm.delta=0.5 \
#     algorithm.encoder.activation=silu \
#     algorithm.encoder.batchnorm=False \
#     algorithm.encoder.nodes='[8,16,32]' \
#     algorithm.encoder.strides='[2,2]' \
#     algorithm.input_noise_std=0.03 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=5.3578927589988375e-05 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 487: wasserstein=0.13276, mse=0.11318
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     experiment=robustad/ae_agnostic \
#     experiment_name=robustad_ae_pareto \
#     run_name=wasserstein_t487 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_shifted_normal_all \
#     data.image_size=[128,128] \
#     algorithm.delta=0.5 \
#     algorithm.encoder.activation=silu \
#     algorithm.encoder.batchnorm=False \
#     algorithm.encoder.nodes='[8,16,32]' \
#     algorithm.encoder.strides='[2,2]' \
#     algorithm.input_noise_std=0.03 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=5.3781140001401564e-05 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 489: wasserstein=0.13237, mse=0.11439
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     experiment=robustad/ae_agnostic \
#     experiment_name=robustad_ae_pareto \
#     run_name=wasserstein_t489 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_shifted_normal_all \
#     data.image_size=[128,128] \
#     algorithm.delta=0.5 \
#     algorithm.encoder.activation=silu \
#     algorithm.encoder.batchnorm=False \
#     algorithm.encoder.nodes='[8,16,32]' \
#     algorithm.encoder.strides='[2,2]' \
#     algorithm.input_noise_std=0.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=5.332059953565463e-05 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[3]

# ========================================================================
# SUBMIT EVERYTHING ABOVE TO CLARIDEN  (one slurm job per command)
# ========================================================================
# Set paths.raw_data_dir to the data location on clariden; any extra
# hydra overrides appended here are added to every job.
# bash scripts/submit_pareto.sh scripts/robustad/runae_pareto.sh \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files
