# ========================================================================
# REALNVP PARETO-FRONT TRAINING COMMANDS
# ========================================================================
# These are the training commands for every point on the Pareto front of
# each validation strategy. Generated by scripts/make_pareto_scripts.py from
# notebooks/paretos/robustad/ -- regenerate rather than edit by hand.
#
# Run from the repository root. All commands are commented out -- uncomment
# the points you want to run locally (taskset pinning, GPUs cycling 0-3).
# To run the WHOLE file on clariden instead, use the single submit command
# at the bottom: it sends every point above to slurm, one job each, via
# scripts/submit_pareto.sh (submitit launcher).

# ========================================================================
# CVAR25 TRAINING  (study: cvar25eff_vs_logp, 1 Pareto points)
# ========================================================================
# ------------------------------------------------------------------------
# trial 333: cvar25eff=1000, logp=-5941.6  << ORIGINAL PICK | BEST cvar25eff
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     experiment=robustad/realnvp \
#     experiment_name=robustad_realnvp_pareto \
#     run_name=cvar25_t333 \
#     algorithm.flow.activation=silu \
#     algorithm.flow.hidden_dim=384 \
#     algorithm.flow.n_flows=6 \
#     algorithm.flow.n_hidden_layers=2 \
#     algorithm.flow.noise_scale=0.001 \
#     algorithm.flow.scale_clamp=3.0 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0005803855298399076 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[0]

# ========================================================================
# CAP TRAINING  (study: cap_vs_logp, 17 Pareto points)
# ========================================================================
# ------------------------------------------------------------------------
# trial 1: cap=-0.70182, logp=-5865.6
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     experiment=robustad/realnvp_agnostic \
#     experiment_name=robustad_realnvp_pareto \
#     run_name=cap_t1 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_shifted_normal_all \
#     algorithm.flow.activation=silu \
#     algorithm.flow.hidden_dim=512 \
#     algorithm.flow.n_flows=6 \
#     algorithm.flow.n_hidden_layers=2 \
#     algorithm.flow.noise_scale=0.001 \
#     algorithm.flow.scale_clamp=3.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.00023730641572913702 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=2.0 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 75: cap=-0.69351, logp=-5548.4
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     experiment=robustad/realnvp_agnostic \
#     experiment_name=robustad_realnvp_pareto \
#     run_name=cap_t75 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_shifted_normal_all \
#     algorithm.flow.activation=silu \
#     algorithm.flow.hidden_dim=512 \
#     algorithm.flow.n_flows=6 \
#     algorithm.flow.n_hidden_layers=1 \
#     algorithm.flow.noise_scale=0.001 \
#     algorithm.flow.scale_clamp=5.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.00048291571723890585 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=2.0 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 129: cap=-0.49417, logp=5595.7
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     experiment=robustad/realnvp_agnostic \
#     experiment_name=robustad_realnvp_pareto \
#     run_name=cap_t129 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_shifted_normal_all \
#     algorithm.flow.activation=gelu \
#     algorithm.flow.hidden_dim=512 \
#     algorithm.flow.n_flows=4 \
#     algorithm.flow.n_hidden_layers=2 \
#     algorithm.flow.noise_scale=0.01 \
#     algorithm.flow.scale_clamp=3.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0009554869257818856 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 151: cap=-0.69477, logp=-5658.8
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     experiment=robustad/realnvp_agnostic \
#     experiment_name=robustad_realnvp_pareto \
#     run_name=cap_t151 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_shifted_normal_all \
#     algorithm.flow.activation=gelu \
#     algorithm.flow.hidden_dim=384 \
#     algorithm.flow.n_flows=6 \
#     algorithm.flow.n_hidden_layers=2 \
#     algorithm.flow.noise_scale=0.001 \
#     algorithm.flow.scale_clamp=3.0 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.00028020537947117335 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=2.0 \
#     trainer=gpu \
#     trainer.devices=[3]

# ------------------------------------------------------------------------
# trial 155: cap=-0.6934, logp=-5329.3
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     experiment=robustad/realnvp_agnostic \
#     experiment_name=robustad_realnvp_pareto \
#     run_name=cap_t155 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_shifted_normal_all \
#     algorithm.flow.activation=gelu \
#     algorithm.flow.hidden_dim=512 \
#     algorithm.flow.n_flows=4 \
#     algorithm.flow.n_hidden_layers=2 \
#     algorithm.flow.noise_scale=0.01 \
#     algorithm.flow.scale_clamp=3.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0009059923822361195 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 174: cap=-0.41213, logp=7420.4  << ORIGINAL PICK | BEST cap
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     experiment=robustad/realnvp_agnostic \
#     experiment_name=robustad_realnvp_pareto \
#     run_name=cap_t174 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_shifted_normal_all \
#     algorithm.flow.activation=gelu \
#     algorithm.flow.hidden_dim=512 \
#     algorithm.flow.n_flows=4 \
#     algorithm.flow.n_hidden_layers=2 \
#     algorithm.flow.noise_scale=0.01 \
#     algorithm.flow.scale_clamp=3.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0009974062369047898 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 222: cap=-0.69421, logp=-5644.4
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     experiment=robustad/realnvp_agnostic \
#     experiment_name=robustad_realnvp_pareto \
#     run_name=cap_t222 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_shifted_normal_all \
#     algorithm.flow.activation=gelu \
#     algorithm.flow.hidden_dim=512 \
#     algorithm.flow.n_flows=4 \
#     algorithm.flow.n_hidden_layers=2 \
#     algorithm.flow.noise_scale=0.01 \
#     algorithm.flow.scale_clamp=3.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0009995327504087237 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 334: cap=-0.69953, logp=-5865
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     experiment=robustad/realnvp_agnostic \
#     experiment_name=robustad_realnvp_pareto \
#     run_name=cap_t334 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_shifted_normal_all \
#     algorithm.flow.activation=silu \
#     algorithm.flow.hidden_dim=512 \
#     algorithm.flow.n_flows=6 \
#     algorithm.flow.n_hidden_layers=2 \
#     algorithm.flow.noise_scale=0.0 \
#     algorithm.flow.scale_clamp=3.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0009367405347214759 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[3]

# ------------------------------------------------------------------------
# trial 336: cap=-0.69706, logp=-5816.3
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     experiment=robustad/realnvp_agnostic \
#     experiment_name=robustad_realnvp_pareto \
#     run_name=cap_t336 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_shifted_normal_all \
#     algorithm.flow.activation=gelu \
#     algorithm.flow.hidden_dim=512 \
#     algorithm.flow.n_flows=6 \
#     algorithm.flow.n_hidden_layers=2 \
#     algorithm.flow.noise_scale=0.01 \
#     algorithm.flow.scale_clamp=3.0 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0009378276788694577 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=1.0 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 361: cap=-0.53791, logp=4437
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     experiment=robustad/realnvp_agnostic \
#     experiment_name=robustad_realnvp_pareto \
#     run_name=cap_t361 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_shifted_normal_all \
#     algorithm.flow.activation=gelu \
#     algorithm.flow.hidden_dim=384 \
#     algorithm.flow.n_flows=4 \
#     algorithm.flow.n_hidden_layers=2 \
#     algorithm.flow.noise_scale=0.01 \
#     algorithm.flow.scale_clamp=5.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0009421509286165142 \
#     algorithm.optimizer.weight_decay=1e-06 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 401: cap=-0.69342, logp=-5421.8
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     experiment=robustad/realnvp_agnostic \
#     experiment_name=robustad_realnvp_pareto \
#     run_name=cap_t401 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_shifted_normal_all \
#     algorithm.flow.activation=gelu \
#     algorithm.flow.hidden_dim=512 \
#     algorithm.flow.n_flows=4 \
#     algorithm.flow.n_hidden_layers=2 \
#     algorithm.flow.noise_scale=0.01 \
#     algorithm.flow.scale_clamp=3.0 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0009485644316340529 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=1.0 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 402: cap=-0.69343, logp=-5474
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     experiment=robustad/realnvp_agnostic \
#     experiment_name=robustad_realnvp_pareto \
#     run_name=cap_t402 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_shifted_normal_all \
#     algorithm.flow.activation=gelu \
#     algorithm.flow.hidden_dim=512 \
#     algorithm.flow.n_flows=4 \
#     algorithm.flow.n_hidden_layers=2 \
#     algorithm.flow.noise_scale=0.01 \
#     algorithm.flow.scale_clamp=3.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0009451857442009206 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=1.0 \
#     trainer=gpu \
#     trainer.devices=[3]

# ------------------------------------------------------------------------
# trial 459: cap=-0.69337, logp=-5152.1
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     experiment=robustad/realnvp_agnostic \
#     experiment_name=robustad_realnvp_pareto \
#     run_name=cap_t459 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_shifted_normal_all \
#     algorithm.flow.activation=gelu \
#     algorithm.flow.hidden_dim=512 \
#     algorithm.flow.n_flows=6 \
#     algorithm.flow.n_hidden_layers=2 \
#     algorithm.flow.noise_scale=0.01 \
#     algorithm.flow.scale_clamp=5.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0009999722525038653 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=1.0 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 460: cap=-0.69337, logp=-4489.3
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     experiment=robustad/realnvp_agnostic \
#     experiment_name=robustad_realnvp_pareto \
#     run_name=cap_t460 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_shifted_normal_all \
#     algorithm.flow.activation=gelu \
#     algorithm.flow.hidden_dim=512 \
#     algorithm.flow.n_flows=6 \
#     algorithm.flow.n_hidden_layers=2 \
#     algorithm.flow.noise_scale=0.01 \
#     algorithm.flow.scale_clamp=5.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0009990716645564683 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=1.0 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 492: cap=-0.69893, logp=-5847.5
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     experiment=robustad/realnvp_agnostic \
#     experiment_name=robustad_realnvp_pareto \
#     run_name=cap_t492 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_shifted_normal_all \
#     algorithm.flow.activation=gelu \
#     algorithm.flow.hidden_dim=384 \
#     algorithm.flow.n_flows=6 \
#     algorithm.flow.n_hidden_layers=2 \
#     algorithm.flow.noise_scale=0.01 \
#     algorithm.flow.scale_clamp=3.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0009475774556099292 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=2.0 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 494: cap=-0.69337, logp=-5040.7
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     experiment=robustad/realnvp_agnostic \
#     experiment_name=robustad_realnvp_pareto \
#     run_name=cap_t494 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_shifted_normal_all \
#     algorithm.flow.activation=gelu \
#     algorithm.flow.hidden_dim=384 \
#     algorithm.flow.n_flows=6 \
#     algorithm.flow.n_hidden_layers=2 \
#     algorithm.flow.noise_scale=0.01 \
#     algorithm.flow.scale_clamp=5.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0009987165236353117 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=1.0 \
#     trainer=gpu \
#     trainer.devices=[3]

# ------------------------------------------------------------------------
# trial 576: cap=-0.69333, logp=-1950.6  << KNEE
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     experiment=robustad/realnvp_agnostic \
#     experiment_name=robustad_realnvp_pareto \
#     run_name=cap_t576 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_shifted_normal_all \
#     algorithm.flow.activation=relu \
#     algorithm.flow.hidden_dim=512 \
#     algorithm.flow.n_flows=4 \
#     algorithm.flow.n_hidden_layers=2 \
#     algorithm.flow.noise_scale=0.01 \
#     algorithm.flow.scale_clamp=5.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0009999622718848465 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[0]

# ========================================================================
# STABILITY TRAINING  (study: drift_vs_logp, 2 Pareto points)
# ========================================================================
# ------------------------------------------------------------------------
# trial 395: drift=1.0296, logp=-5686.1
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     experiment=robustad/realnvp_agnostic \
#     experiment_name=robustad_realnvp_pareto \
#     run_name=stability_t395 \
#     callbacks.wasserstein_dist=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_shifted_normal_all \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_shifted_normal_all \
#     algorithm.flow.activation=silu \
#     algorithm.flow.hidden_dim=512 \
#     algorithm.flow.n_flows=6 \
#     algorithm.flow.n_hidden_layers=2 \
#     algorithm.flow.noise_scale=0.001 \
#     algorithm.flow.scale_clamp=5.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0005068011102426593 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 478: drift=0.068993, logp=-5360.6  << ORIGINAL PICK | BEST drift
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     experiment=robustad/realnvp_agnostic \
#     experiment_name=robustad_realnvp_pareto \
#     run_name=stability_t478 \
#     callbacks.wasserstein_dist=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_shifted_normal_all \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_shifted_normal_all \
#     algorithm.flow.activation=gelu \
#     algorithm.flow.hidden_dim=512 \
#     algorithm.flow.n_flows=6 \
#     algorithm.flow.n_hidden_layers=2 \
#     algorithm.flow.noise_scale=0.001 \
#     algorithm.flow.scale_clamp=5.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0005363051745828947 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[1]

# ========================================================================
# WASSERSTEIN TRAINING  (study: wasserstein_vs_logp, 48 Pareto points, trimmed to 13 around the knee (endpoints kept))
# ========================================================================
# ------------------------------------------------------------------------
# trial 145: wasserstein=5.6677, logp=287
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     experiment=robustad/realnvp_agnostic \
#     experiment_name=robustad_realnvp_pareto \
#     run_name=wasserstein_t145 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_shifted_normal_all \
#     algorithm.flow.activation=silu \
#     algorithm.flow.hidden_dim=384 \
#     algorithm.flow.n_flows=4 \
#     algorithm.flow.n_hidden_layers=1 \
#     algorithm.flow.noise_scale=0.0001 \
#     algorithm.flow.scale_clamp=5.0 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.00031880204120849763 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 187: wasserstein=6.6326, logp=-1415.6
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     experiment=robustad/realnvp_agnostic \
#     experiment_name=robustad_realnvp_pareto \
#     run_name=wasserstein_t187 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_shifted_normal_all \
#     algorithm.flow.activation=gelu \
#     algorithm.flow.hidden_dim=128 \
#     algorithm.flow.n_flows=4 \
#     algorithm.flow.n_hidden_layers=2 \
#     algorithm.flow.noise_scale=0.0001 \
#     algorithm.flow.scale_clamp=5.0 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.00032241866063603474 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 205: wasserstein=6.7346, logp=-3207.2
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     experiment=robustad/realnvp_agnostic \
#     experiment_name=robustad_realnvp_pareto \
#     run_name=wasserstein_t205 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_shifted_normal_all \
#     algorithm.flow.activation=gelu \
#     algorithm.flow.hidden_dim=128 \
#     algorithm.flow.n_flows=4 \
#     algorithm.flow.n_hidden_layers=2 \
#     algorithm.flow.noise_scale=0.0001 \
#     algorithm.flow.scale_clamp=5.0 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0004292831184638859 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 266: wasserstein=6.9197, logp=-3816.8
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     experiment=robustad/realnvp_agnostic \
#     experiment_name=robustad_realnvp_pareto \
#     run_name=wasserstein_t266 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_shifted_normal_all \
#     algorithm.flow.activation=gelu \
#     algorithm.flow.hidden_dim=128 \
#     algorithm.flow.n_flows=4 \
#     algorithm.flow.n_hidden_layers=2 \
#     algorithm.flow.noise_scale=0.0001 \
#     algorithm.flow.scale_clamp=5.0 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0003624115308498231 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[3]

# ------------------------------------------------------------------------
# trial 316: wasserstein=9.0257, logp=-5938.3
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     experiment=robustad/realnvp_agnostic \
#     experiment_name=robustad_realnvp_pareto \
#     run_name=wasserstein_t316 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_shifted_normal_all \
#     algorithm.flow.activation=silu \
#     algorithm.flow.hidden_dim=512 \
#     algorithm.flow.n_flows=6 \
#     algorithm.flow.n_hidden_layers=2 \
#     algorithm.flow.noise_scale=0.0001 \
#     algorithm.flow.scale_clamp=3.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0004158351606745154 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=1.0 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 334: wasserstein=6.3366, logp=95.795  << KNEE
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     experiment=robustad/realnvp_agnostic \
#     experiment_name=robustad_realnvp_pareto \
#     run_name=wasserstein_t334 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_shifted_normal_all \
#     algorithm.flow.activation=gelu \
#     algorithm.flow.hidden_dim=384 \
#     algorithm.flow.n_flows=4 \
#     algorithm.flow.n_hidden_layers=2 \
#     algorithm.flow.noise_scale=0.0001 \
#     algorithm.flow.scale_clamp=5.0 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0003722058179167373 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 353: wasserstein=0.093309, logp=3636.2  << BEST wasserstein
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     experiment=robustad/realnvp_agnostic \
#     experiment_name=robustad_realnvp_pareto \
#     run_name=wasserstein_t353 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_shifted_normal_all \
#     algorithm.flow.activation=gelu \
#     algorithm.flow.hidden_dim=128 \
#     algorithm.flow.n_flows=4 \
#     algorithm.flow.n_hidden_layers=2 \
#     algorithm.flow.noise_scale=0.0001 \
#     algorithm.flow.scale_clamp=5.0 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.00033090336179045395 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 390: wasserstein=5.1145, logp=304.63
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     experiment=robustad/realnvp_agnostic \
#     experiment_name=robustad_realnvp_pareto \
#     run_name=wasserstein_t390 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_shifted_normal_all \
#     algorithm.flow.activation=gelu \
#     algorithm.flow.hidden_dim=384 \
#     algorithm.flow.n_flows=4 \
#     algorithm.flow.n_hidden_layers=1 \
#     algorithm.flow.noise_scale=0.0001 \
#     algorithm.flow.scale_clamp=5.0 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0003429730574286582 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[3]

# ------------------------------------------------------------------------
# trial 441: wasserstein=6.8215, logp=-3388.4
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     experiment=robustad/realnvp_agnostic \
#     experiment_name=robustad_realnvp_pareto \
#     run_name=wasserstein_t441 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_shifted_normal_all \
#     algorithm.flow.activation=gelu \
#     algorithm.flow.hidden_dim=512 \
#     algorithm.flow.n_flows=6 \
#     algorithm.flow.n_hidden_layers=1 \
#     algorithm.flow.noise_scale=0.0001 \
#     algorithm.flow.scale_clamp=3.0 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0003321731349910679 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 493: wasserstein=6.4855, logp=-227.49
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     experiment=robustad/realnvp_agnostic \
#     experiment_name=robustad_realnvp_pareto \
#     run_name=wasserstein_t493 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_shifted_normal_all \
#     algorithm.flow.activation=gelu \
#     algorithm.flow.hidden_dim=384 \
#     algorithm.flow.n_flows=4 \
#     algorithm.flow.n_hidden_layers=1 \
#     algorithm.flow.noise_scale=0.0001 \
#     algorithm.flow.scale_clamp=3.0 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0003444190171357356 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 565: wasserstein=2.7226, logp=375.04
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     experiment=robustad/realnvp_agnostic \
#     experiment_name=robustad_realnvp_pareto \
#     run_name=wasserstein_t565 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_shifted_normal_all \
#     algorithm.flow.activation=gelu \
#     algorithm.flow.hidden_dim=512 \
#     algorithm.flow.n_flows=4 \
#     algorithm.flow.n_hidden_layers=2 \
#     algorithm.flow.noise_scale=0.0001 \
#     algorithm.flow.scale_clamp=5.0 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.00032823526646351555 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 583: wasserstein=4.8632, logp=315.27
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     experiment=robustad/realnvp_agnostic \
#     experiment_name=robustad_realnvp_pareto \
#     run_name=wasserstein_t583 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_shifted_normal_all \
#     algorithm.flow.activation=gelu \
#     algorithm.flow.hidden_dim=512 \
#     algorithm.flow.n_flows=4 \
#     algorithm.flow.n_hidden_layers=2 \
#     algorithm.flow.noise_scale=0.0001 \
#     algorithm.flow.scale_clamp=5.0 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0004432376354027556 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[3]

# ------------------------------------------------------------------------
# trial 591: wasserstein=0.70366, logp=2206.5  << ORIGINAL PICK
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     experiment=robustad/realnvp_agnostic \
#     experiment_name=robustad_realnvp_pareto \
#     run_name=wasserstein_t591 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_shifted_normal_all \
#     algorithm.flow.activation=gelu \
#     algorithm.flow.hidden_dim=512 \
#     algorithm.flow.n_flows=4 \
#     algorithm.flow.n_hidden_layers=2 \
#     algorithm.flow.noise_scale=0.0001 \
#     algorithm.flow.scale_clamp=5.0 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0004475901389689921 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[0]

# ========================================================================
# SUBMIT EVERYTHING ABOVE TO CLARIDEN  (one slurm job per command)
# ========================================================================
# Set paths.raw_data_dir to the data location on clariden; any extra
# hydra overrides appended here are added to every job.
# bash scripts/submit_pareto.sh scripts/robustad/runrealnvp_pareto.sh \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files
