# Template AE configuration.
defaults:
  - _self_

_target_: src.algorithms.ae.AE
features: null 

input_noise_std: 0.0001

target_rate: 0.25 # nominal rate
base_rate: 28608.8064 # bunch crossing rate in kHz

encoder:
  _target_: src.algorithms.components.encoder.Encoder
  in_dim: 117
  nodes: [64, 32, 8]
  activation: relu

decoder:
  _target_: src.algorithms.components.decoder.Decoder
  nodes: ${reverse:${algorithm.encoder.nodes}} # nodes of the encoder, but in reverse
  activation: relu
  out_dim: ${algorithm.encoder.in_dim}

delta: 3.0
