defaults:
  - _self_

_target_: src.algorithms.dsae.DeepSetsAE
features: null

mask: true
input_noise_std: 0.0001

operational_rate: 0.25 # nominal rate
bc_rate: 28608.8064 # bunch crossing rate in kHz

encoder:
  _target_: src.algorithms.components.encoder.DeepSetsEncoder

  object_dims:
    FET: 3
    egammas: 3
    jets: 3
    muons: 3
    taus: 3

  object_phi_nodes:
    FET: [8]
    egammas: [16, 8]
    jets: [16, 8]
    muons: [8]
    taus: [16, 8]

  rho_nodes: [32, 16]
  activation: relu
  pooling: sum
  add_counts: false

decoder:
  _target_: src.algorithms.components.decoder.Decoder
  nodes: ${reverse:${algorithm.encoder.rho_nodes}}
  activation: relu
  out_dim: 117

loss:
  _target_: src.algorithms.losses.ae.HuberAELoss
  delta: 3.0
  reduction: none

mse:
  _target_: src.algorithms.losses.components.reconstruction.MSEReconstructionLoss
  reduction: none
