defaults:
  - _self_

_target_: src.algorithms.realnvp.RealNVP
features: null
ckpt: ''

target_rate: 0.01
base_rate: null

flow:
    _target_: src.algorithms.components.flow.RealNVP
    input_dim: 3072
    n_flows: 6
    hidden_dim: 512
    n_hidden_layers: 2
    activation: relu
    noise_scale: 0.0
    scale_clamp: 5.0
