# @package algorithm

_target_: src.algorithms.jetclr.JetCLR

seed: ${seed}
diagnosis_metrics: true
sync_dist_metrics: true
ckpt: ""

feature_blur: null

detector_smearing:
  _target_: src.algorithms.components.augmentation.FastDetectorSmearing
  _partial_: true
  prob: 0.80
  strength: 0.50

object_mask:
  _target_: src.algorithms.components.augmentation.FastObjectDropout
  prob: 0.80
  object_prob: 0.05
  protected_object_types: [FET, MET]

lorentz_rotation:
  _target_: src.algorithms.components.augmentation.FastLorentzRotation
  _partial_: true
  prob: 0.50

model:
  _target_: src.algorithms.components.jet_encoder.ObjectTransformerEncoder
  feature_names: [Et, eta, phi]
  object_types: [FET, MET, egammas, jets, muons, taus]
  feature_dim: 3
  d_model: 128
  out_dim: 128
  n_heads: 8
  n_layers: 4
  dim_feedforward: 512
  dropout: 0.1
  activation: gelu
  pooling: cls

projector:
  _target_: src.algorithms.components.mlp.MLP
  in_dim: ${algorithm.model.out_dim}
  nodes: [256, 256]
  out_dim: 128
  batchnorm: true
  activation: gelu

loss:
  _target_: src.algorithms.losses.contrastive.NTXentLoss
  temperature: 0.10
  gather_distributed: true

optimizer:
  _partial_: true
  _target_: torch.optim.AdamW
  lr: 0.0003
  weight_decay: 0.0001
  betas: [0.9, 0.99]
  eps: 1e-6

scheduler:
  scheduler:
    _target_: src.algorithms.schedulers.cdw.CosineWithWarmup
    _partial_: true
    warmup_ratio: 0.05
    min_lr_ratio: 0.05
    warmup_start_ratio: 1e-3
