defaults:
  - _self_

_target_: src.algorithms.realnvp.RealNVP
features: null
ckpt: ''

operational_rate: 0.25 # nominal rate
bc_rate: 28608.8064 # bunch crossing rate in kHz

flow:
  _target_: src.algorithms.components.flow.RealNVP
  input_dim: 117
  n_flows: 6
  hidden_dim: 32
  n_hidden_layers: 2
  activation: relu
  noise_scale: 0.0
  scale_clamp: 5.0
