# Template Deep SVDD configuration.
defaults:
  - _self_

_target_: src.algorithms.svdd.DeepSVDD
features: null
ckpt: ""
pretrained_encoder_ckpt: ""
pretrained_encoder_prefix: encoder.
pretrained_encoder_strict: true
enforce_architecture_constraints: true

target_rate: 0.25 # nominal rate
base_rate: 28608.8064 # bunch crossing rate in kHz

encoder:
  _target_: src.algorithms.components.encoder.Encoder
  in_dim: 117
  nodes: [64, 32, 16]
  activation: relu
  bias: false
  batchnorm: false

center_init_method: mean
center_eps: 0.1
center_max_batches: null

objective: one_class
nu: 0.1
network_weight_decay: 1e-6
radius_warmup_epochs: 10

optimizer:
  _partial_: true
  _target_: torch.optim.Adam
  lr: 1.0e-3
  weight_decay: 0.0
  betas: [0.9, 0.999]
  eps: 1.0e-8
