# Template Deep SVDD configuration.
defaults:
  - _self_

_target_: src.algorithms.svdd.DeepSVDD
features: null
ckpt: ''

target_rate: 0.25 # nominal rate
base_rate: 28608.8064 # bunch crossing rate in kHz

encoder:
  _target_: src.algorithms.components.encoder.Encoder
  in_dim: 117
  nodes: [64, 32, 16]
  activation: relu

center_init_method: mean

nu: 0.1
weight_decay: 1e-6
soft_boundary: False
