# Template VAE configuration.
defaults:
  - _self_

_target_: src.algorithms.vae.VAE
features: null

operational_rate: 0.25 # nominal rate
bc_rate: 28608.8064 # bunch crossing rate in kHz

mask: true
ckpt: ''

encoder:
  _target_: src.algorithms.components.encoder.VariationalEncoder
  in_dim: 117
  nodes: [64, 32, 8]
  activation: relu
  clamp_zlogvar_range: [-20.0, 10.0]

decoder:
  _target_: src.algorithms.components.decoder.Decoder
  nodes: ${smaller_decoder:${algorithm.encoder.nodes}}
  activation: relu
  out_dim: ${algorithm.encoder.in_dim}

loss:
  _target_: src.algorithms.losses.vae.ClassicVAELoss
  scale: 1
  kl_scale: 0.001

# Annealing of the KL scale scalar.
kl_warmup_frac: 0.2
