# Template VAE configuration.
defaults:
  - _self_

_target_: src.algorithms.vae.VAE
features: null

target_rate: 0.25 # nominal rate
base_rate: 28608.8064 # bunch crossing rate in kHz

ckpt: ''

encoder:
  _target_: src.algorithms.components.encoder.VariationalEncoder
  in_dim: 117
  nodes: [64, 32, 8]
  activation: relu
  clamp_zlogvar_range: [-20.0, 10.0]

decoder:
  _target_: src.algorithms.components.decoder.Decoder
  nodes: ${smaller_decoder:${algorithm.encoder.nodes}}
  activation: relu
  out_dim: ${algorithm.encoder.in_dim}

# Annealing of the KL scale scalar.
kl_warmup_frac: 0.2
kl_scale: 1.0
