# ========================================================================
# AE PARETO-FRONT TRAINING COMMANDS
# ========================================================================
# These are the training commands for every point on the Pareto front of
# each validation strategy. Generated by scripts/make_pareto_scripts.py from
# notebooks/paretos/cifar10/ -- regenerate rather than edit by hand.
#
# Run from the repository root. All commands are commented out -- uncomment
# the points you want to run locally (taskset pinning, GPUs cycling 0-3).
# To run the WHOLE file on clariden instead, use the single submit command
# at the bottom: it sends every point above to slurm, one job each, via
# scripts/submit_pareto.sh (submitit launcher).

# ========================================================================
# CVAR25 TRAINING  (study: cvar25eff_vs_mse, 13 Pareto points)
# ========================================================================
# ------------------------------------------------------------------------
# trial 180: cvar25eff=23.333, mse=0.12587
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     experiment=cifar10/ae \
#     experiment_name=cifar10_ae_pareto \
#     run_name=cvar25_t180 \
#     algorithm.delta=5.0 \
#     algorithm.encoder.activation=silu \
#     algorithm.encoder.nodes='[64,128,256]' \
#     algorithm.encoder.strides='[2,1]' \
#     algorithm.input_noise_std=0.05 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0015708831079384806 \
#     algorithm.optimizer.weight_decay=0.0005 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 212: cvar25eff=23.6, mse=0.12818
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     experiment=cifar10/ae \
#     experiment_name=cifar10_ae_pareto \
#     run_name=cvar25_t212 \
#     algorithm.delta=5.0 \
#     algorithm.encoder.activation=silu \
#     algorithm.encoder.nodes='[64,128,256]' \
#     algorithm.encoder.strides='[2,1]' \
#     algorithm.input_noise_std=0.05 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.00162985471707567 \
#     algorithm.optimizer.weight_decay=0.0005 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 279: cvar25eff=22.067, mse=0.11038  << KNEE
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     experiment=cifar10/ae \
#     experiment_name=cifar10_ae_pareto \
#     run_name=cvar25_t279 \
#     algorithm.delta=5.0 \
#     algorithm.encoder.activation=silu \
#     algorithm.encoder.nodes='[64,128,256]' \
#     algorithm.encoder.strides='[2,2]' \
#     algorithm.input_noise_std=0.05 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0016948589402705524 \
#     algorithm.optimizer.weight_decay=0.0005 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 280: cvar25eff=20.267, mse=0.10727
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     experiment=cifar10/ae \
#     experiment_name=cifar10_ae_pareto \
#     run_name=cvar25_t280 \
#     algorithm.delta=5.0 \
#     algorithm.encoder.activation=silu \
#     algorithm.encoder.nodes='[64,128,256]' \
#     algorithm.encoder.strides='[2,2]' \
#     algorithm.input_noise_std=0.05 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.001695020478409861 \
#     algorithm.optimizer.weight_decay=0.0005 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[3]

# ------------------------------------------------------------------------
# trial 285: cvar25eff=19.4, mse=0.10567
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     experiment=cifar10/ae \
#     experiment_name=cifar10_ae_pareto \
#     run_name=cvar25_t285 \
#     algorithm.delta=5.0 \
#     algorithm.encoder.activation=silu \
#     algorithm.encoder.nodes='[64,128,256]' \
#     algorithm.encoder.strides='[2,2]' \
#     algorithm.input_noise_std=0.0 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0016494530578202288 \
#     algorithm.optimizer.weight_decay=0.0005 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 289: cvar25eff=19.867, mse=0.10657
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     experiment=cifar10/ae \
#     experiment_name=cifar10_ae_pareto \
#     run_name=cvar25_t289 \
#     algorithm.delta=5.0 \
#     algorithm.encoder.activation=silu \
#     algorithm.encoder.nodes='[64,128,256]' \
#     algorithm.encoder.strides='[2,2]' \
#     algorithm.input_noise_std=0.05 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0016000657232323832 \
#     algorithm.optimizer.weight_decay=0.0005 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 294: cvar25eff=19.133, mse=0.10503
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     experiment=cifar10/ae \
#     experiment_name=cifar10_ae_pareto \
#     run_name=cvar25_t294 \
#     algorithm.delta=5.0 \
#     algorithm.encoder.activation=silu \
#     algorithm.encoder.nodes='[64,128,256]' \
#     algorithm.encoder.strides='[2,2]' \
#     algorithm.input_noise_std=0.05 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0015968285227598573 \
#     algorithm.optimizer.weight_decay=0.0005 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 343: cvar25eff=20.6, mse=0.10743
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     experiment=cifar10/ae \
#     experiment_name=cifar10_ae_pareto \
#     run_name=cvar25_t343 \
#     algorithm.delta=5.0 \
#     algorithm.encoder.activation=silu \
#     algorithm.encoder.nodes='[64,128,256]' \
#     algorithm.encoder.strides='[2,2]' \
#     algorithm.input_noise_std=0.05 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0016944754939187657 \
#     algorithm.optimizer.weight_decay=0.0005 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[3]

# ------------------------------------------------------------------------
# trial 405: cvar25eff=19.533, mse=0.10642
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     experiment=cifar10/ae \
#     experiment_name=cifar10_ae_pareto \
#     run_name=cvar25_t405 \
#     algorithm.delta=5.0 \
#     algorithm.encoder.activation=silu \
#     algorithm.encoder.nodes='[64,128,256]' \
#     algorithm.encoder.strides='[2,2]' \
#     algorithm.input_noise_std=0.1 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0015449361649309847 \
#     algorithm.optimizer.weight_decay=0.0005 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 407: cvar25eff=18.933, mse=0.1049
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     experiment=cifar10/ae \
#     experiment_name=cifar10_ae_pareto \
#     run_name=cvar25_t407 \
#     algorithm.delta=5.0 \
#     algorithm.encoder.activation=silu \
#     algorithm.encoder.nodes='[64,128,256]' \
#     algorithm.encoder.strides='[2,2]' \
#     algorithm.input_noise_std=0.1 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0015362890157314811 \
#     algorithm.optimizer.weight_decay=0.0005 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 452: cvar25eff=24.667, mse=0.13139
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     experiment=cifar10/ae \
#     experiment_name=cifar10_ae_pareto \
#     run_name=cvar25_t452 \
#     algorithm.delta=5.0 \
#     algorithm.encoder.activation=silu \
#     algorithm.encoder.nodes='[64,128,256]' \
#     algorithm.encoder.strides='[1,2]' \
#     algorithm.input_noise_std=0.05 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0018243897173109839 \
#     algorithm.optimizer.weight_decay=0.0005 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 528: cvar25eff=25, mse=0.13369
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     experiment=cifar10/ae \
#     experiment_name=cifar10_ae_pareto \
#     run_name=cvar25_t528 \
#     algorithm.delta=5.0 \
#     algorithm.encoder.activation=silu \
#     algorithm.encoder.nodes='[64,128,256]' \
#     algorithm.encoder.strides='[1,2]' \
#     algorithm.input_noise_std=0.05 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0017579406859508605 \
#     algorithm.optimizer.weight_decay=0.0005 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[3]

# ------------------------------------------------------------------------
# trial 592: cvar25eff=25.133, mse=0.13694  << ORIGINAL PICK | BEST cvar25eff
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     experiment=cifar10/ae \
#     experiment_name=cifar10_ae_pareto \
#     run_name=cvar25_t592 \
#     algorithm.delta=5.0 \
#     algorithm.encoder.activation=silu \
#     algorithm.encoder.nodes='[64,128,256]' \
#     algorithm.encoder.strides='[1,2]' \
#     algorithm.input_noise_std=0.05 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0017368497078662237 \
#     algorithm.optimizer.weight_decay=0.0005 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[0]

# ========================================================================
# CAP TRAINING  (study: cap_vs_mse, 28 Pareto points)
# ========================================================================
# ------------------------------------------------------------------------
# trial 51: cap=-0.18736, mse=0.11618
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     experiment=cifar10/ae_agnostic \
#     experiment_name=cifar10_ae_pareto \
#     run_name=cap_t51 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_reference_normal \
#     algorithm.delta=1.0 \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.nodes='[32,128,256]' \
#     algorithm.encoder.strides='[2,2]' \
#     algorithm.input_noise_std=0.1 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0023284227279765733 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=1.0 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 85: cap=-0.19025, mse=0.1118
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     experiment=cifar10/ae_agnostic \
#     experiment_name=cifar10_ae_pareto \
#     run_name=cap_t85 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_reference_normal \
#     algorithm.delta=1.0 \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.nodes='[64,128,256]' \
#     algorithm.encoder.strides='[2,1]' \
#     algorithm.input_noise_std=0.03 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.000518797301873547 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=1.0 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 117: cap=-0.18891, mse=0.11572
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     experiment=cifar10/ae_agnostic \
#     experiment_name=cifar10_ae_pareto \
#     run_name=cap_t117 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_reference_normal \
#     algorithm.delta=5.0 \
#     algorithm.encoder.activation=silu \
#     algorithm.encoder.nodes='[32,128,256]' \
#     algorithm.encoder.strides='[2,1]' \
#     algorithm.input_noise_std=0.0 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0010349827364424847 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=1.0 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 134: cap=-0.19241, mse=0.11065
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     experiment=cifar10/ae_agnostic \
#     experiment_name=cifar10_ae_pareto \
#     run_name=cap_t134 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_reference_normal \
#     algorithm.delta=3.0 \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.nodes='[32,128,256]' \
#     algorithm.encoder.strides='[2,2]' \
#     algorithm.input_noise_std=0.01 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0022412911495235926 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=1.0 \
#     trainer=gpu \
#     trainer.devices=[3]

# ------------------------------------------------------------------------
# trial 180: cap=-0.17448, mse=0.1902
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     experiment=cifar10/ae_agnostic \
#     experiment_name=cifar10_ae_pareto \
#     run_name=cap_t180 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_reference_normal \
#     algorithm.delta=2.0 \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.nodes='[32,64,128]' \
#     algorithm.encoder.strides='[2,1]' \
#     algorithm.input_noise_std=0.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0016477755069124263 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=1.0 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 192: cap=-0.18436, mse=0.12213
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     experiment=cifar10/ae_agnostic \
#     experiment_name=cifar10_ae_pareto \
#     run_name=cap_t192 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_reference_normal \
#     algorithm.delta=1.0 \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.nodes='[32,128,256]' \
#     algorithm.encoder.strides='[2,1]' \
#     algorithm.input_noise_std=0.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0007131810743406769 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=1.0 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 195: cap=-0.17982, mse=0.12844
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     experiment=cifar10/ae_agnostic \
#     experiment_name=cifar10_ae_pareto \
#     run_name=cap_t195 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_reference_normal \
#     algorithm.delta=1.0 \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.nodes='[32,128,256]' \
#     algorithm.encoder.strides='[2,1]' \
#     algorithm.input_noise_std=0.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0007169851243202001 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=1.0 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 200: cap=-0.18027, mse=0.12593
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     experiment=cifar10/ae_agnostic \
#     experiment_name=cifar10_ae_pareto \
#     run_name=cap_t200 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_reference_normal \
#     algorithm.delta=1.0 \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.nodes='[32,128,256]' \
#     algorithm.encoder.strides='[2,1]' \
#     algorithm.input_noise_std=0.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0006989952553906938 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=1.0 \
#     trainer=gpu \
#     trainer.devices=[3]

# ------------------------------------------------------------------------
# trial 201: cap=-0.17993, mse=0.1276
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     experiment=cifar10/ae_agnostic \
#     experiment_name=cifar10_ae_pareto \
#     run_name=cap_t201 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_reference_normal \
#     algorithm.delta=1.0 \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.nodes='[32,128,256]' \
#     algorithm.encoder.strides='[2,1]' \
#     algorithm.input_noise_std=0.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.000700367091173789 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=1.0 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 211: cap=-0.16751, mse=0.23101  << ORIGINAL PICK | BEST cap
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     experiment=cifar10/ae_agnostic \
#     experiment_name=cifar10_ae_pareto \
#     run_name=cap_t211 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_reference_normal \
#     algorithm.delta=3.0 \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.nodes='[32,64,128]' \
#     algorithm.encoder.strides='[2,1]' \
#     algorithm.input_noise_std=0.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0028555698070213114 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=1.0 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 212: cap=-0.17128, mse=0.23056
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     experiment=cifar10/ae_agnostic \
#     experiment_name=cifar10_ae_pareto \
#     run_name=cap_t212 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_reference_normal \
#     algorithm.delta=3.0 \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.nodes='[32,64,128]' \
#     algorithm.encoder.strides='[2,1]' \
#     algorithm.input_noise_std=0.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0028626872937395085 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=1.0 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 221: cap=-0.173, mse=0.1967
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     experiment=cifar10/ae_agnostic \
#     experiment_name=cifar10_ae_pareto \
#     run_name=cap_t221 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_reference_normal \
#     algorithm.delta=3.0 \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.nodes='[32,64,128]' \
#     algorithm.encoder.strides='[2,1]' \
#     algorithm.input_noise_std=0.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0021132742220368924 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=1.0 \
#     trainer=gpu \
#     trainer.devices=[3]

# ------------------------------------------------------------------------
# trial 275: cap=-0.17197, mse=0.22019
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     experiment=cifar10/ae_agnostic \
#     experiment_name=cifar10_ae_pareto \
#     run_name=cap_t275 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_reference_normal \
#     algorithm.delta=3.0 \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.nodes='[32,64,128]' \
#     algorithm.encoder.strides='[2,1]' \
#     algorithm.input_noise_std=0.01 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0025340191491567687 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=1.0 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 301: cap=-0.17134, mse=0.22724
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     experiment=cifar10/ae_agnostic \
#     experiment_name=cifar10_ae_pareto \
#     run_name=cap_t301 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_reference_normal \
#     algorithm.delta=3.0 \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.nodes='[32,64,128]' \
#     algorithm.encoder.strides='[2,1]' \
#     algorithm.input_noise_std=0.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.002837117184422952 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=2.0 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 318: cap=-0.18602, mse=0.11979
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     experiment=cifar10/ae_agnostic \
#     experiment_name=cifar10_ae_pareto \
#     run_name=cap_t318 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_reference_normal \
#     algorithm.delta=3.0 \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.nodes='[32,128,256]' \
#     algorithm.encoder.strides='[2,2]' \
#     algorithm.input_noise_std=0.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.002200383859458851 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=1.0 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 323: cap=-0.18607, mse=0.11946
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     experiment=cifar10/ae_agnostic \
#     experiment_name=cifar10_ae_pareto \
#     run_name=cap_t323 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_reference_normal \
#     algorithm.delta=3.0 \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.nodes='[32,128,256]' \
#     algorithm.encoder.strides='[2,2]' \
#     algorithm.input_noise_std=0.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.002196495069081466 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=1.0 \
#     trainer=gpu \
#     trainer.devices=[3]

# ------------------------------------------------------------------------
# trial 340: cap=-0.1706, mse=0.23076
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     experiment=cifar10/ae_agnostic \
#     experiment_name=cifar10_ae_pareto \
#     run_name=cap_t340 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_reference_normal \
#     algorithm.delta=3.0 \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.nodes='[32,64,128]' \
#     algorithm.encoder.strides='[2,1]' \
#     algorithm.input_noise_std=0.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0027932693647456557 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=1.0 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 353: cap=-0.17575, mse=0.18455
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     experiment=cifar10/ae_agnostic \
#     experiment_name=cifar10_ae_pareto \
#     run_name=cap_t353 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_reference_normal \
#     algorithm.delta=3.0 \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.nodes='[32,64,128]' \
#     algorithm.encoder.strides='[2,1]' \
#     algorithm.input_noise_std=0.01 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0007108359965127607 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=1.0 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 373: cap=-0.17653, mse=0.18262
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     experiment=cifar10/ae_agnostic \
#     experiment_name=cifar10_ae_pareto \
#     run_name=cap_t373 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_reference_normal \
#     algorithm.delta=3.0 \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.nodes='[32,64,128]' \
#     algorithm.encoder.strides='[2,1]' \
#     algorithm.input_noise_std=0.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0006836196255872358 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=1.0 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 380: cap=-0.17653, mse=0.18374
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     experiment=cifar10/ae_agnostic \
#     experiment_name=cifar10_ae_pareto \
#     run_name=cap_t380 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_reference_normal \
#     algorithm.delta=3.0 \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.nodes='[32,64,128]' \
#     algorithm.encoder.strides='[2,1]' \
#     algorithm.input_noise_std=0.01 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0007449157315773993 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=1.0 \
#     trainer=gpu \
#     trainer.devices=[3]

# ------------------------------------------------------------------------
# trial 414: cap=-0.18175, mse=0.12338
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     experiment=cifar10/ae_agnostic \
#     experiment_name=cifar10_ae_pareto \
#     run_name=cap_t414 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_reference_normal \
#     algorithm.delta=1.0 \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.nodes='[32,64,256]' \
#     algorithm.encoder.strides='[2,1]' \
#     algorithm.input_noise_std=0.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0006897358745259046 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=1.0 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 415: cap=-0.18114, mse=0.12577
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     experiment=cifar10/ae_agnostic \
#     experiment_name=cifar10_ae_pareto \
#     run_name=cap_t415 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_reference_normal \
#     algorithm.delta=1.0 \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.nodes='[32,64,256]' \
#     algorithm.encoder.strides='[2,1]' \
#     algorithm.input_noise_std=0.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0006887159202542141 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=1.0 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 419: cap=-0.18298, mse=0.12264
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     experiment=cifar10/ae_agnostic \
#     experiment_name=cifar10_ae_pareto \
#     run_name=cap_t419 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_reference_normal \
#     algorithm.delta=1.0 \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.nodes='[32,64,256]' \
#     algorithm.encoder.strides='[2,1]' \
#     algorithm.input_noise_std=0.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.000692349490182475 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=1.0 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 431: cap=-0.17655, mse=0.15028
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     experiment=cifar10/ae_agnostic \
#     experiment_name=cifar10_ae_pareto \
#     run_name=cap_t431 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_reference_normal \
#     algorithm.delta=3.0 \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.nodes='[32,64,256]' \
#     algorithm.encoder.strides='[2,1]' \
#     algorithm.input_noise_std=0.01 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.002224141903115755 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=1.0 \
#     trainer=gpu \
#     trainer.devices=[3]

# ------------------------------------------------------------------------
# trial 474: cap=-0.17677, mse=0.1406  << KNEE
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     experiment=cifar10/ae_agnostic \
#     experiment_name=cifar10_ae_pareto \
#     run_name=cap_t474 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_reference_normal \
#     algorithm.delta=3.0 \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.nodes='[32,128,256]' \
#     algorithm.encoder.strides='[2,1]' \
#     algorithm.input_noise_std=0.01 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.002328917310815944 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=1.0 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 520: cap=-0.17563, mse=0.1846
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     experiment=cifar10/ae_agnostic \
#     experiment_name=cifar10_ae_pareto \
#     run_name=cap_t520 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_reference_normal \
#     algorithm.delta=3.0 \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.nodes='[32,64,128]' \
#     algorithm.encoder.strides='[2,2]' \
#     algorithm.input_noise_std=0.01 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.001829618421928333 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=1.0 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 522: cap=-0.18555, mse=0.12137
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     experiment=cifar10/ae_agnostic \
#     experiment_name=cifar10_ae_pareto \
#     run_name=cap_t522 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_reference_normal \
#     algorithm.delta=3.0 \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.nodes='[32,128,256]' \
#     algorithm.encoder.strides='[2,2]' \
#     algorithm.input_noise_std=0.1 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0020257207570705824 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=1.0 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 523: cap=-0.18722, mse=0.11835
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     experiment=cifar10/ae_agnostic \
#     experiment_name=cifar10_ae_pareto \
#     run_name=cap_t523 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_reference_normal \
#     algorithm.delta=3.0 \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.nodes='[32,128,256]' \
#     algorithm.encoder.strides='[2,2]' \
#     algorithm.input_noise_std=0.1 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0020365625038220496 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=1.0 \
#     trainer=gpu \
#     trainer.devices=[3]

# ========================================================================
# CONSISTENCY TRAINING  (study: consistency_vs_mse, 13 Pareto points, trimmed to 11 around the knee (endpoints kept))
# ========================================================================
# ------------------------------------------------------------------------
# trial 5: consistency=-0.0084731, mse=0.11373
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     experiment=cifar10/ae_agnostic \
#     experiment_name=cifar10_ae_pareto \
#     run_name=consistency_t5 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_reference_normal \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_reference_normal \
#     algorithm.delta=3.0 \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.nodes='[32,64,256]' \
#     algorithm.encoder.strides='[1,2]' \
#     algorithm.input_noise_std=0.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0003062938053107561 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 237: consistency=-0.007153, mse=0.11467
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     experiment=cifar10/ae_agnostic \
#     experiment_name=cifar10_ae_pareto \
#     run_name=consistency_t237 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_reference_normal \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_reference_normal \
#     algorithm.delta=2.0 \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.nodes='[32,64,256]' \
#     algorithm.encoder.strides='[1,2]' \
#     algorithm.input_noise_std=0.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.00029266935134324005 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 258: consistency=-0.0018492, mse=0.13877
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     experiment=cifar10/ae_agnostic \
#     experiment_name=cifar10_ae_pareto \
#     run_name=consistency_t258 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_reference_normal \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_reference_normal \
#     algorithm.delta=2.0 \
#     algorithm.encoder.activation=silu \
#     algorithm.encoder.nodes='[32,128,256]' \
#     algorithm.encoder.strides='[2,1]' \
#     algorithm.input_noise_std=0.03 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0007410573425966438 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=1.0 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 261: consistency=-0.0021705, mse=0.12569
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     experiment=cifar10/ae_agnostic \
#     experiment_name=cifar10_ae_pareto \
#     run_name=consistency_t261 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_reference_normal \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_reference_normal \
#     algorithm.delta=2.0 \
#     algorithm.encoder.activation=silu \
#     algorithm.encoder.nodes='[32,128,256]' \
#     algorithm.encoder.strides='[2,1]' \
#     algorithm.input_noise_std=0.03 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.000739824681057596 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=1.0 \
#     trainer=gpu \
#     trainer.devices=[3]

# ------------------------------------------------------------------------
# trial 298: consistency=-0.0020484, mse=0.13501
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     experiment=cifar10/ae_agnostic \
#     experiment_name=cifar10_ae_pareto \
#     run_name=consistency_t298 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_reference_normal \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_reference_normal \
#     algorithm.delta=2.0 \
#     algorithm.encoder.activation=silu \
#     algorithm.encoder.nodes='[32,128,256]' \
#     algorithm.encoder.strides='[2,1]' \
#     algorithm.input_noise_std=0.03 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0007448051779459509 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=1.0 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 326: consistency=-0.0028867, mse=0.11696  << KNEE
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     experiment=cifar10/ae_agnostic \
#     experiment_name=cifar10_ae_pareto \
#     run_name=consistency_t326 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_reference_normal \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_reference_normal \
#     algorithm.delta=2.0 \
#     algorithm.encoder.activation=silu \
#     algorithm.encoder.nodes='[32,128,256]' \
#     algorithm.encoder.strides='[2,1]' \
#     algorithm.input_noise_std=0.05 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.00020971992821224706 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=1.0 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 386: consistency=-0.0013384, mse=0.1941  << BEST consistency
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     experiment=cifar10/ae_agnostic \
#     experiment_name=cifar10_ae_pareto \
#     run_name=consistency_t386 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_reference_normal \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_reference_normal \
#     algorithm.delta=0.5 \
#     algorithm.encoder.activation=silu \
#     algorithm.encoder.nodes='[64,128,256]' \
#     algorithm.encoder.strides='[2,1]' \
#     algorithm.input_noise_std=0.05 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.000723550717961987 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=1.0 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 474: consistency=-0.0020165, mse=0.13755
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     experiment=cifar10/ae_agnostic \
#     experiment_name=cifar10_ae_pareto \
#     run_name=consistency_t474 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_reference_normal \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_reference_normal \
#     algorithm.delta=0.5 \
#     algorithm.encoder.activation=silu \
#     algorithm.encoder.nodes='[64,128,256]' \
#     algorithm.encoder.strides='[2,2]' \
#     algorithm.input_noise_std=0.05 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0007258047241773781 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[3]

# ------------------------------------------------------------------------
# trial 483: consistency=-0.0021608, mse=0.13008
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     experiment=cifar10/ae_agnostic \
#     experiment_name=cifar10_ae_pareto \
#     run_name=consistency_t483 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_reference_normal \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_reference_normal \
#     algorithm.delta=0.5 \
#     algorithm.encoder.activation=silu \
#     algorithm.encoder.nodes='[64,128,256]' \
#     algorithm.encoder.strides='[2,2]' \
#     algorithm.input_noise_std=0.05 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.00029373589433283516 \
#     algorithm.optimizer.weight_decay=0.001 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 544: consistency=-0.0065872, mse=0.11566
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     experiment=cifar10/ae_agnostic \
#     experiment_name=cifar10_ae_pareto \
#     run_name=consistency_t544 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_reference_normal \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_reference_normal \
#     algorithm.delta=0.5 \
#     algorithm.encoder.activation=silu \
#     algorithm.encoder.nodes='[64,128,256]' \
#     algorithm.encoder.strides='[2,1]' \
#     algorithm.input_noise_std=0.0 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0006949966131986122 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 545: consistency=-0.0084973, mse=0.11056
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     experiment=cifar10/ae_agnostic \
#     experiment_name=cifar10_ae_pareto \
#     run_name=consistency_t545 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_reference_normal \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_reference_normal \
#     algorithm.delta=0.5 \
#     algorithm.encoder.activation=silu \
#     algorithm.encoder.nodes='[64,128,256]' \
#     algorithm.encoder.strides='[2,1]' \
#     algorithm.input_noise_std=0.0 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0006935141556533645 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[2]

# ========================================================================
# STABILITY TRAINING  (study: drift_vs_mse, 2 Pareto points)
# ========================================================================
# ------------------------------------------------------------------------
# trial 241: drift=0.15415, mse=0.10821  << ORIGINAL PICK | BEST drift
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     experiment=cifar10/ae_agnostic \
#     experiment_name=cifar10_ae_pareto \
#     run_name=stability_t241 \
#     callbacks.wasserstein_dist=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_reference_normal \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_reference_normal \
#     algorithm.delta=1.0 \
#     algorithm.encoder.activation=silu \
#     algorithm.encoder.nodes='[64,128,256]' \
#     algorithm.encoder.strides='[2,2]' \
#     algorithm.input_noise_std=0.05 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0008065877157877547 \
#     algorithm.optimizer.weight_decay=0.0005 \
#     trainer.gradient_clip_val=1.0 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 256: drift=0.40547, mse=0.10781
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     experiment=cifar10/ae_agnostic \
#     experiment_name=cifar10_ae_pareto \
#     run_name=stability_t256 \
#     callbacks.wasserstein_dist=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_reference_normal \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_reference_normal \
#     algorithm.delta=1.0 \
#     algorithm.encoder.activation=silu \
#     algorithm.encoder.nodes='[64,128,256]' \
#     algorithm.encoder.strides='[2,2]' \
#     algorithm.input_noise_std=0.05 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0008131909232762738 \
#     algorithm.optimizer.weight_decay=0.0005 \
#     trainer.gradient_clip_val=1.0 \
#     trainer=gpu \
#     trainer.devices=[1]

# ========================================================================
# WASSERSTEIN TRAINING  (study: wasserstein_vs_mse, 10 Pareto points)
# ========================================================================
# ------------------------------------------------------------------------
# trial 223: wasserstein=0.0020245, mse=0.10812
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     experiment=cifar10/ae_agnostic \
#     experiment_name=cifar10_ae_pareto \
#     run_name=wasserstein_t223 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_reference_normal \
#     algorithm.delta=5.0 \
#     algorithm.encoder.activation=silu \
#     algorithm.encoder.nodes='[64,128,256]' \
#     algorithm.encoder.strides='[2,2]' \
#     algorithm.input_noise_std=0.03 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0022916723724932544 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 243: wasserstein=0.0020438, mse=0.10646  << KNEE
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     experiment=cifar10/ae_agnostic \
#     experiment_name=cifar10_ae_pareto \
#     run_name=wasserstein_t243 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_reference_normal \
#     algorithm.delta=5.0 \
#     algorithm.encoder.activation=silu \
#     algorithm.encoder.nodes='[64,128,256]' \
#     algorithm.encoder.strides='[2,2]' \
#     algorithm.input_noise_std=0.03 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0022847682391511012 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 254: wasserstein=0.0021622, mse=0.10599
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     experiment=cifar10/ae_agnostic \
#     experiment_name=cifar10_ae_pareto \
#     run_name=wasserstein_t254 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_reference_normal \
#     algorithm.delta=5.0 \
#     algorithm.encoder.activation=silu \
#     algorithm.encoder.nodes='[64,128,256]' \
#     algorithm.encoder.strides='[2,2]' \
#     algorithm.input_noise_std=0.03 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0027624093037785066 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 279: wasserstein=0.0022523, mse=0.1051  << ORIGINAL PICK
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     experiment=cifar10/ae_agnostic \
#     experiment_name=cifar10_ae_pareto \
#     run_name=wasserstein_t279 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_reference_normal \
#     algorithm.delta=5.0 \
#     algorithm.encoder.activation=silu \
#     algorithm.encoder.nodes='[64,128,256]' \
#     algorithm.encoder.strides='[2,2]' \
#     algorithm.input_noise_std=0.03 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.002250553692978696 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[3]

# ------------------------------------------------------------------------
# trial 293: wasserstein=0.0021169, mse=0.10604
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     experiment=cifar10/ae_agnostic \
#     experiment_name=cifar10_ae_pareto \
#     run_name=wasserstein_t293 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_reference_normal \
#     algorithm.delta=5.0 \
#     algorithm.encoder.activation=silu \
#     algorithm.encoder.nodes='[64,128,256]' \
#     algorithm.encoder.strides='[2,2]' \
#     algorithm.input_noise_std=0.03 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0022801418555526195 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 433: wasserstein=0.0019648, mse=0.11087
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     experiment=cifar10/ae_agnostic \
#     experiment_name=cifar10_ae_pareto \
#     run_name=wasserstein_t433 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_reference_normal \
#     algorithm.delta=5.0 \
#     algorithm.encoder.activation=silu \
#     algorithm.encoder.nodes='[64,128,256]' \
#     algorithm.encoder.strides='[2,2]' \
#     algorithm.input_noise_std=0.03 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0005916521452647295 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 435: wasserstein=0.0018893, mse=0.112
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     experiment=cifar10/ae_agnostic \
#     experiment_name=cifar10_ae_pareto \
#     run_name=wasserstein_t435 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_reference_normal \
#     algorithm.delta=5.0 \
#     algorithm.encoder.activation=silu \
#     algorithm.encoder.nodes='[64,128,256]' \
#     algorithm.encoder.strides='[2,2]' \
#     algorithm.input_noise_std=0.03 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0005876061782550472 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 556: wasserstein=0.0019194, mse=0.11104
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     experiment=cifar10/ae_agnostic \
#     experiment_name=cifar10_ae_pareto \
#     run_name=wasserstein_t556 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_reference_normal \
#     algorithm.delta=5.0 \
#     algorithm.encoder.activation=silu \
#     algorithm.encoder.nodes='[64,128,256]' \
#     algorithm.encoder.strides='[2,2]' \
#     algorithm.input_noise_std=0.03 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0005905728159921275 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[3]

# ------------------------------------------------------------------------
# trial 568: wasserstein=0.0018183, mse=0.11679  << BEST wasserstein
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     experiment=cifar10/ae_agnostic \
#     experiment_name=cifar10_ae_pareto \
#     run_name=wasserstein_t568 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_reference_normal \
#     algorithm.delta=5.0 \
#     algorithm.encoder.activation=silu \
#     algorithm.encoder.nodes='[64,128,256]' \
#     algorithm.encoder.strides='[2,2]' \
#     algorithm.input_noise_std=0.03 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.002209650437272835 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 569: wasserstein=0.0018415, mse=0.11491
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     experiment=cifar10/ae_agnostic \
#     experiment_name=cifar10_ae_pareto \
#     run_name=wasserstein_t569 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_reference_normal \
#     algorithm.delta=5.0 \
#     algorithm.encoder.activation=silu \
#     algorithm.encoder.nodes='[64,128,256]' \
#     algorithm.encoder.strides='[2,2]' \
#     algorithm.input_noise_std=0.03 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.002208760145006456 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[1]

# ========================================================================
# SUBMIT EVERYTHING ABOVE TO CLARIDEN  (one slurm job per command)
# ========================================================================
# Set paths.raw_data_dir to the data location on clariden; any extra
# hydra overrides appended here are added to every job.
# bash scripts/submit_pareto.sh scripts/cifar10/runae_pareto.sh \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files
