# ========================================================================
# VAE PARETO-FRONT TRAINING COMMANDS
# ========================================================================
# These are the training commands for every point on the Pareto front of
# each validation strategy. Generated by scripts/make_pareto_scripts.py from
# notebooks/paretos/cifar10/ -- regenerate rather than edit by hand.
#
# Run from the repository root. All commands are commented out -- uncomment
# the points you want to run locally (taskset pinning, GPUs cycling 0-3).
# To run the WHOLE file on clariden instead, use the single submit command
# at the bottom: it sends every point above to slurm, one job each, via
# scripts/submit_pareto.sh (submitit launcher).

# ========================================================================
# CVAR25 TRAINING  (study: cvar25eff_vs_kl, 10 Pareto points)
# ========================================================================
# ------------------------------------------------------------------------
# trial 79: cvar25eff=3.2667, kl=3.4344
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     experiment=cifar10/vae \
#     experiment_name=cifar10_vae_pareto \
#     run_name=cvar25_t79 \
#     algorithm.encoder.activation=silu \
#     algorithm.encoder.batchnorm=True \
#     algorithm.encoder.clamp_zlogvar_range='[-20,10]' \
#     algorithm.encoder.nodes='[24,48,96,32]' \
#     algorithm.encoder.strides='[2,2]' \
#     algorithm.kl_scale=0.001 \
#     algorithm.kl_warmup_frac=0.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=5.2661564806918774e-05 \
#     algorithm.optimizer.weight_decay=0.001 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 119: cvar25eff=11.2, kl=39.528
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     experiment=cifar10/vae \
#     experiment_name=cifar10_vae_pareto \
#     run_name=cvar25_t119 \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.batchnorm=False \
#     algorithm.encoder.clamp_zlogvar_range='[-6,4]' \
#     algorithm.encoder.nodes='[16,32,64,16]' \
#     algorithm.encoder.strides='[2,2]' \
#     algorithm.kl_scale=0.002 \
#     algorithm.kl_warmup_frac=0.0 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0009880962194267783 \
#     algorithm.optimizer.weight_decay=0.001 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 248: cvar25eff=10, kl=39.233
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     experiment=cifar10/vae \
#     experiment_name=cifar10_vae_pareto \
#     run_name=cvar25_t248 \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.batchnorm=False \
#     algorithm.encoder.clamp_zlogvar_range='[-6,4]' \
#     algorithm.encoder.nodes='[16,32,64,16]' \
#     algorithm.encoder.strides='[2,2]' \
#     algorithm.kl_scale=0.002 \
#     algorithm.kl_warmup_frac=0.0 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0009999198102642005 \
#     algorithm.optimizer.weight_decay=0.001 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 250: cvar25eff=10.8, kl=39.493
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     experiment=cifar10/vae \
#     experiment_name=cifar10_vae_pareto \
#     run_name=cvar25_t250 \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.batchnorm=False \
#     algorithm.encoder.clamp_zlogvar_range='[-6,4]' \
#     algorithm.encoder.nodes='[16,32,64,16]' \
#     algorithm.encoder.strides='[2,2]' \
#     algorithm.kl_scale=0.002 \
#     algorithm.kl_warmup_frac=0.0 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0009993665719803067 \
#     algorithm.optimizer.weight_decay=0.001 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[3]

# ------------------------------------------------------------------------
# trial 251: cvar25eff=10.267, kl=39.255
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     experiment=cifar10/vae \
#     experiment_name=cifar10_vae_pareto \
#     run_name=cvar25_t251 \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.batchnorm=False \
#     algorithm.encoder.clamp_zlogvar_range='[-6,4]' \
#     algorithm.encoder.nodes='[16,32,64,16]' \
#     algorithm.encoder.strides='[2,2]' \
#     algorithm.kl_scale=0.002 \
#     algorithm.kl_warmup_frac=0.0 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0009995476842574672 \
#     algorithm.optimizer.weight_decay=0.001 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 411: cvar25eff=0.6, kl=1.4436
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     experiment=cifar10/vae \
#     experiment_name=cifar10_vae_pareto \
#     run_name=cvar25_t411 \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.batchnorm=True \
#     algorithm.encoder.clamp_zlogvar_range='[-6,4]' \
#     algorithm.encoder.nodes='[16,32,64,16]' \
#     algorithm.encoder.strides='[2,2]' \
#     algorithm.kl_scale=0.002 \
#     algorithm.kl_warmup_frac=0.0 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=5.231029667505769e-05 \
#     algorithm.optimizer.weight_decay=0.001 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 488: cvar25eff=14.267, kl=68.708  << KNEE
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     experiment=cifar10/vae \
#     experiment_name=cifar10_vae_pareto \
#     run_name=cvar25_t488 \
#     algorithm.encoder.activation=silu \
#     algorithm.encoder.batchnorm=False \
#     algorithm.encoder.clamp_zlogvar_range='[-20,10]' \
#     algorithm.encoder.nodes='[48,96,192,64]' \
#     algorithm.encoder.strides='[2,1]' \
#     algorithm.kl_scale=0.002 \
#     algorithm.kl_warmup_frac=0.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.000955143883162113 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 566: cvar25eff=17.6, kl=69.465
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     experiment=cifar10/vae \
#     experiment_name=cifar10_vae_pareto \
#     run_name=cvar25_t566 \
#     algorithm.encoder.activation=silu \
#     algorithm.encoder.batchnorm=False \
#     algorithm.encoder.clamp_zlogvar_range='[-6,4]' \
#     algorithm.encoder.nodes='[48,96,192,64]' \
#     algorithm.encoder.strides='[2,1]' \
#     algorithm.kl_scale=0.002 \
#     algorithm.kl_warmup_frac=0.0 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.000956771805807344 \
#     algorithm.optimizer.weight_decay=0.001 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[3]

# ------------------------------------------------------------------------
# trial 568: cvar25eff=17.933, kl=69.66  << ORIGINAL PICK | BEST cvar25eff
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     experiment=cifar10/vae \
#     experiment_name=cifar10_vae_pareto \
#     run_name=cvar25_t568 \
#     algorithm.encoder.activation=silu \
#     algorithm.encoder.batchnorm=False \
#     algorithm.encoder.clamp_zlogvar_range='[-6,4]' \
#     algorithm.encoder.nodes='[48,96,192,64]' \
#     algorithm.encoder.strides='[2,1]' \
#     algorithm.kl_scale=0.002 \
#     algorithm.kl_warmup_frac=0.0 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0009568361127419486 \
#     algorithm.optimizer.weight_decay=0.001 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 588: cvar25eff=13.533, kl=56.457
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     experiment=cifar10/vae \
#     experiment_name=cifar10_vae_pareto \
#     run_name=cvar25_t588 \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.batchnorm=False \
#     algorithm.encoder.clamp_zlogvar_range='[-6,4]' \
#     algorithm.encoder.nodes='[32,64,128,32]' \
#     algorithm.encoder.strides='[2,1]' \
#     algorithm.kl_scale=0.002 \
#     algorithm.kl_warmup_frac=0.0 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0009628424048802279 \
#     algorithm.optimizer.weight_decay=0.001 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[1]

# ========================================================================
# CAP TRAINING  (study: cap_vs_kl, 25 Pareto points)
# ========================================================================
# ------------------------------------------------------------------------
# trial 102: cap=-0.15737, kl=66.591
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     experiment=cifar10/vae_agnostic \
#     experiment_name=cifar10_vae_pareto \
#     run_name=cap_t102 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_reference_normal \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.batchnorm=True \
#     algorithm.encoder.clamp_zlogvar_range='[-6,4]' \
#     algorithm.encoder.nodes='[16,32,64,16]' \
#     algorithm.encoder.strides='[2,2]' \
#     algorithm.kl_scale=0.0003 \
#     algorithm.kl_warmup_frac=0.2 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.00012628588538425928 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=2.0 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 150: cap=-0.15736, kl=67.047
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     experiment=cifar10/vae_agnostic \
#     experiment_name=cifar10_vae_pareto \
#     run_name=cap_t150 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_reference_normal \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.batchnorm=True \
#     algorithm.encoder.clamp_zlogvar_range='[-6,4]' \
#     algorithm.encoder.nodes='[16,32,64,16]' \
#     algorithm.encoder.strides='[2,2]' \
#     algorithm.kl_scale=0.0003 \
#     algorithm.kl_warmup_frac=0.2 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.00019005006128682548 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=2.0 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 177: cap=-0.16372, kl=39.406
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     experiment=cifar10/vae_agnostic \
#     experiment_name=cifar10_vae_pareto \
#     run_name=cap_t177 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_reference_normal \
#     algorithm.encoder.activation=silu \
#     algorithm.encoder.batchnorm=False \
#     algorithm.encoder.clamp_zlogvar_range='[-20,10]' \
#     algorithm.encoder.nodes='[16,32,64,16]' \
#     algorithm.encoder.strides='[1,2]' \
#     algorithm.kl_scale=0.002 \
#     algorithm.kl_warmup_frac=0.2 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0004174969164327221 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=1.0 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 180: cap=-0.16516, kl=38.875
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     experiment=cifar10/vae_agnostic \
#     experiment_name=cifar10_vae_pareto \
#     run_name=cap_t180 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_reference_normal \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.batchnorm=False \
#     algorithm.encoder.clamp_zlogvar_range='[-20,10]' \
#     algorithm.encoder.nodes='[16,32,64,16]' \
#     algorithm.encoder.strides='[1,2]' \
#     algorithm.kl_scale=0.002 \
#     algorithm.kl_warmup_frac=0.05 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.00015508292398618177 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[3]

# ------------------------------------------------------------------------
# trial 181: cap=-0.16511, kl=38.882
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     experiment=cifar10/vae_agnostic \
#     experiment_name=cifar10_vae_pareto \
#     run_name=cap_t181 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_reference_normal \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.batchnorm=False \
#     algorithm.encoder.clamp_zlogvar_range='[-20,10]' \
#     algorithm.encoder.nodes='[16,32,64,16]' \
#     algorithm.encoder.strides='[1,2]' \
#     algorithm.kl_scale=0.002 \
#     algorithm.kl_warmup_frac=0.05 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.00015460253627694204 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 182: cap=-0.16515, kl=38.877
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     experiment=cifar10/vae_agnostic \
#     experiment_name=cifar10_vae_pareto \
#     run_name=cap_t182 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_reference_normal \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.batchnorm=False \
#     algorithm.encoder.clamp_zlogvar_range='[-20,10]' \
#     algorithm.encoder.nodes='[16,32,64,16]' \
#     algorithm.encoder.strides='[1,2]' \
#     algorithm.kl_scale=0.002 \
#     algorithm.kl_warmup_frac=0.05 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0001549239360440079 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 183: cap=-0.16525, kl=38.863
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     experiment=cifar10/vae_agnostic \
#     experiment_name=cifar10_vae_pareto \
#     run_name=cap_t183 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_reference_normal \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.batchnorm=False \
#     algorithm.encoder.clamp_zlogvar_range='[-20,10]' \
#     algorithm.encoder.nodes='[16,32,64,16]' \
#     algorithm.encoder.strides='[1,2]' \
#     algorithm.kl_scale=0.002 \
#     algorithm.kl_warmup_frac=0.05 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.00015618156033405257 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 184: cap=-0.16507, kl=38.886
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     experiment=cifar10/vae_agnostic \
#     experiment_name=cifar10_vae_pareto \
#     run_name=cap_t184 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_reference_normal \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.batchnorm=False \
#     algorithm.encoder.clamp_zlogvar_range='[-20,10]' \
#     algorithm.encoder.nodes='[16,32,64,16]' \
#     algorithm.encoder.strides='[1,2]' \
#     algorithm.kl_scale=0.002 \
#     algorithm.kl_warmup_frac=0.05 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.00015403485178052523 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[3]

# ------------------------------------------------------------------------
# trial 185: cap=-0.16504, kl=38.89
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     experiment=cifar10/vae_agnostic \
#     experiment_name=cifar10_vae_pareto \
#     run_name=cap_t185 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_reference_normal \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.batchnorm=False \
#     algorithm.encoder.clamp_zlogvar_range='[-20,10]' \
#     algorithm.encoder.nodes='[16,32,64,16]' \
#     algorithm.encoder.strides='[1,2]' \
#     algorithm.kl_scale=0.002 \
#     algorithm.kl_warmup_frac=0.05 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.00015368966592730607 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 200: cap=-0.16624, kl=38.439
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     experiment=cifar10/vae_agnostic \
#     experiment_name=cifar10_vae_pareto \
#     run_name=cap_t200 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_reference_normal \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.batchnorm=False \
#     algorithm.encoder.clamp_zlogvar_range='[-20,10]' \
#     algorithm.encoder.nodes='[16,32,64,16]' \
#     algorithm.encoder.strides='[1,2]' \
#     algorithm.kl_scale=0.002 \
#     algorithm.kl_warmup_frac=0.2 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0002100684929837176 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=2.0 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 201: cap=-0.1662, kl=38.443
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     experiment=cifar10/vae_agnostic \
#     experiment_name=cifar10_vae_pareto \
#     run_name=cap_t201 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_reference_normal \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.batchnorm=False \
#     algorithm.encoder.clamp_zlogvar_range='[-20,10]' \
#     algorithm.encoder.nodes='[16,32,64,16]' \
#     algorithm.encoder.strides='[1,2]' \
#     algorithm.kl_scale=0.002 \
#     algorithm.kl_warmup_frac=0.2 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.00020926561927027716 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=2.0 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 202: cap=-0.16623, kl=38.441
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     experiment=cifar10/vae_agnostic \
#     experiment_name=cifar10_vae_pareto \
#     run_name=cap_t202 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_reference_normal \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.batchnorm=False \
#     algorithm.encoder.clamp_zlogvar_range='[-20,10]' \
#     algorithm.encoder.nodes='[16,32,64,16]' \
#     algorithm.encoder.strides='[1,2]' \
#     algorithm.kl_scale=0.002 \
#     algorithm.kl_warmup_frac=0.2 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.00020970368501311778 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=2.0 \
#     trainer=gpu \
#     trainer.devices=[3]

# ------------------------------------------------------------------------
# trial 354: cap=-0.15958, kl=49.268
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     experiment=cifar10/vae_agnostic \
#     experiment_name=cifar10_vae_pareto \
#     run_name=cap_t354 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_reference_normal \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.batchnorm=False \
#     algorithm.encoder.clamp_zlogvar_range='[-6,4]' \
#     algorithm.encoder.nodes='[16,32,64,16]' \
#     algorithm.encoder.strides='[2,2]' \
#     algorithm.kl_scale=0.002 \
#     algorithm.kl_warmup_frac=0.05 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.00010708930539120865 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 356: cap=-0.15946, kl=49.327  << KNEE
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     experiment=cifar10/vae_agnostic \
#     experiment_name=cifar10_vae_pareto \
#     run_name=cap_t356 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_reference_normal \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.batchnorm=False \
#     algorithm.encoder.clamp_zlogvar_range='[-6,4]' \
#     algorithm.encoder.nodes='[16,32,64,16]' \
#     algorithm.encoder.strides='[2,2]' \
#     algorithm.kl_scale=0.002 \
#     algorithm.kl_warmup_frac=0.05 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.00010679259482433302 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 358: cap=-0.15949, kl=49.304
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     experiment=cifar10/vae_agnostic \
#     experiment_name=cifar10_vae_pareto \
#     run_name=cap_t358 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_reference_normal \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.batchnorm=False \
#     algorithm.encoder.clamp_zlogvar_range='[-6,4]' \
#     algorithm.encoder.nodes='[16,32,64,16]' \
#     algorithm.encoder.strides='[2,2]' \
#     algorithm.kl_scale=0.002 \
#     algorithm.kl_warmup_frac=0.05 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.00010683611860643533 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 365: cap=-0.14872, kl=122.63
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     experiment=cifar10/vae_agnostic \
#     experiment_name=cifar10_vae_pareto \
#     run_name=cap_t365 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_reference_normal \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.batchnorm=False \
#     algorithm.encoder.clamp_zlogvar_range='[-6,4]' \
#     algorithm.encoder.nodes='[24,48,96,32]' \
#     algorithm.encoder.strides='[1,2]' \
#     algorithm.kl_scale=0.0003 \
#     algorithm.kl_warmup_frac=0.05 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.00010486028940107213 \
#     algorithm.optimizer.weight_decay=0.001 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[3]

# ------------------------------------------------------------------------
# trial 372: cap=-0.14848, kl=123.47
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     experiment=cifar10/vae_agnostic \
#     experiment_name=cifar10_vae_pareto \
#     run_name=cap_t372 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_reference_normal \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.batchnorm=False \
#     algorithm.encoder.clamp_zlogvar_range='[-6,4]' \
#     algorithm.encoder.nodes='[24,48,96,32]' \
#     algorithm.encoder.strides='[1,2]' \
#     algorithm.kl_scale=0.0003 \
#     algorithm.kl_warmup_frac=0.05 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.00010857963609121084 \
#     algorithm.optimizer.weight_decay=0.001 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 441: cap=-0.14858, kl=122.87
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     experiment=cifar10/vae_agnostic \
#     experiment_name=cifar10_vae_pareto \
#     run_name=cap_t441 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_reference_normal \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.batchnorm=False \
#     algorithm.encoder.clamp_zlogvar_range='[-6,4]' \
#     algorithm.encoder.nodes='[24,48,96,32]' \
#     algorithm.encoder.strides='[1,2]' \
#     algorithm.kl_scale=0.0003 \
#     algorithm.kl_warmup_frac=0.05 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.00010439993053418744 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 443: cap=-0.14837, kl=123.84  << BEST cap
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     experiment=cifar10/vae_agnostic \
#     experiment_name=cifar10_vae_pareto \
#     run_name=cap_t443 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_reference_normal \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.batchnorm=False \
#     algorithm.encoder.clamp_zlogvar_range='[-6,4]' \
#     algorithm.encoder.nodes='[24,48,96,32]' \
#     algorithm.encoder.strides='[1,2]' \
#     algorithm.kl_scale=0.0003 \
#     algorithm.kl_warmup_frac=0.05 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.00010443565850199426 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 518: cap=-0.16251, kl=43.302
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     experiment=cifar10/vae_agnostic \
#     experiment_name=cifar10_vae_pareto \
#     run_name=cap_t518 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_reference_normal \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.batchnorm=False \
#     algorithm.encoder.clamp_zlogvar_range='[-6,4]' \
#     algorithm.encoder.nodes='[16,32,64,16]' \
#     algorithm.encoder.strides='[1,2]' \
#     algorithm.kl_scale=0.002 \
#     algorithm.kl_warmup_frac=0.2 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.00012214328250071614 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[3]

# ------------------------------------------------------------------------
# trial 519: cap=-0.16248, kl=43.322
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     experiment=cifar10/vae_agnostic \
#     experiment_name=cifar10_vae_pareto \
#     run_name=cap_t519 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_reference_normal \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.batchnorm=False \
#     algorithm.encoder.clamp_zlogvar_range='[-6,4]' \
#     algorithm.encoder.nodes='[16,32,64,16]' \
#     algorithm.encoder.strides='[1,2]' \
#     algorithm.kl_scale=0.002 \
#     algorithm.kl_warmup_frac=0.2 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.00012215627084441504 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 520: cap=-0.16235, kl=43.34  << ORIGINAL PICK
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     experiment=cifar10/vae_agnostic \
#     experiment_name=cifar10_vae_pareto \
#     run_name=cap_t520 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_reference_normal \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.batchnorm=False \
#     algorithm.encoder.clamp_zlogvar_range='[-6,4]' \
#     algorithm.encoder.nodes='[16,32,64,16]' \
#     algorithm.encoder.strides='[1,2]' \
#     algorithm.kl_scale=0.002 \
#     algorithm.kl_warmup_frac=0.2 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.00012155116550631143 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 521: cap=-0.1626, kl=43.297
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     experiment=cifar10/vae_agnostic \
#     experiment_name=cifar10_vae_pareto \
#     run_name=cap_t521 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_reference_normal \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.batchnorm=False \
#     algorithm.encoder.clamp_zlogvar_range='[-6,4]' \
#     algorithm.encoder.nodes='[16,32,64,16]' \
#     algorithm.encoder.strides='[1,2]' \
#     algorithm.kl_scale=0.002 \
#     algorithm.kl_warmup_frac=0.2 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.00012199186698634934 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 559: cap=-0.14967, kl=122.34
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     experiment=cifar10/vae_agnostic \
#     experiment_name=cifar10_vae_pareto \
#     run_name=cap_t559 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_reference_normal \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.batchnorm=False \
#     algorithm.encoder.clamp_zlogvar_range='[-6,4]' \
#     algorithm.encoder.nodes='[24,48,96,32]' \
#     algorithm.encoder.strides='[1,2]' \
#     algorithm.kl_scale=0.0003 \
#     algorithm.kl_warmup_frac=0.05 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.00010819194834505472 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[3]

# ------------------------------------------------------------------------
# trial 560: cap=-0.14959, kl=122.58
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     experiment=cifar10/vae_agnostic \
#     experiment_name=cifar10_vae_pareto \
#     run_name=cap_t560 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_reference_normal \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.batchnorm=False \
#     algorithm.encoder.clamp_zlogvar_range='[-6,4]' \
#     algorithm.encoder.nodes='[24,48,96,32]' \
#     algorithm.encoder.strides='[1,2]' \
#     algorithm.kl_scale=0.0003 \
#     algorithm.kl_warmup_frac=0.05 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.00010831721111622483 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[0]

# ========================================================================
# STABILITY TRAINING  (study: drift_vs_kl, 2 Pareto points)
# ========================================================================
# ------------------------------------------------------------------------
# trial 245: drift=0.18232, kl=3.0208
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     experiment=cifar10/vae_agnostic \
#     experiment_name=cifar10_vae_pareto \
#     run_name=stability_t245 \
#     callbacks.wasserstein_dist=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_reference_normal \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_reference_normal \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.batchnorm=True \
#     algorithm.encoder.clamp_zlogvar_range='[-10,6]' \
#     algorithm.encoder.nodes='[16,32,64,32]' \
#     algorithm.encoder.strides='[2,2]' \
#     algorithm.kl_scale=0.001 \
#     algorithm.kl_warmup_frac=0.1 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=5.135194451214502e-05 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=2.0 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 587: drift=0.15415, kl=8.4046  << ORIGINAL PICK | BEST drift
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     experiment=cifar10/vae_agnostic \
#     experiment_name=cifar10_vae_pareto \
#     run_name=stability_t587 \
#     callbacks.wasserstein_dist=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_reference_normal \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_reference_normal \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.batchnorm=False \
#     algorithm.encoder.clamp_zlogvar_range='[-10,6]' \
#     algorithm.encoder.nodes='[16,32,64,32]' \
#     algorithm.encoder.strides='[2,1]' \
#     algorithm.kl_scale=0.0001 \
#     algorithm.kl_warmup_frac=0.2 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=5.0005417147756347e-05 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=2.0 \
#     trainer=gpu \
#     trainer.devices=[1]

# ========================================================================
# WASSERSTEIN TRAINING  (study: wasserstein_vs_kl, 1 Pareto points)
# ========================================================================
# ------------------------------------------------------------------------
# trial 596: wasserstein=0.00084275, kl=0.11834  << ORIGINAL PICK | BEST wasserstein
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     experiment=cifar10/vae_agnostic \
#     experiment_name=cifar10_vae_pareto \
#     run_name=wasserstein_t596 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_reference_normal \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.batchnorm=False \
#     algorithm.encoder.clamp_zlogvar_range='[-10,6]' \
#     algorithm.encoder.nodes='[24,48,96,32]' \
#     algorithm.encoder.strides='[2,2]' \
#     algorithm.kl_scale=0.002 \
#     algorithm.kl_warmup_frac=0.0 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0001892559752409742 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[0]

# ========================================================================
# SUBMIT EVERYTHING ABOVE TO CLARIDEN  (one slurm job per command)
# ========================================================================
# Set paths.raw_data_dir to the data location on clariden; any extra
# hydra overrides appended here are added to every job.
# bash scripts/submit_pareto.sh scripts/cifar10/runvae_pareto.sh \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files
