#!/usr/bin/env python

import argparse
from pathlib import Path

import mlflow
import numpy as np


parser = argparse.ArgumentParser(formatter_class=argparse.ArgumentDefaultsHelpFormatter)
parser.add_argument('--experiment_name', type=str, help="The name of the MLFlow experiment.")
args = parser.parse_args()


mlflow_uri = "file:../logs/mlflow/mlruns"
mlflow.set_tracking_uri(mlflow_uri)

# Get the desired experiment.
print(f"Fetching data for experiment {args.experiment_name}...")
runs = mlflow.search_runs(experiment_names=[args.experiment_name])

client = mlflow.tracking.MlflowClient()
metrics = [column[8:] for column in runs.columns if column.startswith("metrics")]
run_names = runs["tags.mlflow.runName"].values.tolist()
run_ids = runs["run_id"].values.tolist()

output_dir = Path(f"./mlflow_data/{args.experiment_name}")
for idx, run_id in enumerate(run_ids):
    print(f"Getting metrics for run {run_names[idx]}")
    run_dir = output_dir / run_names[idx]
    run_dir.mkdir(parents=True, exist_ok=True)
    for metric in metrics:
        metric_values = np.array([
            metric_value.value
            for metric_value
            in client.get_metric_history(run_id, metric)
        ])
        metric_filepath = run_dir / (metric.replace('/', '_') + ".dat")
        metric_values.astype('float32').tofile(metric_filepath)
        print(f"Metric saved to {metric_filepath}!\n")
