# ========================================================================
# AE PARETO-FRONT TRAINING COMMANDS
# ========================================================================
# These are the training commands for every point on the Pareto front of
# each validation strategy. Generated by scripts/make_pareto_scripts.py from
# notebooks/paretos/physics/ -- regenerate rather than edit by hand.
#
# Run from the repository root. All commands are commented out -- uncomment
# the points you want to run. Device / taskset assignments cycle over the
# four GPUs.

# ========================================================================
# CVAR25 TRAINING  (study: cvar25eff_vs_mse_b16k, 7 Pareto points)
# ========================================================================
# ------------------------------------------------------------------------
# trial 169: cvar25eff=1.8793, mse=0.21281  << ORIGINAL PICK | BEST cvar25eff
# ------------------------------------------------------------------------
taskset -c 0-2 \
python3 src/train.py \
    paths.raw_data_dir=/data/deodagiu/adl1t_data/parquet_files \
    experiment=physics/ae \
    experiment_name=physics_ae_pareto \
    run_name=cvar25_t169 \
    algorithm.encoder.nodes='[64,32,8]' \
    algorithm.input_noise_std=0.0 \
    algorithm.delta=10.0 \
    algorithm.optimizer.betas='[0.9,0.999]' \
    algorithm.optimizer.lr=0.0019859329798336714 \
    algorithm.optimizer.weight_decay=1e-06 \
    trainer.gradient_clip_val=5.0 \
    trainer=gpu \
    trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 239: cvar25eff=1.577, mse=0.20467  << KNEE
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/ae \
#     experiment_name=physics_ae_pareto \
#     run_name=cvar25_t239 \
#     algorithm.encoder.nodes='[64,32,8]' \
#     algorithm.input_noise_std=0.0 \
#     algorithm.delta=10.0 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0017860579498200522 \
#     algorithm.optimizer.weight_decay=1e-06 \
#     trainer.gradient_clip_val=5.0 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 281: cvar25eff=1.5064, mse=0.19208
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/ae \
#     experiment_name=physics_ae_pareto \
#     run_name=cvar25_t281 \
#     algorithm.encoder.nodes='[64,32,8]' \
#     algorithm.input_noise_std=0.0 \
#     algorithm.delta=10.0 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0022046443124541606 \
#     algorithm.optimizer.weight_decay=1e-06 \
#     trainer.gradient_clip_val=5.0 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 332: cvar25eff=1.1125, mse=0.16769
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/ae \
#     experiment_name=physics_ae_pareto \
#     run_name=cvar25_t332 \
#     algorithm.encoder.nodes='[64,32,32]' \
#     algorithm.input_noise_std=0.0 \
#     algorithm.delta=10.0 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.002226412053684666 \
#     algorithm.optimizer.weight_decay=1e-06 \
#     trainer.gradient_clip_val=5.0 \
#     trainer=gpu \
#     trainer.devices=[3]

# ------------------------------------------------------------------------
# trial 357: cvar25eff=0.96219, mse=0.14817
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/ae \
#     experiment_name=physics_ae_pareto \
#     run_name=cvar25_t357 \
#     algorithm.encoder.nodes='[64,32,32]' \
#     algorithm.input_noise_std=0.0 \
#     algorithm.delta=10.0 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.002051993353313883 \
#     algorithm.optimizer.weight_decay=1e-06 \
#     trainer.gradient_clip_val=5.0 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 379: cvar25eff=1.3345, mse=0.16864
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/ae \
#     experiment_name=physics_ae_pareto \
#     run_name=cvar25_t379 \
#     algorithm.encoder.nodes='[64,32,32]' \
#     algorithm.input_noise_std=0.0 \
#     algorithm.delta=10.0 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0022190221710598084 \
#     algorithm.optimizer.weight_decay=1e-06 \
#     trainer.gradient_clip_val=5.0 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 520: cvar25eff=1.0707, mse=0.15564
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/ae \
#     experiment_name=physics_ae_pareto \
#     run_name=cvar25_t520 \
#     algorithm.encoder.nodes='[64,32,32]' \
#     algorithm.input_noise_std=0.0 \
#     algorithm.delta=10.0 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0019789545082545034 \
#     algorithm.optimizer.weight_decay=1e-06 \
#     trainer.gradient_clip_val=5.0 \
#     trainer=gpu \
#     trainer.devices=[2]

# ========================================================================
# CVAR10 TRAINING  (study: cvar10eff_vs_mse_b16k, 7 Pareto points)
# ========================================================================
# ------------------------------------------------------------------------
# trial 34: cvar10eff=0.2548, mse=0.20898
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/ae \
#     experiment_name=physics_ae_pareto \
#     run_name=cvar10_t34 \
#     evaluation.callbacks.anomaly_efficiency.cvar_summary=0.10 \
#     algorithm.encoder.nodes='[64,32,8]' \
#     algorithm.input_noise_std=0.003 \
#     algorithm.delta=5.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0017289611925142678 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 165: cvar10eff=0.26396, mse=0.21713
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/ae \
#     experiment_name=physics_ae_pareto \
#     run_name=cvar10_t165 \
#     evaluation.callbacks.anomaly_efficiency.cvar_summary=0.10 \
#     algorithm.encoder.nodes='[64,32,8]' \
#     algorithm.input_noise_std=0.003 \
#     algorithm.delta=5.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0017865296714410016 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 322: cvar10eff=0.13045, mse=0.15881
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/ae \
#     experiment_name=physics_ae_pareto \
#     run_name=cvar10_t322 \
#     evaluation.callbacks.anomaly_efficiency.cvar_summary=0.10 \
#     algorithm.encoder.nodes='[64,32,32]' \
#     algorithm.input_noise_std=0.003 \
#     algorithm.delta=5.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.002556446038607921 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 331: cvar10eff=0.31051, mse=0.23161  << BEST cvar10eff
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/ae \
#     experiment_name=physics_ae_pareto \
#     run_name=cvar10_t331 \
#     evaluation.callbacks.anomaly_efficiency.cvar_summary=0.10 \
#     algorithm.encoder.nodes='[64,32,8]' \
#     algorithm.input_noise_std=0.003 \
#     algorithm.delta=5.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0018619950325312572 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[3]

# ------------------------------------------------------------------------
# trial 368: cvar10eff=0.2098, mse=0.16097  << KNEE
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/ae \
#     experiment_name=physics_ae_pareto \
#     run_name=cvar10_t368 \
#     evaluation.callbacks.anomaly_efficiency.cvar_summary=0.10 \
#     algorithm.encoder.nodes='[64,32,32]' \
#     algorithm.input_noise_std=0.003 \
#     algorithm.delta=5.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0025560335463653432 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 406: cvar10eff=0.13579, mse=0.16028
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/ae \
#     experiment_name=physics_ae_pareto \
#     run_name=cvar10_t406 \
#     evaluation.callbacks.anomaly_efficiency.cvar_summary=0.10 \
#     algorithm.encoder.nodes='[64,32,32]' \
#     algorithm.input_noise_std=0.003 \
#     algorithm.delta=10.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0026150688092766226 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 414: cvar10eff=0.1213, mse=0.15847
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/ae \
#     experiment_name=physics_ae_pareto \
#     run_name=cvar10_t414 \
#     evaluation.callbacks.anomaly_efficiency.cvar_summary=0.10 \
#     algorithm.encoder.nodes='[64,32,32]' \
#     algorithm.input_noise_std=0.003 \
#     algorithm.delta=10.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0026063244932853927 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[2]

# ========================================================================
# CAP TRAINING  (study: cap_vs_mse_b16k, 5 Pareto points)
# ========================================================================
# ------------------------------------------------------------------------
# trial 175: cap=-0.21905, mse=0.17967  << ORIGINAL PICK
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/ae_agnostic \
#     experiment_name=physics_ae_pareto \
#     run_name=cap_t175 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.encoder.nodes='[64,32,16]' \
#     algorithm.input_noise_std=0.0001 \
#     algorithm.delta=10.0 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0028379676477468516 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 229: cap=-0.21644, mse=0.188  << KNEE
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/ae_agnostic \
#     experiment_name=physics_ae_pareto \
#     run_name=cap_t229 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.encoder.nodes='[64,32,16]' \
#     algorithm.input_noise_std=0.0001 \
#     algorithm.delta=10.0 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.002479901587876306 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 392: cap=-0.21436, mse=0.38293  << BEST cap
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/ae_agnostic \
#     experiment_name=physics_ae_pareto \
#     run_name=cap_t392 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.encoder.nodes='[24,8,4]' \
#     algorithm.input_noise_std=0.0001 \
#     algorithm.delta=10.0 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.002746319234488316 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=2.0 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 406: cap=-0.21487, mse=0.36239
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/ae_agnostic \
#     experiment_name=physics_ae_pareto \
#     run_name=cap_t406 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.encoder.nodes='[24,8,4]' \
#     algorithm.input_noise_std=0.0001 \
#     algorithm.delta=10.0 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.002775385552612688 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=2.0 \
#     trainer=gpu \
#     trainer.devices=[3]

# ------------------------------------------------------------------------
# trial 447: cap=-0.21934, mse=0.17097
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/ae_agnostic \
#     experiment_name=physics_ae_pareto \
#     run_name=cap_t447 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.encoder.nodes='[64,32,16]' \
#     algorithm.input_noise_std=0.0001 \
#     algorithm.delta=10.0 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.002542908265029417 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[0]

# ========================================================================
# STABILITY TRAINING  (study: drift_vs_mse_b16k, 2 Pareto points)
# ========================================================================
# ------------------------------------------------------------------------
# trial 380: drift=0.039093, mse=0.1702
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/ae_agnostic \
#     experiment_name=physics_ae_pareto \
#     run_name=stability_t380 \
#     callbacks.wasserstein_dist=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_SingleNeutrino_E-10-gun \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.encoder.nodes='[64,32,24]' \
#     algorithm.input_noise_std=0.0003 \
#     algorithm.delta=10.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.002547317020597471 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=5.0 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 564: drift=0.013551, mse=0.17071  << ORIGINAL PICK | BEST drift
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/ae_agnostic \
#     experiment_name=physics_ae_pareto \
#     run_name=stability_t564 \
#     callbacks.wasserstein_dist=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_SingleNeutrino_E-10-gun \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.encoder.nodes='[64,32,24]' \
#     algorithm.input_noise_std=0.0003 \
#     algorithm.delta=7.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.002583753082224847 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=2.0 \
#     trainer=gpu \
#     trainer.devices=[1]

# ========================================================================
# WASSERSTEIN TRAINING  (study: wasserstein_vs_mse_b16k, 16 Pareto points)
# ========================================================================
# ------------------------------------------------------------------------
# trial 178: wasserstein=0.0038752, mse=0.17002
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/ae_agnostic \
#     experiment_name=physics_ae_pareto \
#     run_name=wasserstein_t178 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.encoder.nodes='[64,32,32]' \
#     algorithm.input_noise_std=0.003 \
#     algorithm.delta=10.0 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.002646980018226206 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=1.0 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 200: wasserstein=0.0034142, mse=0.2888
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/ae_agnostic \
#     experiment_name=physics_ae_pareto \
#     run_name=wasserstein_t200 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.encoder.nodes='[32,16,8]' \
#     algorithm.input_noise_std=0.003 \
#     algorithm.delta=10.0 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0022097293350206693 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=1.0 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 261: wasserstein=0.0038967, mse=0.1667
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/ae_agnostic \
#     experiment_name=physics_ae_pareto \
#     run_name=wasserstein_t261 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.encoder.nodes='[64,32,32]' \
#     algorithm.input_noise_std=0.003 \
#     algorithm.delta=10.0 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.002302976354955957 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=1.0 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 262: wasserstein=0.0041813, mse=0.1539
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/ae_agnostic \
#     experiment_name=physics_ae_pareto \
#     run_name=wasserstein_t262 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.encoder.nodes='[64,32,32]' \
#     algorithm.input_noise_std=0.003 \
#     algorithm.delta=10.0 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.002282521936632589 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=1.0 \
#     trainer=gpu \
#     trainer.devices=[3]

# ------------------------------------------------------------------------
# trial 285: wasserstein=0.0034199, mse=0.27305
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/ae_agnostic \
#     experiment_name=physics_ae_pareto \
#     run_name=wasserstein_t285 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.encoder.nodes='[32,16,8]' \
#     algorithm.input_noise_std=0.003 \
#     algorithm.delta=10.0 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.002516839097364944 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=1.0 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 347: wasserstein=0.0026489, mse=0.36437  << BEST wasserstein
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/ae_agnostic \
#     experiment_name=physics_ae_pareto \
#     run_name=wasserstein_t347 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.encoder.nodes='[24,8,4]' \
#     algorithm.input_noise_std=0.003 \
#     algorithm.delta=10.0 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0015984423128631963 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=1.0 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 357: wasserstein=0.0039119, mse=0.15557
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/ae_agnostic \
#     experiment_name=physics_ae_pareto \
#     run_name=wasserstein_t357 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.encoder.nodes='[64,32,32]' \
#     algorithm.input_noise_std=0.003 \
#     algorithm.delta=10.0 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.002779834743254138 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=1.0 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 374: wasserstein=0.0035178, mse=0.25315
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/ae_agnostic \
#     experiment_name=physics_ae_pareto \
#     run_name=wasserstein_t374 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.encoder.nodes='[32,16,8]' \
#     algorithm.input_noise_std=0.003 \
#     algorithm.delta=10.0 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.002980984817655451 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=1.0 \
#     trainer=gpu \
#     trainer.devices=[3]

# ------------------------------------------------------------------------
# trial 447: wasserstein=0.0032424, mse=0.34493
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/ae_agnostic \
#     experiment_name=physics_ae_pareto \
#     run_name=wasserstein_t447 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.encoder.nodes='[16,8]' \
#     algorithm.input_noise_std=0.003 \
#     algorithm.delta=10.0 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0029948256479085896 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=1.0 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 456: wasserstein=0.0032851, mse=0.34191
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/ae_agnostic \
#     experiment_name=physics_ae_pareto \
#     run_name=wasserstein_t456 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.encoder.nodes='[16,8]' \
#     algorithm.input_noise_std=0.003 \
#     algorithm.delta=10.0 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.002763801428319547 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=1.0 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 474: wasserstein=0.0032093, mse=0.36078  << KNEE
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/ae_agnostic \
#     experiment_name=physics_ae_pareto \
#     run_name=wasserstein_t474 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.encoder.nodes='[32,16,8]' \
#     algorithm.input_noise_std=0.003 \
#     algorithm.delta=10.0 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.002998594683246037 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=1.0 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 505: wasserstein=0.0032488, mse=0.34221
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/ae_agnostic \
#     experiment_name=physics_ae_pareto \
#     run_name=wasserstein_t505 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.encoder.nodes='[16,8]' \
#     algorithm.input_noise_std=0.003 \
#     algorithm.delta=5.0 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0027611234080054314 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=1.0 \
#     trainer=gpu \
#     trainer.devices=[3]

# ------------------------------------------------------------------------
# trial 513: wasserstein=0.0033907, mse=0.32515
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/ae_agnostic \
#     experiment_name=physics_ae_pareto \
#     run_name=wasserstein_t513 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.encoder.nodes='[32,16,8]' \
#     algorithm.input_noise_std=0.003 \
#     algorithm.delta=5.0 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.002551194585322046 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=2.0 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 539: wasserstein=0.0032912, mse=0.33938
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/ae_agnostic \
#     experiment_name=physics_ae_pareto \
#     run_name=wasserstein_t539 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.encoder.nodes='[32,16,8]' \
#     algorithm.input_noise_std=0.003 \
#     algorithm.delta=10.0 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.002998885086004602 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=1.0 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 549: wasserstein=0.0038723, mse=0.18592
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/ae_agnostic \
#     experiment_name=physics_ae_pareto \
#     run_name=wasserstein_t549 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.encoder.nodes='[64,32,32]' \
#     algorithm.input_noise_std=0.003 \
#     algorithm.delta=10.0 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0015800984038449577 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=1.0 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 584: wasserstein=0.0036503, mse=0.22663
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/ae_agnostic \
#     experiment_name=physics_ae_pareto \
#     run_name=wasserstein_t584 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.encoder.nodes='[32,16,8]' \
#     algorithm.input_noise_std=0.003 \
#     algorithm.delta=10.0 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0022921058516179194 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=1.0 \
#     trainer=gpu \
#     trainer.devices=[3]

# ------------------------------------------------------------------------
# trial 584: objective values unknown  << ORIGINAL PICK (handpicked; predates the current study db -- no matching trial, command copied verbatim from the original runae.sh)
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/ae_agnostic \
#     experiment_name=physics_ae_pareto \
#     run_name=wasserstein_t584 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.delta=5.0 \
#     algorithm.encoder.nodes='[64,32,32]' \
#     algorithm.input_noise_std=0.001 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.00047124714609726086 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[0]
