# ========================================================================
# REALNVP PARETO-FRONT TRAINING COMMANDS
# ========================================================================
# q99 background-rate study: training commands for every point on the Pareto front of
# each validation strategy. Generated by scripts/make_pareto_scripts.py from
# notebooks/paretos/physics/ -- regenerate rather than edit by hand.
#
# Run from the repository root. All commands are commented out -- uncomment
# the points you want to run. Device / taskset assignments cycle over the
# four GPUs.

# ========================================================================
# CVAR25 TRAINING  (study: cvar25eff_vs_logpq99, 36 Pareto points, trimmed to 12 around the knee (endpoints kept))
# ========================================================================
# ------------------------------------------------------------------------
# trial 156: cvar25eff=196.78, logpq99=72.128  << KNEE
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/realnvp \
#     experiment_name=physics_realnvp_q99_pareto \
#     run_name=cvar25_t156 \
#     algorithm.target_rate=0.01 \
#     algorithm.base_rate=null \
#     algorithm.flow.activation=gelu \
#     algorithm.flow.hidden_dim=48 \
#     algorithm.flow.n_flows=6 \
#     algorithm.flow.n_hidden_layers=2 \
#     algorithm.flow.noise_scale=0.0 \
#     algorithm.flow.scale_clamp=5.0 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0003750697936988472 \
#     algorithm.optimizer.weight_decay=1e-06 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 248: cvar25eff=163.98, logpq99=-90.319
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/realnvp \
#     experiment_name=physics_realnvp_q99_pareto \
#     run_name=cvar25_t248 \
#     algorithm.target_rate=0.01 \
#     algorithm.base_rate=null \
#     algorithm.flow.activation=relu \
#     algorithm.flow.hidden_dim=48 \
#     algorithm.flow.n_flows=8 \
#     algorithm.flow.n_hidden_layers=2 \
#     algorithm.flow.noise_scale=0.0 \
#     algorithm.flow.scale_clamp=3.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.000575631245401733 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 250: cvar25eff=156.92, logpq99=-99.273
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/realnvp \
#     experiment_name=physics_realnvp_q99_pareto \
#     run_name=cvar25_t250 \
#     algorithm.target_rate=0.01 \
#     algorithm.base_rate=null \
#     algorithm.flow.activation=relu \
#     algorithm.flow.hidden_dim=48 \
#     algorithm.flow.n_flows=8 \
#     algorithm.flow.n_hidden_layers=2 \
#     algorithm.flow.noise_scale=0.0 \
#     algorithm.flow.scale_clamp=3.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0005723305800069265 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 362: cvar25eff=192.42, logpq99=37.734
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/realnvp \
#     experiment_name=physics_realnvp_q99_pareto \
#     run_name=cvar25_t362 \
#     algorithm.target_rate=0.01 \
#     algorithm.base_rate=null \
#     algorithm.flow.activation=gelu \
#     algorithm.flow.hidden_dim=48 \
#     algorithm.flow.n_flows=8 \
#     algorithm.flow.n_hidden_layers=2 \
#     algorithm.flow.noise_scale=0.0 \
#     algorithm.flow.scale_clamp=5.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0005088198852772951 \
#     algorithm.optimizer.weight_decay=1e-06 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[3]

# ------------------------------------------------------------------------
# trial 364: cvar25eff=166.28, logpq99=-7.7498
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/realnvp \
#     experiment_name=physics_realnvp_q99_pareto \
#     run_name=cvar25_t364 \
#     algorithm.target_rate=0.01 \
#     algorithm.base_rate=null \
#     algorithm.flow.activation=gelu \
#     algorithm.flow.hidden_dim=48 \
#     algorithm.flow.n_flows=8 \
#     algorithm.flow.n_hidden_layers=2 \
#     algorithm.flow.noise_scale=0.0 \
#     algorithm.flow.scale_clamp=3.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0005306342538542524 \
#     algorithm.optimizer.weight_decay=1e-06 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 374: cvar25eff=221.07, logpq99=74.251
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/realnvp \
#     experiment_name=physics_realnvp_q99_pareto \
#     run_name=cvar25_t374 \
#     algorithm.target_rate=0.01 \
#     algorithm.base_rate=null \
#     algorithm.flow.activation=gelu \
#     algorithm.flow.hidden_dim=48 \
#     algorithm.flow.n_flows=8 \
#     algorithm.flow.n_hidden_layers=2 \
#     algorithm.flow.noise_scale=0.0 \
#     algorithm.flow.scale_clamp=5.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.000483072686454125 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 398: cvar25eff=227.36, logpq99=84.598
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/realnvp \
#     experiment_name=physics_realnvp_q99_pareto \
#     run_name=cvar25_t398 \
#     algorithm.target_rate=0.01 \
#     algorithm.base_rate=null \
#     algorithm.flow.activation=gelu \
#     algorithm.flow.hidden_dim=48 \
#     algorithm.flow.n_flows=8 \
#     algorithm.flow.n_hidden_layers=2 \
#     algorithm.flow.noise_scale=0.0 \
#     algorithm.flow.scale_clamp=5.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0004932795612912492 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 409: cvar25eff=219.05, logpq99=72.692
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/realnvp \
#     experiment_name=physics_realnvp_q99_pareto \
#     run_name=cvar25_t409 \
#     algorithm.target_rate=0.01 \
#     algorithm.base_rate=null \
#     algorithm.flow.activation=gelu \
#     algorithm.flow.hidden_dim=48 \
#     algorithm.flow.n_flows=8 \
#     algorithm.flow.n_hidden_layers=2 \
#     algorithm.flow.noise_scale=0.0 \
#     algorithm.flow.scale_clamp=5.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.000536924839119063 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[3]

# ------------------------------------------------------------------------
# trial 466: cvar25eff=298.38, logpq99=133.5  << ORIGINAL PICK | BEST cvar25eff
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/realnvp \
#     experiment_name=physics_realnvp_q99_pareto \
#     run_name=cvar25_t466 \
#     algorithm.target_rate=0.01 \
#     algorithm.base_rate=null \
#     algorithm.flow.activation=gelu \
#     algorithm.flow.hidden_dim=48 \
#     algorithm.flow.n_flows=8 \
#     algorithm.flow.n_hidden_layers=2 \
#     algorithm.flow.noise_scale=0.0 \
#     algorithm.flow.scale_clamp=5.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=3.7803380868254345e-05 \
#     algorithm.optimizer.weight_decay=1e-06 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 527: cvar25eff=236.6, logpq99=85.446
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/realnvp \
#     experiment_name=physics_realnvp_q99_pareto \
#     run_name=cvar25_t527 \
#     algorithm.target_rate=0.01 \
#     algorithm.base_rate=null \
#     algorithm.flow.activation=gelu \
#     algorithm.flow.hidden_dim=48 \
#     algorithm.flow.n_flows=8 \
#     algorithm.flow.n_hidden_layers=2 \
#     algorithm.flow.noise_scale=0.0 \
#     algorithm.flow.scale_clamp=5.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0004985320102952522 \
#     algorithm.optimizer.weight_decay=1e-06 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 536: cvar25eff=169.06, logpq99=11.603
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/realnvp \
#     experiment_name=physics_realnvp_q99_pareto \
#     run_name=cvar25_t536 \
#     algorithm.target_rate=0.01 \
#     algorithm.base_rate=null \
#     algorithm.flow.activation=relu \
#     algorithm.flow.hidden_dim=48 \
#     algorithm.flow.n_flows=8 \
#     algorithm.flow.n_hidden_layers=2 \
#     algorithm.flow.noise_scale=0.0 \
#     algorithm.flow.scale_clamp=5.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0005386873045680958 \
#     algorithm.optimizer.weight_decay=1e-06 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 655: cvar25eff=94.035, logpq99=-156.66
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/realnvp \
#     experiment_name=physics_realnvp_q99_pareto \
#     run_name=cvar25_t655 \
#     algorithm.target_rate=0.01 \
#     algorithm.base_rate=null \
#     algorithm.flow.activation=relu \
#     algorithm.flow.hidden_dim=64 \
#     algorithm.flow.n_flows=8 \
#     algorithm.flow.n_hidden_layers=2 \
#     algorithm.flow.noise_scale=0.0001 \
#     algorithm.flow.scale_clamp=5.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0005142069419818001 \
#     algorithm.optimizer.weight_decay=1e-06 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[3]

# ========================================================================
# CAP TRAINING  (study: cap_vs_logpq99, 2 Pareto points)
# ========================================================================
# ------------------------------------------------------------------------
# trial 200: cap=-0.1179, logpq99=-155.28  << ORIGINAL PICK | BEST cap
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/realnvp_agnostic \
#     experiment_name=physics_realnvp_q99_pareto \
#     run_name=cap_t200 \
#     algorithm.target_rate=0.01 \
#     algorithm.base_rate=null \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.flow.activation=relu \
#     algorithm.flow.hidden_dim=64 \
#     algorithm.flow.n_flows=8 \
#     algorithm.flow.n_hidden_layers=2 \
#     algorithm.flow.noise_scale=0.0001 \
#     algorithm.flow.scale_clamp=5.0 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0008856132495375707 \
#     algorithm.optimizer.weight_decay=1e-06 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 224: cap=-0.21402, logpq99=-157.15
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/realnvp_agnostic \
#     experiment_name=physics_realnvp_q99_pareto \
#     run_name=cap_t224 \
#     algorithm.target_rate=0.01 \
#     algorithm.base_rate=null \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.flow.activation=relu \
#     algorithm.flow.hidden_dim=64 \
#     algorithm.flow.n_flows=8 \
#     algorithm.flow.n_hidden_layers=2 \
#     algorithm.flow.noise_scale=0.0001 \
#     algorithm.flow.scale_clamp=5.0 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0008494909394656174 \
#     algorithm.optimizer.weight_decay=1e-06 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[1]

# ========================================================================
# STABILITY TRAINING  (study: drift_vs_logpq99, 4 Pareto points)
# ========================================================================
# ------------------------------------------------------------------------
# trial 254: drift=3.9736e-05, logpq99=-151.91
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/realnvp_agnostic \
#     experiment_name=physics_realnvp_q99_pareto \
#     run_name=stability_t254 \
#     algorithm.target_rate=0.01 \
#     algorithm.base_rate=null \
#     callbacks.wasserstein_dist=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_SingleNeutrino_E-10-gun \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.flow.activation=gelu \
#     algorithm.flow.hidden_dim=48 \
#     algorithm.flow.n_flows=8 \
#     algorithm.flow.n_hidden_layers=2 \
#     algorithm.flow.noise_scale=0.0001 \
#     algorithm.flow.scale_clamp=5.0 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0008557648504721822 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 445: drift=0.00053491, logpq99=-154.53
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/realnvp_agnostic \
#     experiment_name=physics_realnvp_q99_pareto \
#     run_name=stability_t445 \
#     algorithm.target_rate=0.01 \
#     algorithm.base_rate=null \
#     callbacks.wasserstein_dist=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_SingleNeutrino_E-10-gun \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.flow.activation=relu \
#     algorithm.flow.hidden_dim=48 \
#     algorithm.flow.n_flows=8 \
#     algorithm.flow.n_hidden_layers=2 \
#     algorithm.flow.noise_scale=0.0001 \
#     algorithm.flow.scale_clamp=5.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0008223345297944777 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 548: drift=8.1388e-06, logpq99=-146.76  << BEST drift
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/realnvp_agnostic \
#     experiment_name=physics_realnvp_q99_pareto \
#     run_name=stability_t548 \
#     algorithm.target_rate=0.01 \
#     algorithm.base_rate=null \
#     callbacks.wasserstein_dist=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_SingleNeutrino_E-10-gun \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.flow.activation=relu \
#     algorithm.flow.hidden_dim=48 \
#     algorithm.flow.n_flows=8 \
#     algorithm.flow.n_hidden_layers=2 \
#     algorithm.flow.noise_scale=0.0001 \
#     algorithm.flow.scale_clamp=5.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.000787231729254959 \
#     algorithm.optimizer.weight_decay=1e-06 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 595: drift=5.6015e-05, logpq99=-153.07  << ORIGINAL PICK | KNEE
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/realnvp_agnostic \
#     experiment_name=physics_realnvp_q99_pareto \
#     run_name=stability_t595 \
#     algorithm.target_rate=0.01 \
#     algorithm.base_rate=null \
#     callbacks.wasserstein_dist=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_SingleNeutrino_E-10-gun \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.flow.activation=relu \
#     algorithm.flow.hidden_dim=48 \
#     algorithm.flow.n_flows=8 \
#     algorithm.flow.n_hidden_layers=2 \
#     algorithm.flow.noise_scale=0.0001 \
#     algorithm.flow.scale_clamp=5.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0008426900182503831 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[3]

# ========================================================================
# WASSERSTEIN TRAINING  (study: wasserstein_vs_logpq99, 8 Pareto points)
# ========================================================================
# ------------------------------------------------------------------------
# trial 160: wasserstein=0.00071626, logpq99=-79.077  << BEST wasserstein
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/realnvp_agnostic \
#     experiment_name=physics_realnvp_q99_pareto \
#     run_name=wasserstein_t160 \
#     algorithm.target_rate=0.01 \
#     algorithm.base_rate=null \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.flow.activation=relu \
#     algorithm.flow.hidden_dim=64 \
#     algorithm.flow.n_flows=8 \
#     algorithm.flow.n_hidden_layers=2 \
#     algorithm.flow.noise_scale=0.01 \
#     algorithm.flow.scale_clamp=3.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.001056241830812491 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 216: wasserstein=0.0010237, logpq99=-80.461
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/realnvp_agnostic \
#     experiment_name=physics_realnvp_q99_pareto \
#     run_name=wasserstein_t216 \
#     algorithm.target_rate=0.01 \
#     algorithm.base_rate=null \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.flow.activation=relu \
#     algorithm.flow.hidden_dim=64 \
#     algorithm.flow.n_flows=8 \
#     algorithm.flow.n_hidden_layers=2 \
#     algorithm.flow.noise_scale=0.01 \
#     algorithm.flow.scale_clamp=5.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0016806038710917332 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 222: wasserstein=0.00092514, logpq99=-80.3
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/realnvp_agnostic \
#     experiment_name=physics_realnvp_q99_pareto \
#     run_name=wasserstein_t222 \
#     algorithm.target_rate=0.01 \
#     algorithm.base_rate=null \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.flow.activation=relu \
#     algorithm.flow.hidden_dim=64 \
#     algorithm.flow.n_flows=8 \
#     algorithm.flow.n_hidden_layers=2 \
#     algorithm.flow.noise_scale=0.01 \
#     algorithm.flow.scale_clamp=5.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0012319807597370705 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 253: wasserstein=0.00072953, logpq99=-79.511
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/realnvp_agnostic \
#     experiment_name=physics_realnvp_q99_pareto \
#     run_name=wasserstein_t253 \
#     algorithm.target_rate=0.01 \
#     algorithm.base_rate=null \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.flow.activation=relu \
#     algorithm.flow.hidden_dim=64 \
#     algorithm.flow.n_flows=8 \
#     algorithm.flow.n_hidden_layers=2 \
#     algorithm.flow.noise_scale=0.01 \
#     algorithm.flow.scale_clamp=5.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0014501294068329418 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[3]

# ------------------------------------------------------------------------
# trial 368: wasserstein=0.0018573, logpq99=-161.71
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/realnvp_agnostic \
#     experiment_name=physics_realnvp_q99_pareto \
#     run_name=wasserstein_t368 \
#     algorithm.target_rate=0.01 \
#     algorithm.base_rate=null \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.flow.activation=relu \
#     algorithm.flow.hidden_dim=64 \
#     algorithm.flow.n_flows=8 \
#     algorithm.flow.n_hidden_layers=2 \
#     algorithm.flow.noise_scale=0.0001 \
#     algorithm.flow.scale_clamp=5.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0006412081263630465 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 448: wasserstein=0.0013593, logpq99=-153.89
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/realnvp_agnostic \
#     experiment_name=physics_realnvp_q99_pareto \
#     run_name=wasserstein_t448 \
#     algorithm.target_rate=0.01 \
#     algorithm.base_rate=null \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.flow.activation=relu \
#     algorithm.flow.hidden_dim=64 \
#     algorithm.flow.n_flows=8 \
#     algorithm.flow.n_hidden_layers=2 \
#     algorithm.flow.noise_scale=0.0001 \
#     algorithm.flow.scale_clamp=5.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.000718605220305433 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 498: wasserstein=0.0025287, logpq99=-162.02
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/realnvp_agnostic \
#     experiment_name=physics_realnvp_q99_pareto \
#     run_name=wasserstein_t498 \
#     algorithm.target_rate=0.01 \
#     algorithm.base_rate=null \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.flow.activation=relu \
#     algorithm.flow.hidden_dim=64 \
#     algorithm.flow.n_flows=8 \
#     algorithm.flow.n_hidden_layers=2 \
#     algorithm.flow.noise_scale=0.0001 \
#     algorithm.flow.scale_clamp=5.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0007076247389485985 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 580: wasserstein=0.0013962, logpq99=-160.19  << ORIGINAL PICK | KNEE
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/realnvp_agnostic \
#     experiment_name=physics_realnvp_q99_pareto \
#     run_name=wasserstein_t580 \
#     algorithm.target_rate=0.01 \
#     algorithm.base_rate=null \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.flow.activation=relu \
#     algorithm.flow.hidden_dim=64 \
#     algorithm.flow.n_flows=8 \
#     algorithm.flow.n_hidden_layers=2 \
#     algorithm.flow.noise_scale=0.0001 \
#     algorithm.flow.scale_clamp=5.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0007229552409929307 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[3]
