# ========================================================================
# SVDD PARETO-FRONT TRAINING COMMANDS
# ========================================================================
# These are the training commands for every point on the Pareto front of
# each validation strategy. Generated by scripts/make_pareto_scripts.py from
# notebooks/paretos/physics/ -- regenerate rather than edit by hand.
#
# Run from the repository root. All commands are commented out -- uncomment
# the points you want to run. Device / taskset assignments cycle over the
# four GPUs.

# ========================================================================
# CVAR25 TRAINING  (study: cvar25eff_vs_dist, 9 Pareto points)
# ========================================================================
# ------------------------------------------------------------------------
# trial 175: cvar25eff=1.5185, dist=4.9029e-10
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/svdd \
#     experiment_name=physics_svdd_pareto \
#     run_name=cvar25_t175 \
#     algorithm.center_init_method=zeros \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.nodes='[64,32,16]' \
#     algorithm.nu=0.01 \
#     algorithm.soft_boundary=True \
#     algorithm.weight_decay=1e-08 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0011837945587210236 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 230: cvar25eff=992.1, dist=3.4338e-09
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/svdd \
#     experiment_name=physics_svdd_pareto \
#     run_name=cvar25_t230 \
#     algorithm.center_init_method=zeros \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.nodes='[48,24,8]' \
#     algorithm.nu=0.01 \
#     algorithm.soft_boundary=True \
#     algorithm.weight_decay=1e-08 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.002667613729012032 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 365: cvar25eff=999.9, dist=4.371e-09
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/svdd \
#     experiment_name=physics_svdd_pareto \
#     run_name=cvar25_t365 \
#     algorithm.center_init_method=zeros \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.nodes='[64,32,24]' \
#     algorithm.nu=0.01 \
#     algorithm.soft_boundary=True \
#     algorithm.weight_decay=0.0 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.002592614046882389 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 447: cvar25eff=999.95, dist=4.9135e-09
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/svdd \
#     experiment_name=physics_svdd_pareto \
#     run_name=cvar25_t447 \
#     algorithm.center_init_method=zeros \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.nodes='[48,24,8]' \
#     algorithm.nu=0.01 \
#     algorithm.soft_boundary=True \
#     algorithm.weight_decay=0.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.002719149135605468 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=2.0 \
#     trainer=gpu \
#     trainer.devices=[3]

# ------------------------------------------------------------------------
# trial 518: cvar25eff=999.99, dist=7.8759e-09
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/svdd \
#     experiment_name=physics_svdd_pareto \
#     run_name=cvar25_t518 \
#     algorithm.center_init_method=zeros \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.nodes='[24,8]' \
#     algorithm.nu=0.01 \
#     algorithm.soft_boundary=True \
#     algorithm.weight_decay=1e-05 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.002570590115255978 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=1.0 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 563: cvar25eff=999.99, dist=5.4063e-09
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/svdd \
#     experiment_name=physics_svdd_pareto \
#     run_name=cvar25_t563 \
#     algorithm.center_init_method=zeros \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.nodes='[48,24,8]' \
#     algorithm.nu=0.05 \
#     algorithm.soft_boundary=True \
#     algorithm.weight_decay=1e-05 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0025807654905732128 \
#     algorithm.optimizer.weight_decay=0.001 \
#     trainer.gradient_clip_val=2.0 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 612: cvar25eff=999.99, dist=6.5463e-09
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/svdd \
#     experiment_name=physics_svdd_pareto \
#     run_name=cvar25_t612 \
#     algorithm.center_init_method=zeros \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.nodes='[48,24,8]' \
#     algorithm.nu=0.2 \
#     algorithm.soft_boundary=True \
#     algorithm.weight_decay=1e-05 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0025925553526115804 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 787: cvar25eff=1000, dist=1.6446e-08  << BEST cvar25eff
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/svdd \
#     experiment_name=physics_svdd_pareto \
#     run_name=cvar25_t787 \
#     algorithm.center_init_method=zeros \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.nodes='[24,8]' \
#     algorithm.nu=0.01 \
#     algorithm.soft_boundary=True \
#     algorithm.weight_decay=0.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0025678002749062283 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[3]

# ------------------------------------------------------------------------
# trial 874: cvar25eff=984.39, dist=5.3136e-10  << KNEE
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/svdd \
#     experiment_name=physics_svdd_pareto \
#     run_name=cvar25_t874 \
#     algorithm.center_init_method=zeros \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.nodes='[48,24,8]' \
#     algorithm.nu=0.01 \
#     algorithm.soft_boundary=True \
#     algorithm.weight_decay=0.0 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.002572692872861613 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=2.0 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 739: cvar25eff=2.5689, dist=3.809e-08  << ORIGINAL PICK (handpicked; no longer on the current front)
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/svdd \
#     experiment_name=physics_svdd_pareto \
#     run_name=cvar25_t739 \
#     algorithm.center_init_method=mean \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.nodes='[48,24,8]' \
#     algorithm.nu=0.01 \
#     algorithm.soft_boundary=False \
#     algorithm.weight_decay=1e-07 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0025808010156689754 \
#     algorithm.optimizer.weight_decay=0.001 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[1]

# ========================================================================
# CVAR10 TRAINING  (study: cvar10eff_vs_dist, 2 Pareto points)
# ========================================================================
# ------------------------------------------------------------------------
# trial 571: cvar10eff=1000, dist=0  << BEST cvar10eff
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/svdd \
#     experiment_name=physics_svdd_pareto \
#     run_name=cvar10_t571 \
#     evaluation.callbacks.anomaly_efficiency.cvar_summary=0.10 \
#     algorithm.center_init_method=mean \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.nodes='[32,16,8]' \
#     algorithm.nu=0.1 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.001087358459053696 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     algorithm.soft_boundary=True \
#     algorithm.weight_decay=1e-07 \
#     trainer.gradient_clip_val=2.0 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 576: cvar10eff=1000, dist=0
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/svdd \
#     experiment_name=physics_svdd_pareto \
#     run_name=cvar10_t576 \
#     evaluation.callbacks.anomaly_efficiency.cvar_summary=0.10 \
#     algorithm.center_init_method=mean \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.nodes='[32,16,8]' \
#     algorithm.nu=0.1 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0010769612501436406 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     algorithm.soft_boundary=True \
#     algorithm.weight_decay=1e-07 \
#     trainer.gradient_clip_val=2.0 \
#     trainer=gpu \
#     trainer.devices=[1]

# ========================================================================
# CAP TRAINING  (study: cap_vs_dist, 14 Pareto points)
# ========================================================================
# ------------------------------------------------------------------------
# trial 92: cap=-0.69275, dist=3.3488e-08
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/svdd_agnostic \
#     experiment_name=physics_svdd_pareto \
#     run_name=cap_t92 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.center_init_method=mean \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.nodes='[32,16,8]' \
#     algorithm.nu=0.1 \
#     algorithm.soft_boundary=True \
#     algorithm.weight_decay=1e-07 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=3.295490968930208e-05 \
#     algorithm.optimizer.weight_decay=0.001 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 266: cap=-0.54324, dist=1.4276e-07
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/svdd_agnostic \
#     experiment_name=physics_svdd_pareto \
#     run_name=cap_t266 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.center_init_method=mean \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.nodes='[48,16]' \
#     algorithm.nu=0.05 \
#     algorithm.soft_boundary=False \
#     algorithm.weight_decay=1e-07 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0019503782295804946 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=2.0 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 270: cap=-0.46907, dist=2.0744e-07
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/svdd_agnostic \
#     experiment_name=physics_svdd_pareto \
#     run_name=cap_t270 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.center_init_method=mean \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.nodes='[48,16]' \
#     algorithm.nu=0.05 \
#     algorithm.soft_boundary=False \
#     algorithm.weight_decay=1e-07 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0021350768178344157 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=2.0 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 288: cap=-0.1715, dist=4.8572e-07
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/svdd_agnostic \
#     experiment_name=physics_svdd_pareto \
#     run_name=cap_t288 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.center_init_method=mean \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.nodes='[32,16]' \
#     algorithm.nu=0.05 \
#     algorithm.soft_boundary=False \
#     algorithm.weight_decay=1e-07 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0016221914366880278 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=2.0 \
#     trainer=gpu \
#     trainer.devices=[3]

# ------------------------------------------------------------------------
# trial 289: cap=-0.5643, dist=1.3013e-07
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/svdd_agnostic \
#     experiment_name=physics_svdd_pareto \
#     run_name=cap_t289 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.center_init_method=mean \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.nodes='[32,16]' \
#     algorithm.nu=0.05 \
#     algorithm.soft_boundary=False \
#     algorithm.weight_decay=1e-07 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.001620101146790778 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=2.0 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 297: cap=-0.31616, dist=2.2994e-07  << KNEE
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/svdd_agnostic \
#     experiment_name=physics_svdd_pareto \
#     run_name=cap_t297 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.center_init_method=mean \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.nodes='[32,16]' \
#     algorithm.nu=0.05 \
#     algorithm.soft_boundary=False \
#     algorithm.weight_decay=1e-07 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0016163497212673703 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=2.0 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 353: cap=-0.15057, dist=4.9288e-07
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/svdd_agnostic \
#     experiment_name=physics_svdd_pareto \
#     run_name=cap_t353 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.center_init_method=mean \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.nodes='[32,16]' \
#     algorithm.nu=0.05 \
#     algorithm.soft_boundary=False \
#     algorithm.weight_decay=1e-07 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.001928880597880822 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=2.0 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 439: cap=-0.23373, dist=3.4572e-07
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/svdd_agnostic \
#     experiment_name=physics_svdd_pareto \
#     run_name=cap_t439 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.center_init_method=mean \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.nodes='[32,16]' \
#     algorithm.nu=0.05 \
#     algorithm.soft_boundary=False \
#     algorithm.weight_decay=1e-07 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0020925921195731256 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=2.0 \
#     trainer=gpu \
#     trainer.devices=[3]

# ------------------------------------------------------------------------
# trial 460: cap=-0.19635, dist=3.7974e-07
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/svdd_agnostic \
#     experiment_name=physics_svdd_pareto \
#     run_name=cap_t460 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.center_init_method=mean \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.nodes='[32,16]' \
#     algorithm.nu=0.05 \
#     algorithm.soft_boundary=False \
#     algorithm.weight_decay=1e-07 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0020885081104832135 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=2.0 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 462: cap=-0.69315, dist=1.0479e-09
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/svdd_agnostic \
#     experiment_name=physics_svdd_pareto \
#     run_name=cap_t462 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.center_init_method=mean \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.nodes='[24,8,4]' \
#     algorithm.nu=0.05 \
#     algorithm.soft_boundary=False \
#     algorithm.weight_decay=1e-07 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.002071565172949557 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=2.0 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 480: cap=-0.14241, dist=5.0275e-07
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/svdd_agnostic \
#     experiment_name=physics_svdd_pareto \
#     run_name=cap_t480 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.center_init_method=mean \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.nodes='[32,16]' \
#     algorithm.nu=0.05 \
#     algorithm.soft_boundary=False \
#     algorithm.weight_decay=1e-07 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.002156005400724992 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=2.0 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 536: cap=-0.18176, dist=4.4792e-07  << ORIGINAL PICK
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/svdd_agnostic \
#     experiment_name=physics_svdd_pareto \
#     run_name=cap_t536 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.center_init_method=mean \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.nodes='[32,16]' \
#     algorithm.nu=0.05 \
#     algorithm.soft_boundary=False \
#     algorithm.weight_decay=1e-07 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0016271866440343411 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=2.0 \
#     trainer=gpu \
#     trainer.devices=[3]

# ------------------------------------------------------------------------
# trial 568: cap=-0.68184, dist=1.1795e-07
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/svdd_agnostic \
#     experiment_name=physics_svdd_pareto \
#     run_name=cap_t568 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.center_init_method=mean \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.nodes='[24,16]' \
#     algorithm.nu=0.05 \
#     algorithm.soft_boundary=False \
#     algorithm.weight_decay=1e-07 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.001653414072510062 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=2.0 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 573: cap=-0.10344, dist=5.4723e-07  << BEST cap
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/svdd_agnostic \
#     experiment_name=physics_svdd_pareto \
#     run_name=cap_t573 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.center_init_method=mean \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.nodes='[32,16]' \
#     algorithm.nu=0.05 \
#     algorithm.soft_boundary=False \
#     algorithm.weight_decay=1e-08 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0021443044608126962 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=2.0 \
#     trainer=gpu \
#     trainer.devices=[1]

# ========================================================================
# STABILITY TRAINING  (study: drift_vs_dist, 4 Pareto points)
# ========================================================================
# ------------------------------------------------------------------------
# trial 2: drift=11.621, dist=0
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/svdd_agnostic \
#     experiment_name=physics_svdd_pareto \
#     run_name=stability_t2 \
#     callbacks.wasserstein_dist=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_SingleNeutrino_E-10-gun \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.center_init_method=mean \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.nodes='[32,16,8]' \
#     algorithm.nu=0.01 \
#     algorithm.soft_boundary=True \
#     algorithm.weight_decay=1e-06 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0009934888610093689 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 260: drift=0.40559, dist=1.7309e-09  << KNEE
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/svdd_agnostic \
#     experiment_name=physics_svdd_pareto \
#     run_name=stability_t260 \
#     callbacks.wasserstein_dist=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_SingleNeutrino_E-10-gun \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.center_init_method=mean \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.nodes='[32,16,8]' \
#     algorithm.nu=0.1 \
#     algorithm.soft_boundary=True \
#     algorithm.weight_decay=1e-05 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.001042126370005284 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=2.0 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 297: drift=0.25717, dist=2.7507e-09
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/svdd_agnostic \
#     experiment_name=physics_svdd_pareto \
#     run_name=stability_t297 \
#     callbacks.wasserstein_dist=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_SingleNeutrino_E-10-gun \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.center_init_method=mean \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.nodes='[32,16,8]' \
#     algorithm.nu=0.1 \
#     algorithm.soft_boundary=True \
#     algorithm.weight_decay=1e-05 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0010885973494313324 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=2.0 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 419: drift=0.013551, dist=2.8757e-09  << ORIGINAL PICK | BEST drift
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/svdd_agnostic \
#     experiment_name=physics_svdd_pareto \
#     run_name=stability_t419 \
#     callbacks.wasserstein_dist=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_SingleNeutrino_E-10-gun \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.center_init_method=mean \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.nodes='[32,16,8]' \
#     algorithm.nu=0.1 \
#     algorithm.soft_boundary=True \
#     algorithm.weight_decay=1e-05 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0009833375412439862 \
#     algorithm.optimizer.weight_decay=0.001 \
#     trainer.gradient_clip_val=2.0 \
#     trainer=gpu \
#     trainer.devices=[3]

# ========================================================================
# WASSERSTEIN TRAINING  (study: wasserstein_vs_dist, 1 Pareto points)
# ========================================================================
# ------------------------------------------------------------------------
# trial 545: wasserstein=6.0228e-13, dist=6.8239e-10  << ORIGINAL PICK | BEST wasserstein
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/svdd_agnostic \
#     experiment_name=physics_svdd_pareto \
#     run_name=wasserstein_t545 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.center_init_method=mean \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.nodes='[16,8]' \
#     algorithm.nu=0.1 \
#     algorithm.soft_boundary=True \
#     algorithm.weight_decay=1e-06 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.001983105654764409 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[0]
