# ========================================================================
# SVDD PARETO-FRONT TRAINING COMMANDS
# ========================================================================
# q99 background-rate study: training commands for every point on the Pareto front of
# each validation strategy. Generated by scripts/make_pareto_scripts.py from
# notebooks/paretos/physics/ -- regenerate rather than edit by hand.
#
# Run from the repository root. All commands are commented out -- uncomment
# the points you want to run. Device / taskset assignments cycle over the
# four GPUs.

# ========================================================================
# CVAR25 TRAINING  (study: cvar25eff_vs_distq99, 4 Pareto points)
# ========================================================================
# ------------------------------------------------------------------------
# trial 393: cvar25eff=1000, distq99=1.2523e-13  << BEST cvar25eff
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/svdd \
#     experiment_name=physics_svdd_q99_pareto \
#     run_name=cvar25_t393 \
#     algorithm.target_rate=0.01 \
#     algorithm.base_rate=null \
#     algorithm.center_init_method=mean \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.nodes='[24,8,4]' \
#     algorithm.nu=0.2 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.001190363850015101 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     algorithm.soft_boundary=True \
#     algorithm.weight_decay=1e-07 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 425: cvar25eff=976.51, distq99=1.5321e-14  << KNEE
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/svdd \
#     experiment_name=physics_svdd_q99_pareto \
#     run_name=cvar25_t425 \
#     algorithm.target_rate=0.01 \
#     algorithm.base_rate=null \
#     algorithm.center_init_method=mean \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.nodes='[24,8,4]' \
#     algorithm.nu=0.2 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.00125841092711957 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     algorithm.soft_boundary=True \
#     algorithm.weight_decay=1e-07 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 565: cvar25eff=1000, distq99=3.5749e-14
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/svdd \
#     experiment_name=physics_svdd_q99_pareto \
#     run_name=cvar25_t565 \
#     algorithm.target_rate=0.01 \
#     algorithm.base_rate=null \
#     algorithm.center_init_method=mean \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.nodes='[24,8,4]' \
#     algorithm.nu=0.2 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0012668871145509381 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     algorithm.soft_boundary=True \
#     algorithm.weight_decay=1e-07 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 573: cvar25eff=776.73, distq99=7.3275e-15
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/svdd \
#     experiment_name=physics_svdd_q99_pareto \
#     run_name=cvar25_t573 \
#     algorithm.target_rate=0.01 \
#     algorithm.base_rate=null \
#     algorithm.center_init_method=mean \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.nodes='[24,8,4]' \
#     algorithm.nu=0.2 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0012586576597311853 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     algorithm.soft_boundary=True \
#     algorithm.weight_decay=1e-07 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[3]

# ------------------------------------------------------------------------
# trial 465: cvar25eff=51.648, distq99=3.5038e-12  << ORIGINAL PICK (handpicked; no longer on the current front)
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/svdd \
#     experiment_name=physics_svdd_q99_pareto \
#     run_name=cvar25_t465 \
#     algorithm.target_rate=0.01 \
#     algorithm.base_rate=null \
#     algorithm.center_init_method=mean \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.nodes='[16,8]' \
#     algorithm.nu=0.2 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0011493007715406593 \
#     algorithm.optimizer.weight_decay=0.0001 \
#     algorithm.soft_boundary=True \
#     algorithm.weight_decay=1e-07 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[0]

# ========================================================================
# CAP TRAINING  (study: cap_vs_distq99, 31 Pareto points, trimmed to 11 around the knee (endpoints kept))
# ========================================================================
# ------------------------------------------------------------------------
# trial 77: cap=-0.69314, distq99=2.2204e-16
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/svdd_agnostic \
#     experiment_name=physics_svdd_q99_pareto \
#     run_name=cap_t77 \
#     algorithm.target_rate=0.01 \
#     algorithm.base_rate=null \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.center_init_method=mean \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.nodes='[16,8]' \
#     algorithm.nu=0.01 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0008306313585049562 \
#     algorithm.optimizer.weight_decay=0.0 \
#     algorithm.soft_boundary=True \
#     algorithm.weight_decay=1e-08 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 169: cap=-0.21935, distq99=8.5974e-08
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/svdd_agnostic \
#     experiment_name=physics_svdd_q99_pareto \
#     run_name=cap_t169 \
#     algorithm.target_rate=0.01 \
#     algorithm.base_rate=null \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.center_init_method=zeros \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.nodes='[64,32,8]' \
#     algorithm.nu=0.01 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.001995296802628226 \
#     algorithm.optimizer.weight_decay=0.001 \
#     algorithm.soft_boundary=True \
#     algorithm.weight_decay=1e-07 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 232: cap=-0.11749, distq99=2.2046e-07  << KNEE
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/svdd_agnostic \
#     experiment_name=physics_svdd_q99_pareto \
#     run_name=cap_t232 \
#     algorithm.target_rate=0.01 \
#     algorithm.base_rate=null \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.center_init_method=zeros \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.nodes='[64,32,8]' \
#     algorithm.nu=0.01 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0016579250214218497 \
#     algorithm.optimizer.weight_decay=0.001 \
#     algorithm.soft_boundary=True \
#     algorithm.weight_decay=1e-07 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 284: cap=-0.10242, distq99=7.7931e-07
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/svdd_agnostic \
#     experiment_name=physics_svdd_q99_pareto \
#     run_name=cap_t284 \
#     algorithm.target_rate=0.01 \
#     algorithm.base_rate=null \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.center_init_method=zeros \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.nodes='[48,24,24]' \
#     algorithm.nu=0.01 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0019461054026542809 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     algorithm.soft_boundary=True \
#     algorithm.weight_decay=1e-07 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[3]

# ------------------------------------------------------------------------
# trial 338: cap=-0.20612, distq99=1.0689e-07
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/svdd_agnostic \
#     experiment_name=physics_svdd_q99_pareto \
#     run_name=cap_t338 \
#     algorithm.target_rate=0.01 \
#     algorithm.base_rate=null \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.center_init_method=zeros \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.nodes='[64,32,8]' \
#     algorithm.nu=0.01 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0016893172049139637 \
#     algorithm.optimizer.weight_decay=0.001 \
#     algorithm.soft_boundary=True \
#     algorithm.weight_decay=1e-07 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 403: cap=-0.16426, distq99=1.8553e-07
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/svdd_agnostic \
#     experiment_name=physics_svdd_q99_pareto \
#     run_name=cap_t403 \
#     algorithm.target_rate=0.01 \
#     algorithm.base_rate=null \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.center_init_method=zeros \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.nodes='[64,32,8]' \
#     algorithm.nu=0.01 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0016780395371884798 \
#     algorithm.optimizer.weight_decay=0.001 \
#     algorithm.soft_boundary=True \
#     algorithm.weight_decay=1e-07 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 449: cap=-0.16457, distq99=1.5054e-07
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/svdd_agnostic \
#     experiment_name=physics_svdd_q99_pareto \
#     run_name=cap_t449 \
#     algorithm.target_rate=0.01 \
#     algorithm.base_rate=null \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.center_init_method=zeros \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.nodes='[64,32,8]' \
#     algorithm.nu=0.01 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0017540888736492831 \
#     algorithm.optimizer.weight_decay=0.0 \
#     algorithm.soft_boundary=True \
#     algorithm.weight_decay=1e-07 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 570: cap=-0.099293, distq99=1.7508e-06
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/svdd_agnostic \
#     experiment_name=physics_svdd_q99_pareto \
#     run_name=cap_t570 \
#     algorithm.target_rate=0.01 \
#     algorithm.base_rate=null \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.center_init_method=zeros \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.nodes='[48,24,24]' \
#     algorithm.nu=0.01 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0019486850634503731 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     algorithm.soft_boundary=True \
#     algorithm.weight_decay=1e-07 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[3]

# ------------------------------------------------------------------------
# trial 575: cap=-0.096351, distq99=2.5662e-06
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/svdd_agnostic \
#     experiment_name=physics_svdd_q99_pareto \
#     run_name=cap_t575 \
#     algorithm.target_rate=0.01 \
#     algorithm.base_rate=null \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.center_init_method=zeros \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.nodes='[48,24,24]' \
#     algorithm.nu=0.01 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0018870737502939628 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     algorithm.soft_boundary=True \
#     algorithm.weight_decay=1e-07 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 597: cap=-0.094684, distq99=5.4154e-06  << BEST cap
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/svdd_agnostic \
#     experiment_name=physics_svdd_q99_pareto \
#     run_name=cap_t597 \
#     algorithm.target_rate=0.01 \
#     algorithm.base_rate=null \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.center_init_method=zeros \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.nodes='[48,24,24]' \
#     algorithm.nu=0.01 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0017235665263425628 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     algorithm.soft_boundary=True \
#     algorithm.weight_decay=1e-07 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 598: cap=-0.14438, distq99=1.9035e-07  << ORIGINAL PICK
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/svdd_agnostic \
#     experiment_name=physics_svdd_q99_pareto \
#     run_name=cap_t598 \
#     algorithm.target_rate=0.01 \
#     algorithm.base_rate=null \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.center_init_method=zeros \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.nodes='[48,24,24]' \
#     algorithm.nu=0.01 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0019670315274035116 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     algorithm.soft_boundary=True \
#     algorithm.weight_decay=1e-07 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[2]

# ========================================================================
# STABILITY TRAINING  (study: drift_vs_distq99, 12 Pareto points)
# ========================================================================
# ------------------------------------------------------------------------
# trial 204: drift=0.0044821, distq99=1.7254e-12
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/svdd_agnostic \
#     experiment_name=physics_svdd_q99_pareto \
#     run_name=stability_t204 \
#     algorithm.target_rate=0.01 \
#     algorithm.base_rate=null \
#     callbacks.wasserstein_dist=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_SingleNeutrino_E-10-gun \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.center_init_method=mean \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.nodes='[24,8]' \
#     algorithm.nu=0.01 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=4.267378132459436e-05 \
#     algorithm.optimizer.weight_decay=0.0 \
#     algorithm.soft_boundary=False \
#     algorithm.weight_decay=1e-06 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 240: drift=0.00066189, distq99=4.6587e-12
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/svdd_agnostic \
#     experiment_name=physics_svdd_q99_pareto \
#     run_name=stability_t240 \
#     algorithm.target_rate=0.01 \
#     algorithm.base_rate=null \
#     callbacks.wasserstein_dist=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_SingleNeutrino_E-10-gun \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.center_init_method=mean \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.nodes='[24,8]' \
#     algorithm.nu=0.05 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=4.44613577893144e-05 \
#     algorithm.optimizer.weight_decay=0.0 \
#     algorithm.soft_boundary=False \
#     algorithm.weight_decay=1e-06 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 286: drift=0.00034332, distq99=5.7949e-12  << KNEE
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/svdd_agnostic \
#     experiment_name=physics_svdd_q99_pareto \
#     run_name=stability_t286 \
#     algorithm.target_rate=0.01 \
#     algorithm.base_rate=null \
#     callbacks.wasserstein_dist=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_SingleNeutrino_E-10-gun \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.center_init_method=mean \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.nodes='[24,8]' \
#     algorithm.nu=0.05 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=3.0045988779347382e-05 \
#     algorithm.optimizer.weight_decay=0.0 \
#     algorithm.soft_boundary=False \
#     algorithm.weight_decay=1e-08 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 328: drift=8.1388e-06, distq99=2.3758e-10  << BEST drift
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/svdd_agnostic \
#     experiment_name=physics_svdd_q99_pareto \
#     run_name=stability_t328 \
#     algorithm.target_rate=0.01 \
#     algorithm.base_rate=null \
#     callbacks.wasserstein_dist=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_SingleNeutrino_E-10-gun \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.center_init_method=mean \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.nodes='[48,16]' \
#     algorithm.nu=0.05 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=3.607350958280863e-05 \
#     algorithm.optimizer.weight_decay=0.0 \
#     algorithm.soft_boundary=False \
#     algorithm.weight_decay=1e-08 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[3]

# ------------------------------------------------------------------------
# trial 338: drift=0.00015178, distq99=1.4693e-10
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/svdd_agnostic \
#     experiment_name=physics_svdd_q99_pareto \
#     run_name=stability_t338 \
#     algorithm.target_rate=0.01 \
#     algorithm.base_rate=null \
#     callbacks.wasserstein_dist=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_SingleNeutrino_E-10-gun \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.center_init_method=mean \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.nodes='[24,8,8]' \
#     algorithm.nu=0.05 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=4.173197622096486e-05 \
#     algorithm.optimizer.weight_decay=0.0 \
#     algorithm.soft_boundary=False \
#     algorithm.weight_decay=1e-06 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 377: drift=0.011842, distq99=9.7345e-13
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/svdd_agnostic \
#     experiment_name=physics_svdd_q99_pareto \
#     run_name=stability_t377 \
#     algorithm.target_rate=0.01 \
#     algorithm.base_rate=null \
#     callbacks.wasserstein_dist=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_SingleNeutrino_E-10-gun \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.center_init_method=mean \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.nodes='[24,8]' \
#     algorithm.nu=0.05 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=4.5877087275280435e-05 \
#     algorithm.optimizer.weight_decay=0.0 \
#     algorithm.soft_boundary=False \
#     algorithm.weight_decay=1e-06 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 412: drift=0.00024755, distq99=5.6426e-11
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/svdd_agnostic \
#     experiment_name=physics_svdd_q99_pareto \
#     run_name=stability_t412 \
#     algorithm.target_rate=0.01 \
#     algorithm.base_rate=null \
#     callbacks.wasserstein_dist=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_SingleNeutrino_E-10-gun \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.center_init_method=mean \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.nodes='[32,16]' \
#     algorithm.nu=0.05 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=4.158837045912069e-05 \
#     algorithm.optimizer.weight_decay=0.0 \
#     algorithm.soft_boundary=False \
#     algorithm.weight_decay=1e-06 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 475: drift=0.017927, distq99=5.1211e-13
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/svdd_agnostic \
#     experiment_name=physics_svdd_q99_pareto \
#     run_name=stability_t475 \
#     algorithm.target_rate=0.01 \
#     algorithm.base_rate=null \
#     callbacks.wasserstein_dist=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_SingleNeutrino_E-10-gun \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.center_init_method=mean \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.nodes='[24,8]' \
#     algorithm.nu=0.05 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=4.586642903693423e-05 \
#     algorithm.optimizer.weight_decay=0.0 \
#     algorithm.soft_boundary=False \
#     algorithm.weight_decay=1e-06 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[3]

# ------------------------------------------------------------------------
# trial 516: drift=0.0037669, distq99=2.4664e-12
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/svdd_agnostic \
#     experiment_name=physics_svdd_q99_pareto \
#     run_name=stability_t516 \
#     algorithm.target_rate=0.01 \
#     algorithm.base_rate=null \
#     callbacks.wasserstein_dist=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_SingleNeutrino_E-10-gun \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.center_init_method=mean \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.nodes='[24,8]' \
#     algorithm.nu=0.05 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=4.6525552416708994e-05 \
#     algorithm.optimizer.weight_decay=0.0 \
#     algorithm.soft_boundary=False \
#     algorithm.weight_decay=1e-06 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 520: drift=0.011369, distq99=1.1498e-12
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/svdd_agnostic \
#     experiment_name=physics_svdd_q99_pareto \
#     run_name=stability_t520 \
#     algorithm.target_rate=0.01 \
#     algorithm.base_rate=null \
#     callbacks.wasserstein_dist=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_SingleNeutrino_E-10-gun \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.center_init_method=mean \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.nodes='[24,8]' \
#     algorithm.nu=0.05 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=4.5806056769162696e-05 \
#     algorithm.optimizer.weight_decay=0.0 \
#     algorithm.soft_boundary=False \
#     algorithm.weight_decay=1e-06 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 555: drift=0.00032693, distq99=2.4412e-11
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/svdd_agnostic \
#     experiment_name=physics_svdd_q99_pareto \
#     run_name=stability_t555 \
#     algorithm.target_rate=0.01 \
#     algorithm.base_rate=null \
#     callbacks.wasserstein_dist=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_SingleNeutrino_E-10-gun \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.center_init_method=mean \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.nodes='[24,8]' \
#     algorithm.nu=0.05 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=4.2453581654427377e-05 \
#     algorithm.optimizer.weight_decay=0.0 \
#     algorithm.soft_boundary=False \
#     algorithm.weight_decay=1e-06 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 587: drift=0.0020006, distq99=3.3847e-12  << ORIGINAL PICK
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/svdd_agnostic \
#     experiment_name=physics_svdd_q99_pareto \
#     run_name=stability_t587 \
#     algorithm.target_rate=0.01 \
#     algorithm.base_rate=null \
#     callbacks.wasserstein_dist=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_SingleNeutrino_E-10-gun \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.center_init_method=mean \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.nodes='[24,8]' \
#     algorithm.nu=0.05 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=4.6219023315298896e-05 \
#     algorithm.optimizer.weight_decay=0.0 \
#     algorithm.soft_boundary=False \
#     algorithm.weight_decay=1e-06 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[3]

# ========================================================================
# WASSERSTEIN TRAINING  (study: wasserstein_vs_distq99, 5 Pareto points)
# ========================================================================
# ------------------------------------------------------------------------
# trial 113: wasserstein=5.5623e-09, distq99=1.8804e-15
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/svdd_agnostic \
#     experiment_name=physics_svdd_q99_pareto \
#     run_name=wasserstein_t113 \
#     algorithm.target_rate=0.01 \
#     algorithm.base_rate=null \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.center_init_method=zeros \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.nodes='[32,8]' \
#     algorithm.nu=0.05 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0022237475776075333 \
#     algorithm.optimizer.weight_decay=1e-06 \
#     algorithm.soft_boundary=True \
#     algorithm.weight_decay=1e-06 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 162: wasserstein=1.7094e-12, distq99=2.2235e-12  << KNEE
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/svdd_agnostic \
#     experiment_name=physics_svdd_q99_pareto \
#     run_name=wasserstein_t162 \
#     algorithm.target_rate=0.01 \
#     algorithm.base_rate=null \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.center_init_method=mean \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.nodes='[48,24,8]' \
#     algorithm.nu=0.01 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0013672149816131947 \
#     algorithm.optimizer.weight_decay=0.0 \
#     algorithm.soft_boundary=True \
#     algorithm.weight_decay=1e-06 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 319: wasserstein=0, distq99=1.5282e-09  << BEST wasserstein
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/svdd_agnostic \
#     experiment_name=physics_svdd_q99_pareto \
#     run_name=wasserstein_t319 \
#     algorithm.target_rate=0.01 \
#     algorithm.base_rate=null \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.center_init_method=mean \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.nodes='[32,16,8]' \
#     algorithm.nu=0.01 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0012848777522330886 \
#     algorithm.optimizer.weight_decay=1e-06 \
#     algorithm.soft_boundary=True \
#     algorithm.weight_decay=1e-07 \
#     trainer.gradient_clip_val=1.0 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 322: wasserstein=1.0463e-18, distq99=1.4505e-09
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/svdd_agnostic \
#     experiment_name=physics_svdd_q99_pareto \
#     run_name=wasserstein_t322 \
#     algorithm.target_rate=0.01 \
#     algorithm.base_rate=null \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.center_init_method=mean \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.nodes='[32,16,8]' \
#     algorithm.nu=0.01 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0013948028088934907 \
#     algorithm.optimizer.weight_decay=1e-06 \
#     algorithm.soft_boundary=True \
#     algorithm.weight_decay=1e-07 \
#     trainer.gradient_clip_val=1.0 \
#     trainer=gpu \
#     trainer.devices=[3]

# ------------------------------------------------------------------------
# trial 464: wasserstein=6.6013e-11, distq99=1.533e-12  << ORIGINAL PICK
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/svdd_agnostic \
#     experiment_name=physics_svdd_q99_pareto \
#     run_name=wasserstein_t464 \
#     algorithm.target_rate=0.01 \
#     algorithm.base_rate=null \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.center_init_method=mean \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.nodes='[32,16,8]' \
#     algorithm.nu=0.01 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=7.504046703635279e-05 \
#     algorithm.optimizer.weight_decay=1e-06 \
#     algorithm.soft_boundary=True \
#     algorithm.weight_decay=1e-07 \
#     trainer.gradient_clip_val=1.0 \
#     trainer=gpu \
#     trainer.devices=[0]
