# ========================================================================
# VAE PARETO-FRONT TRAINING COMMANDS
# ========================================================================
# These are the training commands for every point on the Pareto front of
# each validation strategy. Generated by scripts/make_pareto_scripts.py from
# notebooks/paretos/physics/ -- regenerate rather than edit by hand.
#
# Run from the repository root. All commands are commented out -- uncomment
# the points you want to run. Device / taskset assignments cycle over the
# four GPUs.

# ========================================================================
# CVAR25 TRAINING  (study: cvar25eff_vs_kl_b16k, 13 Pareto points)
# ========================================================================
# ------------------------------------------------------------------------
# trial 45: cvar25eff=0.51126, kl=14.502
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/vae \
#     experiment_name=physics_vae_pareto \
#     run_name=cvar25_t45 \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.clamp_zlogvar_range='[-20,10]' \
#     algorithm.encoder.nodes='[32,16,16]' \
#     algorithm.kl_warmup_frac=0.05 \
#     algorithm.kl_scale=0.002 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=6.435948933915592e-05 \
#     algorithm.optimizer.weight_decay=1e-06 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 173: cvar25eff=0.71131, kl=40.692
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/vae \
#     experiment_name=physics_vae_pareto \
#     run_name=cvar25_t173 \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.clamp_zlogvar_range='[-20,10]' \
#     algorithm.encoder.nodes='[48,24,16]' \
#     algorithm.kl_warmup_frac=0.0 \
#     algorithm.kl_scale=0.002 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0009911308657120426 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 221: cvar25eff=0.62818, kl=15.715
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/vae \
#     experiment_name=physics_vae_pareto \
#     run_name=cvar25_t221 \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.clamp_zlogvar_range='[-20,10]' \
#     algorithm.encoder.nodes='[24,8,4]' \
#     algorithm.kl_warmup_frac=0.0 \
#     algorithm.kl_scale=0.002 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.00010351426144833387 \
#     algorithm.optimizer.weight_decay=1e-06 \
#     trainer.gradient_clip_val=2.0 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 345: cvar25eff=0.50349, kl=5.3899  << ORIGINAL PICK
#   caveat: old script had algorithm.optimizer.lr=5.236233832409967e-05; db trial 345 has 5.008239492340467e-05
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/vae \
#     experiment_name=physics_vae_pareto \
#     run_name=cvar25_t345 \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.clamp_zlogvar_range='[-20,10]' \
#     algorithm.encoder.nodes='[32,16,16]' \
#     algorithm.kl_warmup_frac=0.0 \
#     algorithm.kl_scale=0.002 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=5.008239492340467e-05 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[3]

# ------------------------------------------------------------------------
# trial 397: cvar25eff=0.65879, kl=39.974
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/vae \
#     experiment_name=physics_vae_pareto \
#     run_name=cvar25_t397 \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.clamp_zlogvar_range='[-20,10]' \
#     algorithm.encoder.nodes='[48,24,16]' \
#     algorithm.kl_warmup_frac=0.0 \
#     algorithm.kl_scale=0.002 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0009538066014516791 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 398: cvar25eff=0.65885, kl=40.125  << KNEE
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/vae \
#     experiment_name=physics_vae_pareto \
#     run_name=cvar25_t398 \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.clamp_zlogvar_range='[-20,10]' \
#     algorithm.encoder.nodes='[48,24,16]' \
#     algorithm.kl_warmup_frac=0.0 \
#     algorithm.kl_scale=0.002 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0009546091445164261 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 415: cvar25eff=0.69539, kl=40.387
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/vae \
#     experiment_name=physics_vae_pareto \
#     run_name=cvar25_t415 \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.clamp_zlogvar_range='[-20,10]' \
#     algorithm.encoder.nodes='[48,24,16]' \
#     algorithm.kl_warmup_frac=0.0 \
#     algorithm.kl_scale=0.002 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0009926531324521322 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 513: cvar25eff=0.93864, kl=45.644  << BEST cvar25eff
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/vae \
#     experiment_name=physics_vae_pareto \
#     run_name=cvar25_t513 \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.clamp_zlogvar_range='[-20,10]' \
#     algorithm.encoder.nodes='[48,24,8]' \
#     algorithm.kl_warmup_frac=0.0 \
#     algorithm.kl_scale=0.002 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0009593961598492453 \
#     algorithm.optimizer.weight_decay=1e-06 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[3]

# ------------------------------------------------------------------------
# trial 535: cvar25eff=0.8041, kl=41.838
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/vae \
#     experiment_name=physics_vae_pareto \
#     run_name=cvar25_t535 \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.clamp_zlogvar_range='[-8,6]' \
#     algorithm.encoder.nodes='[48,24,8]' \
#     algorithm.kl_warmup_frac=0.0 \
#     algorithm.kl_scale=0.002 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0009544474275946093 \
#     algorithm.optimizer.weight_decay=1e-06 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 578: cvar25eff=0.87408, kl=42.003
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/vae \
#     experiment_name=physics_vae_pareto \
#     run_name=cvar25_t578 \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.clamp_zlogvar_range='[-8,6]' \
#     algorithm.encoder.nodes='[48,24,8]' \
#     algorithm.kl_warmup_frac=0.0 \
#     algorithm.kl_scale=0.002 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0009520924346900142 \
#     algorithm.optimizer.weight_decay=1e-06 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 587: cvar25eff=0.92214, kl=44.828
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/vae \
#     experiment_name=physics_vae_pareto \
#     run_name=cvar25_t587 \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.clamp_zlogvar_range='[-8,6]' \
#     algorithm.encoder.nodes='[48,24,8]' \
#     algorithm.kl_warmup_frac=0.0 \
#     algorithm.kl_scale=0.002 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0009319615732323362 \
#     algorithm.optimizer.weight_decay=1e-06 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 588: cvar25eff=0.93222, kl=45.577
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/vae \
#     experiment_name=physics_vae_pareto \
#     run_name=cvar25_t588 \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.clamp_zlogvar_range='[-8,6]' \
#     algorithm.encoder.nodes='[48,24,8]' \
#     algorithm.kl_warmup_frac=0.0 \
#     algorithm.kl_scale=0.002 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0009316486401141324 \
#     algorithm.optimizer.weight_decay=1e-06 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[3]

# ------------------------------------------------------------------------
# trial 595: cvar25eff=0.90869, kl=44.655
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/vae \
#     experiment_name=physics_vae_pareto \
#     run_name=cvar25_t595 \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.clamp_zlogvar_range='[-8,6]' \
#     algorithm.encoder.nodes='[48,24,8]' \
#     algorithm.kl_warmup_frac=0.0 \
#     algorithm.kl_scale=0.002 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0009240229337198204 \
#     algorithm.optimizer.weight_decay=1e-06 \
#     trainer.gradient_clip_val=0.0 \
#     trainer=gpu \
#     trainer.devices=[0]

# ========================================================================
# CVAR10 TRAINING  (study: cvar10eff_vs_kl_b16k, 14 Pareto points)
# ========================================================================
# ------------------------------------------------------------------------
# trial 108: cvar10eff=0.12507, kl=45.485
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/vae \
#     experiment_name=physics_vae_pareto \
#     run_name=cvar10_t108 \
#     evaluation.callbacks.anomaly_efficiency.cvar_summary=0.10 \
#     algorithm.encoder.activation=silu \
#     algorithm.encoder.clamp_zlogvar_range='[-6,4]' \
#     algorithm.encoder.nodes='[48,24,8]' \
#     algorithm.kl_warmup_frac=0.0 \
#     algorithm.kl_scale=0.002 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0006969816072606508 \
#     algorithm.optimizer.weight_decay=1e-06 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 135: cvar10eff=0.17504, kl=81.534
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/vae \
#     experiment_name=physics_vae_pareto \
#     run_name=cvar10_t135 \
#     evaluation.callbacks.anomaly_efficiency.cvar_summary=0.10 \
#     algorithm.encoder.activation=silu \
#     algorithm.encoder.clamp_zlogvar_range='[-10,6]' \
#     algorithm.encoder.nodes='[24,4]' \
#     algorithm.kl_warmup_frac=0.3 \
#     algorithm.kl_scale=0.002 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.00024640350120670165 \
#     algorithm.optimizer.weight_decay=0.001 \
#     trainer.gradient_clip_val=1.0 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 211: cvar10eff=0.18337, kl=86.848  << KNEE
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/vae \
#     experiment_name=physics_vae_pareto \
#     run_name=cvar10_t211 \
#     evaluation.callbacks.anomaly_efficiency.cvar_summary=0.10 \
#     algorithm.encoder.activation=silu \
#     algorithm.encoder.clamp_zlogvar_range='[-10,6]' \
#     algorithm.encoder.nodes='[24,4]' \
#     algorithm.kl_warmup_frac=0.3 \
#     algorithm.kl_scale=0.002 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.00020279226014686453 \
#     algorithm.optimizer.weight_decay=0.001 \
#     trainer.gradient_clip_val=1.0 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 242: cvar10eff=0.23499, kl=318.28  << BEST cvar10eff
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/vae \
#     experiment_name=physics_vae_pareto \
#     run_name=cvar10_t242 \
#     evaluation.callbacks.anomaly_efficiency.cvar_summary=0.10 \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.clamp_zlogvar_range='[-10,6]' \
#     algorithm.encoder.nodes='[24,8,4]' \
#     algorithm.kl_warmup_frac=0.3 \
#     algorithm.kl_scale=3e-05 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0002867376596445716 \
#     algorithm.optimizer.weight_decay=1e-06 \
#     trainer.gradient_clip_val=2.0 \
#     trainer=gpu \
#     trainer.devices=[3]

# ------------------------------------------------------------------------
# trial 245: cvar10eff=0.23193, kl=310.38
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/vae \
#     experiment_name=physics_vae_pareto \
#     run_name=cvar10_t245 \
#     evaluation.callbacks.anomaly_efficiency.cvar_summary=0.10 \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.clamp_zlogvar_range='[-10,6]' \
#     algorithm.encoder.nodes='[24,8,4]' \
#     algorithm.kl_warmup_frac=0.3 \
#     algorithm.kl_scale=3e-05 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.00028246362588099525 \
#     algorithm.optimizer.weight_decay=1e-06 \
#     trainer.gradient_clip_val=2.0 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 294: cvar10eff=0.1667, kl=73.761
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/vae \
#     experiment_name=physics_vae_pareto \
#     run_name=cvar10_t294 \
#     evaluation.callbacks.anomaly_efficiency.cvar_summary=0.10 \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.clamp_zlogvar_range='[-10,6]' \
#     algorithm.encoder.nodes='[24,8,4]' \
#     algorithm.kl_warmup_frac=0.3 \
#     algorithm.kl_scale=0.002 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.00099902130194465 \
#     algorithm.optimizer.weight_decay=1e-06 \
#     trainer.gradient_clip_val=1.0 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 366: cvar10eff=0.21057, kl=208.06
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/vae \
#     experiment_name=physics_vae_pareto \
#     run_name=cvar10_t366 \
#     evaluation.callbacks.anomaly_efficiency.cvar_summary=0.10 \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.clamp_zlogvar_range='[-8,6]' \
#     algorithm.encoder.nodes='[48,24,8]' \
#     algorithm.kl_warmup_frac=0.3 \
#     algorithm.kl_scale=3e-05 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.00029089099895892803 \
#     algorithm.optimizer.weight_decay=1e-06 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 367: cvar10eff=0.20004, kl=205.65
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/vae \
#     experiment_name=physics_vae_pareto \
#     run_name=cvar10_t367 \
#     evaluation.callbacks.anomaly_efficiency.cvar_summary=0.10 \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.clamp_zlogvar_range='[-8,6]' \
#     algorithm.encoder.nodes='[48,24,8]' \
#     algorithm.kl_warmup_frac=0.3 \
#     algorithm.kl_scale=3e-05 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.00029104163873416524 \
#     algorithm.optimizer.weight_decay=1e-06 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[3]

# ------------------------------------------------------------------------
# trial 380: cvar10eff=0.15792, kl=48.2
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/vae \
#     experiment_name=physics_vae_pareto \
#     run_name=cvar10_t380 \
#     evaluation.callbacks.anomaly_efficiency.cvar_summary=0.10 \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.clamp_zlogvar_range='[-6,4]' \
#     algorithm.encoder.nodes='[32,16,8]' \
#     algorithm.kl_warmup_frac=0.0 \
#     algorithm.kl_scale=0.002 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0006792528193134147 \
#     algorithm.optimizer.weight_decay=1e-06 \
#     trainer.gradient_clip_val=1.0 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 381: cvar10eff=0.16174, kl=50.304
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/vae \
#     experiment_name=physics_vae_pareto \
#     run_name=cvar10_t381 \
#     evaluation.callbacks.anomaly_efficiency.cvar_summary=0.10 \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.clamp_zlogvar_range='[-20,10]' \
#     algorithm.encoder.nodes='[32,16,8]' \
#     algorithm.kl_warmup_frac=0.0 \
#     algorithm.kl_scale=0.002 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0006840519906796113 \
#     algorithm.optimizer.weight_decay=1e-06 \
#     trainer.gradient_clip_val=1.0 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 382: cvar10eff=0.16479, kl=50.878
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/vae \
#     experiment_name=physics_vae_pareto \
#     run_name=cvar10_t382 \
#     evaluation.callbacks.anomaly_efficiency.cvar_summary=0.10 \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.clamp_zlogvar_range='[-20,10]' \
#     algorithm.encoder.nodes='[32,16,8]' \
#     algorithm.kl_warmup_frac=0.0 \
#     algorithm.kl_scale=0.002 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0006846341582642431 \
#     algorithm.optimizer.weight_decay=1e-06 \
#     trainer.gradient_clip_val=1.0 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 383: cvar10eff=0.16097, kl=48.506
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/vae \
#     experiment_name=physics_vae_pareto \
#     run_name=cvar10_t383 \
#     evaluation.callbacks.anomaly_efficiency.cvar_summary=0.10 \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.clamp_zlogvar_range='[-20,10]' \
#     algorithm.encoder.nodes='[32,16,8]' \
#     algorithm.kl_warmup_frac=0.0 \
#     algorithm.kl_scale=0.002 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0006834103176623972 \
#     algorithm.optimizer.weight_decay=1e-06 \
#     trainer.gradient_clip_val=1.0 \
#     trainer=gpu \
#     trainer.devices=[3]

# ------------------------------------------------------------------------
# trial 431: cvar10eff=0.21285, kl=298.56
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/vae \
#     experiment_name=physics_vae_pareto \
#     run_name=cvar10_t431 \
#     evaluation.callbacks.anomaly_efficiency.cvar_summary=0.10 \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.clamp_zlogvar_range='[-10,6]' \
#     algorithm.encoder.nodes='[24,8,4]' \
#     algorithm.kl_warmup_frac=0.3 \
#     algorithm.kl_scale=3e-05 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.00026844935615058367 \
#     algorithm.optimizer.weight_decay=1e-06 \
#     trainer.gradient_clip_val=2.0 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 525: cvar10eff=0.13428, kl=48.024
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/vae \
#     experiment_name=physics_vae_pareto \
#     run_name=cvar10_t525 \
#     evaluation.callbacks.anomaly_efficiency.cvar_summary=0.10 \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.clamp_zlogvar_range='[-6,4]' \
#     algorithm.encoder.nodes='[32,16,8]' \
#     algorithm.kl_warmup_frac=0.0 \
#     algorithm.kl_scale=0.002 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0006977153783281235 \
#     algorithm.optimizer.weight_decay=1e-06 \
#     trainer.gradient_clip_val=1.0 \
#     trainer=gpu \
#     trainer.devices=[1]

# ========================================================================
# CAP TRAINING  (study: cap_vs_kl_b16k, 13 Pareto points)
# ========================================================================
# ------------------------------------------------------------------------
# trial 123: cap=-0.14615, kl=13.822
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/vae_agnostic \
#     experiment_name=physics_vae_pareto \
#     run_name=cap_t123 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.encoder.activation=silu \
#     algorithm.encoder.clamp_zlogvar_range='[-20,10]' \
#     algorithm.encoder.nodes='[32,16,16]' \
#     algorithm.kl_warmup_frac=0.05 \
#     algorithm.kl_scale=0.002 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=7.215884081105373e-05 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=2.0 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 166: cap=-0.14607, kl=17.873
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/vae_agnostic \
#     experiment_name=physics_vae_pareto \
#     run_name=cap_t166 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.encoder.activation=silu \
#     algorithm.encoder.clamp_zlogvar_range='[-20,10]' \
#     algorithm.encoder.nodes='[32,16,16]' \
#     algorithm.kl_warmup_frac=0.05 \
#     algorithm.kl_scale=0.002 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=7.758014532488988e-05 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=2.0 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 167: cap=-0.14607, kl=17.923
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/vae_agnostic \
#     experiment_name=physics_vae_pareto \
#     run_name=cap_t167 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.encoder.activation=silu \
#     algorithm.encoder.clamp_zlogvar_range='[-20,10]' \
#     algorithm.encoder.nodes='[32,16,16]' \
#     algorithm.kl_warmup_frac=0.05 \
#     algorithm.kl_scale=0.002 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=7.764036438175236e-05 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=2.0 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 176: cap=-0.13218, kl=47.227  << BEST cap
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/vae_agnostic \
#     experiment_name=physics_vae_pareto \
#     run_name=cap_t176 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.clamp_zlogvar_range='[-8,6]' \
#     algorithm.encoder.nodes='[64,32,24]' \
#     algorithm.kl_warmup_frac=0.05 \
#     algorithm.kl_scale=0.002 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0006138362652284726 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=2.0 \
#     trainer=gpu \
#     trainer.devices=[3]

# ------------------------------------------------------------------------
# trial 177: cap=-0.13945, kl=45.444
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/vae_agnostic \
#     experiment_name=physics_vae_pareto \
#     run_name=cap_t177 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.clamp_zlogvar_range='[-8,6]' \
#     algorithm.encoder.nodes='[64,32,24]' \
#     algorithm.kl_warmup_frac=0.05 \
#     algorithm.kl_scale=0.002 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0006168342788398662 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=2.0 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 178: cap=-0.14687, kl=9.1628
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/vae_agnostic \
#     experiment_name=physics_vae_pareto \
#     run_name=cap_t178 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.encoder.activation=silu \
#     algorithm.encoder.clamp_zlogvar_range='[-20,10]' \
#     algorithm.encoder.nodes='[32,16,16]' \
#     algorithm.kl_warmup_frac=0.05 \
#     algorithm.kl_scale=0.002 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=6.382214252059709e-05 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=2.0 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 179: cap=-0.14691, kl=9.054  << ORIGINAL PICK
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/vae_agnostic \
#     experiment_name=physics_vae_pareto \
#     run_name=cap_t179 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.encoder.activation=silu \
#     algorithm.encoder.clamp_zlogvar_range='[-20,10]' \
#     algorithm.encoder.nodes='[32,16,16]' \
#     algorithm.kl_warmup_frac=0.05 \
#     algorithm.kl_scale=0.002 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=6.358827890772183e-05 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=2.0 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 180: cap=-0.14614, kl=14.093
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/vae_agnostic \
#     experiment_name=physics_vae_pareto \
#     run_name=cap_t180 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.encoder.activation=silu \
#     algorithm.encoder.clamp_zlogvar_range='[-20,10]' \
#     algorithm.encoder.nodes='[32,16,16]' \
#     algorithm.kl_warmup_frac=0.05 \
#     algorithm.kl_scale=0.002 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=7.256260359557088e-05 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=2.0 \
#     trainer=gpu \
#     trainer.devices=[3]

# ------------------------------------------------------------------------
# trial 181: cap=-0.14615, kl=13.709
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/vae_agnostic \
#     experiment_name=physics_vae_pareto \
#     run_name=cap_t181 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.encoder.activation=silu \
#     algorithm.encoder.clamp_zlogvar_range='[-20,10]' \
#     algorithm.encoder.nodes='[32,16,16]' \
#     algorithm.kl_warmup_frac=0.05 \
#     algorithm.kl_scale=0.002 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=7.198791214129244e-05 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=2.0 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 188: cap=-0.13612, kl=46.01
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/vae_agnostic \
#     experiment_name=physics_vae_pareto \
#     run_name=cap_t188 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.clamp_zlogvar_range='[-8,6]' \
#     algorithm.encoder.nodes='[64,32,24]' \
#     algorithm.kl_warmup_frac=0.05 \
#     algorithm.kl_scale=0.002 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0006111281096251776 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=2.0 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 295: cap=-0.1369, kl=45.772
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/vae_agnostic \
#     experiment_name=physics_vae_pareto \
#     run_name=cap_t295 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.clamp_zlogvar_range='[-8,6]' \
#     algorithm.encoder.nodes='[64,32,24]' \
#     algorithm.kl_warmup_frac=0.05 \
#     algorithm.kl_scale=0.002 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0006103595770851728 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=2.0 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 364: cap=-0.15459, kl=4.8439
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/vae_agnostic \
#     experiment_name=physics_vae_pareto \
#     run_name=cap_t364 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.clamp_zlogvar_range='[-8,6]' \
#     algorithm.encoder.nodes='[16,4]' \
#     algorithm.kl_warmup_frac=0.05 \
#     algorithm.kl_scale=0.002 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=6.874519645878375e-05 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=2.0 \
#     trainer=gpu \
#     trainer.devices=[3]

# ------------------------------------------------------------------------
# trial 584: cap=-0.14236, kl=41.292  << KNEE
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/vae_agnostic \
#     experiment_name=physics_vae_pareto \
#     run_name=cap_t584 \
#     callbacks.wasserstein_dist=null \
#     callbacks.thres_drift=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.clamp_zlogvar_range='[-8,6]' \
#     algorithm.encoder.nodes='[32,16,4]' \
#     algorithm.kl_warmup_frac=0.05 \
#     algorithm.kl_scale=0.002 \
#     algorithm.optimizer.betas='[0.9,0.999]' \
#     algorithm.optimizer.lr=0.0006166918590268315 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=2.0 \
#     trainer=gpu \
#     trainer.devices=[0]

# ========================================================================
# STABILITY TRAINING  (study: drift_vs_kl_b16k, 3 Pareto points)
# ========================================================================
# ------------------------------------------------------------------------
# trial 238: drift=0.25717, kl=13.774
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/vae_agnostic \
#     experiment_name=physics_vae_pareto \
#     run_name=stability_t238 \
#     callbacks.wasserstein_dist=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_SingleNeutrino_E-10-gun \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.clamp_zlogvar_range='[-8,6]' \
#     algorithm.encoder.nodes='[48,16,8]' \
#     algorithm.kl_warmup_frac=0.1 \
#     algorithm.kl_scale=0.0001 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=5.7721059347761214e-05 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=2.0 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 454: drift=0.013551, kl=45.227  << BEST drift
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/vae_agnostic \
#     experiment_name=physics_vae_pareto \
#     run_name=stability_t454 \
#     callbacks.wasserstein_dist=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_SingleNeutrino_E-10-gun \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.clamp_zlogvar_range='[-10,6]' \
#     algorithm.encoder.nodes='[48,16,8]' \
#     algorithm.kl_warmup_frac=0.0 \
#     algorithm.kl_scale=0.002 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0008423594125278336 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=2.0 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 529: drift=0.12796, kl=44.612  << ORIGINAL PICK | KNEE
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/vae_agnostic \
#     experiment_name=physics_vae_pareto \
#     run_name=stability_t529 \
#     callbacks.wasserstein_dist=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.wasserstein_dist_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.w1dist_ema_normal_vs_SingleNeutrino_E-10-gun \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.encoder.activation=gelu \
#     algorithm.encoder.clamp_zlogvar_range='[-10,6]' \
#     algorithm.encoder.nodes='[48,16,8]' \
#     algorithm.kl_warmup_frac=0.0 \
#     algorithm.kl_scale=0.002 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0008437643709861688 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=2.0 \
#     trainer=gpu \
#     trainer.devices=[2]

# ========================================================================
# WASSERSTEIN TRAINING  (study: wasserstein_vs_kl_b16k, 24 Pareto points)
# ========================================================================
# ------------------------------------------------------------------------
# trial 394: wasserstein=0.00064449, kl=138.01  << BEST wasserstein
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/vae_agnostic \
#     experiment_name=physics_vae_pareto \
#     run_name=wasserstein_t394 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.clamp_zlogvar_range='[-8,6]' \
#     algorithm.encoder.nodes='[24,8,4]' \
#     algorithm.kl_warmup_frac=0.2 \
#     algorithm.kl_scale=3e-05 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=0.0005669712185369004 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 427: wasserstein=0.00082546, kl=0.9662
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/vae_agnostic \
#     experiment_name=physics_vae_pareto \
#     run_name=wasserstein_t427 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.clamp_zlogvar_range='[-8,6]' \
#     algorithm.encoder.nodes='[24,8,4]' \
#     algorithm.kl_warmup_frac=0.2 \
#     algorithm.kl_scale=3e-05 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=5.8615085930070284e-05 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 428: wasserstein=0.00086012, kl=0.95604
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/vae_agnostic \
#     experiment_name=physics_vae_pareto \
#     run_name=wasserstein_t428 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.clamp_zlogvar_range='[-8,6]' \
#     algorithm.encoder.nodes='[24,8,4]' \
#     algorithm.kl_warmup_frac=0.2 \
#     algorithm.kl_scale=3e-05 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=5.8312640209952394e-05 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 429: wasserstein=0.00082634, kl=0.96592
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/vae_agnostic \
#     experiment_name=physics_vae_pareto \
#     run_name=wasserstein_t429 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.clamp_zlogvar_range='[-8,6]' \
#     algorithm.encoder.nodes='[24,8,4]' \
#     algorithm.kl_warmup_frac=0.2 \
#     algorithm.kl_scale=3e-05 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=5.860678308810372e-05 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[3]

# ------------------------------------------------------------------------
# trial 431: wasserstein=0.00085081, kl=0.95885
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/vae_agnostic \
#     experiment_name=physics_vae_pareto \
#     run_name=wasserstein_t431 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.clamp_zlogvar_range='[-8,6]' \
#     algorithm.encoder.nodes='[24,8,4]' \
#     algorithm.kl_warmup_frac=0.2 \
#     algorithm.kl_scale=3e-05 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=5.8397407874567905e-05 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 432: wasserstein=0.00080666, kl=0.97222
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/vae_agnostic \
#     experiment_name=physics_vae_pareto \
#     run_name=wasserstein_t432 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.clamp_zlogvar_range='[-8,6]' \
#     algorithm.encoder.nodes='[24,8,4]' \
#     algorithm.kl_warmup_frac=0.2 \
#     algorithm.kl_scale=3e-05 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=5.878569699878999e-05 \
#     algorithm.optimizer.weight_decay=1e-05 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 440: wasserstein=0.00070615, kl=0.99863
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/vae_agnostic \
#     experiment_name=physics_vae_pareto \
#     run_name=wasserstein_t440 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.clamp_zlogvar_range='[-10,6]' \
#     algorithm.encoder.nodes='[24,8,4]' \
#     algorithm.kl_warmup_frac=0.2 \
#     algorithm.kl_scale=0.002 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=5.958015185161453e-05 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 443: wasserstein=0.00067282, kl=1.0076
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/vae_agnostic \
#     experiment_name=physics_vae_pareto \
#     run_name=wasserstein_t443 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.clamp_zlogvar_range='[-10,6]' \
#     algorithm.encoder.nodes='[24,8,4]' \
#     algorithm.kl_warmup_frac=0.1 \
#     algorithm.kl_scale=0.002 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=5.988146214183658e-05 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[3]

# ------------------------------------------------------------------------
# trial 444: wasserstein=0.00066685, kl=1.0307
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/vae_agnostic \
#     experiment_name=physics_vae_pareto \
#     run_name=wasserstein_t444 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.clamp_zlogvar_range='[-10,6]' \
#     algorithm.encoder.nodes='[24,8,4]' \
#     algorithm.kl_warmup_frac=0.3 \
#     algorithm.kl_scale=0.002 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=6.046620826037219e-05 \
#     algorithm.optimizer.weight_decay=0.001 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 448: wasserstein=0.000666, kl=1.0355  << KNEE
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/vae_agnostic \
#     experiment_name=physics_vae_pareto \
#     run_name=wasserstein_t448 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.clamp_zlogvar_range='[-10,6]' \
#     algorithm.encoder.nodes='[24,8,4]' \
#     algorithm.kl_warmup_frac=0.2 \
#     algorithm.kl_scale=0.002 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=6.060652377051845e-05 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 471: wasserstein=0.00095658, kl=0.92382
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/vae_agnostic \
#     experiment_name=physics_vae_pareto \
#     run_name=wasserstein_t471 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.clamp_zlogvar_range='[-10,6]' \
#     algorithm.encoder.nodes='[24,8,4]' \
#     algorithm.kl_warmup_frac=0.3 \
#     algorithm.kl_scale=0.002 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=5.736993874688997e-05 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 472: wasserstein=0.00094331, kl=0.92783
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/vae_agnostic \
#     experiment_name=physics_vae_pareto \
#     run_name=wasserstein_t472 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.clamp_zlogvar_range='[-10,6]' \
#     algorithm.encoder.nodes='[24,8,4]' \
#     algorithm.kl_warmup_frac=0.3 \
#     algorithm.kl_scale=0.002 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=5.749172954620169e-05 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[3]

# ------------------------------------------------------------------------
# trial 473: wasserstein=0.00098595, kl=0.9151
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/vae_agnostic \
#     experiment_name=physics_vae_pareto \
#     run_name=wasserstein_t473 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.clamp_zlogvar_range='[-10,6]' \
#     algorithm.encoder.nodes='[24,8,4]' \
#     algorithm.kl_warmup_frac=0.3 \
#     algorithm.kl_scale=0.002 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=5.7099177037427195e-05 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 474: wasserstein=0.00094317, kl=0.92789
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/vae_agnostic \
#     experiment_name=physics_vae_pareto \
#     run_name=wasserstein_t474 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.clamp_zlogvar_range='[-10,6]' \
#     algorithm.encoder.nodes='[24,8,4]' \
#     algorithm.kl_warmup_frac=0.3 \
#     algorithm.kl_scale=0.002 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=5.7493403555614645e-05 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 475: wasserstein=0.000925, kl=0.9317
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/vae_agnostic \
#     experiment_name=physics_vae_pareto \
#     run_name=wasserstein_t475 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.clamp_zlogvar_range='[-10,6]' \
#     algorithm.encoder.nodes='[24,8,4]' \
#     algorithm.kl_warmup_frac=0.2 \
#     algorithm.kl_scale=0.002 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=5.762357099041878e-05 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 476: wasserstein=0.00093274, kl=0.92946
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/vae_agnostic \
#     experiment_name=physics_vae_pareto \
#     run_name=wasserstein_t476 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.clamp_zlogvar_range='[-10,6]' \
#     algorithm.encoder.nodes='[24,8,4]' \
#     algorithm.kl_warmup_frac=0.2 \
#     algorithm.kl_scale=0.002 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=5.755410028938525e-05 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[3]

# ------------------------------------------------------------------------
# trial 477: wasserstein=0.00099718, kl=0.91163
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/vae_agnostic \
#     experiment_name=physics_vae_pareto \
#     run_name=wasserstein_t477 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.clamp_zlogvar_range='[-10,6]' \
#     algorithm.encoder.nodes='[24,8,4]' \
#     algorithm.kl_warmup_frac=0.3 \
#     algorithm.kl_scale=0.002 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=5.6990960341708e-05 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 478: wasserstein=0.00093178, kl=0.93119
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/vae_agnostic \
#     experiment_name=physics_vae_pareto \
#     run_name=wasserstein_t478 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.clamp_zlogvar_range='[-10,6]' \
#     algorithm.encoder.nodes='[24,8,4]' \
#     algorithm.kl_warmup_frac=0.3 \
#     algorithm.kl_scale=0.002 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=5.75950940066689e-05 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 479: wasserstein=0.000962, kl=0.92215
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/vae_agnostic \
#     experiment_name=physics_vae_pareto \
#     run_name=wasserstein_t479 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.clamp_zlogvar_range='[-10,6]' \
#     algorithm.encoder.nodes='[24,8,4]' \
#     algorithm.kl_warmup_frac=0.3 \
#     algorithm.kl_scale=0.002 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=5.7319222991066867e-05 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 480: wasserstein=0.00095719, kl=0.92365
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/vae_agnostic \
#     experiment_name=physics_vae_pareto \
#     run_name=wasserstein_t480 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.clamp_zlogvar_range='[-10,6]' \
#     algorithm.encoder.nodes='[24,8,4]' \
#     algorithm.kl_warmup_frac=0.3 \
#     algorithm.kl_scale=0.002 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=5.736449626378256e-05 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[3]

# ------------------------------------------------------------------------
# trial 481: wasserstein=0.00095246, kl=0.92499
# ------------------------------------------------------------------------
# taskset -c 0-2 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/vae_agnostic \
#     experiment_name=physics_vae_pareto \
#     run_name=wasserstein_t481 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.clamp_zlogvar_range='[-10,6]' \
#     algorithm.encoder.nodes='[24,8,4]' \
#     algorithm.kl_warmup_frac=0.3 \
#     algorithm.kl_scale=0.002 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=5.7406287887853556e-05 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[0]

# ------------------------------------------------------------------------
# trial 482: wasserstein=0.00091236, kl=0.93693
# ------------------------------------------------------------------------
# taskset -c 3-5 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/vae_agnostic \
#     experiment_name=physics_vae_pareto \
#     run_name=wasserstein_t482 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.clamp_zlogvar_range='[-10,6]' \
#     algorithm.encoder.nodes='[24,8,4]' \
#     algorithm.kl_warmup_frac=0.3 \
#     algorithm.kl_scale=0.002 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=5.776869419086839e-05 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[1]

# ------------------------------------------------------------------------
# trial 538: wasserstein=0.00067212, kl=1.0145
# ------------------------------------------------------------------------
# taskset -c 6-8 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/vae_agnostic \
#     experiment_name=physics_vae_pareto \
#     run_name=wasserstein_t538 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.clamp_zlogvar_range='[-6,4]' \
#     algorithm.encoder.nodes='[24,8,4]' \
#     algorithm.kl_warmup_frac=0.2 \
#     algorithm.kl_scale=0.002 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=6.003218398524073e-05 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=1.0 \
#     trainer=gpu \
#     trainer.devices=[2]

# ------------------------------------------------------------------------
# trial 539: wasserstein=0.00067084, kl=1.0154  << ORIGINAL PICK
# ------------------------------------------------------------------------
# taskset -c 9-11 \
# python3 src/train.py \
#     paths.raw_data_dir=/path/to/adl1t_data/parquet_files \
#     experiment=physics/vae_agnostic \
#     experiment_name=physics_vae_pareto \
#     run_name=wasserstein_t539 \
#     callbacks.thres_drift=null \
#     callbacks.cap_sn_zb=null \
#     callbacks.thres_drift_ema_ckpt=null \
#     callbacks.cap_sn_zb_ema_ckpt=null \
#     ~evaluation.evaluator.ckpts.summary.operational_drift_ema \
#     ~evaluation.evaluator.ckpts.summary.cap_ema_normal_vs_SingleNeutrino_E-10-gun \
#     algorithm.encoder.activation=relu \
#     algorithm.encoder.clamp_zlogvar_range='[-6,4]' \
#     algorithm.encoder.nodes='[24,8,4]' \
#     algorithm.kl_warmup_frac=0.2 \
#     algorithm.kl_scale=0.002 \
#     algorithm.optimizer.betas='[0.9,0.99]' \
#     algorithm.optimizer.lr=6.005882209363415e-05 \
#     algorithm.optimizer.weight_decay=0.0 \
#     trainer.gradient_clip_val=0.5 \
#     trainer=gpu \
#     trainer.devices=[3]
