# @package callbacks.main

_target_: src.callbacks.binning.BinningDiagnosticsCallback
enabled: true
epochs: [0]
include_last_epoch: true
batch_indices: [0, 100, 400, 764]
output_root_dir: '${paths.checkpoints_dir}/${experiment_name}/${run_name}/plots'
output_subdir: mi_diagnostics
log_to_mlflow: true
mlflow_artifact_path: mi_diagnostics
