# @package callbacks.main

_target_: src.callbacks.cap.CAPCallback
output_name: 'ascore/full'
dataset_1: ???
dataset_2: ???
pairing_type: cdf
cap_metric_config:
  beta0: 1.0
  normalization_type: sigmoid
  normalization_params: null
  energy_type: baseline
  energy_params: null
  regularization_type: none
  regularization_params: null
  binary: True
  lr: 0.01
  n_epochs: 50
  batch_size: 16384
  normalize_gradients: False
  process_group: null
  dist_sync_fn: null
