# @package _global_

defaults:
  - override /hydra/sweeper: optuna
  - override /hydra/sweeper/sampler: motpe

# here we define Optuna hyperparameter search
# it optimizes for value returned from function with @hydra.main decorator
# docs: https://hydra.cc/docs/next/plugins/optuna_sweeper
hydra:
  mode: "MULTIRUN" # set hydra to multirun by default if this config is attached
  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper

    # storage URL to persist optimization results
    # for example, you can use SQLite if you set 'sqlite:///example.db'
    storage: sqlite:///logs/optuna/physics/ae.db

    # name of the study to persist optimization results
    study_name: cvar25eff_vs_mse_b16k

    # number of parallel workers
    n_jobs: 1

    # 'minimize' or 'maximize' the objective
    direction: [maximize, minimize]

    # total number of runs that will be executed
    n_trials: 15

    # choose Optuna hyperparameter sampler
    # you can choose bayesian sampler (tpe), random search (without optimization), grid sampler, and others
    # docs: https://optuna.readthedocs.io/en/stable/reference/samplers.html
    sampler:
      n_startup_trials: 3
      consider_endpoints: true
      n_ehvi_candidates: 256

    # define hyperparameter search space. Assumes using torch.optim.AdamW
    params:
      trainer.gradient_clip_val: choice(0.0, 0.5, 1.0, 2.0, 5.0)
      algorithm.delta: choice(3.0, 4.0, 5.0, 7.0, 10.0)
      algorithm.input_noise_std: choice(0.0, 1e-4, 3e-4, 1e-3, 3e-3, 1e-2)
      algorithm.encoder.nodes: choice([16,8], [24,8], [24,16], [32,8], [32,16], [32,24], [48,8], [48,16], [48,24], [24,8,4], [24,8,8], [32,16,8], [32,16,16], [48,24,8], [48,24,16], [48,24,24], [64,32,8], [64,32,16], [64,32,24], [64,32,32])
      algorithm.optimizer.lr: tag(log, interval(3e-5, 3e-3))
      algorithm.optimizer.betas: choice([0.9, 0.999], [0.9, 0.99])
      algorithm.optimizer.weight_decay: choice(0.0, 1e-6, 1e-5, 1e-4, 1e-3)
