# @package _global_

defaults:
  - override /hydra/sweeper: optuna
  - override /hydra/sweeper/sampler: motpe

hydra:
  mode: "MULTIRUN" # set hydra to multirun by default if this config is attached
  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper

    # storage URL to persist optimization results
    # for example, you can use SQLite if you set 'sqlite:///example.db'
    storage: sqlite:///logs/optuna/vae.db

    # name of the study to persist optimization results
    study_name: cap_vs_mse_bs16k

    # number of parallel workers
    n_jobs: 1

    # 'minimize' or 'maximize' the objective
    direction: [maximize, minimize]

    # total number of runs that will be executed
    n_trials: 15

    # choose Optuna hyperparameter sampler
    # you can choose bayesian sampler (tpe), random search (without optimization), grid sampler, and others
    # docs: https://optuna.readthedocs.io/en/stable/reference/samplers.html
    sampler:
      n_startup_trials: 3
      consider_endpoints: true
      n_ehvi_candidates: 256

    # define hyperparameter search space. Assumes using torch.optim.AdamW
    params:
      trainer.gradient_clip_val: choice(0.0, 0.5, 1.0, 2.0)
      algorithm.encoder.clamp_zlogvar_range: choice([-20, 10], [-10, 6], [-8, 6], [-6, 4])
      algorithm.optimizer.lr: tag(log, interval(5e-5, 1e-3))
      algorithm.optimizer.betas: choice([0.9, 0.999], [0.9, 0.99])
      algorithm.optimizer.weight_decay: choice(0.0, 1e-6, 1e-5, 1e-4, 1e-3)
      algorithm.loss.kl_scale: choice(3e-5, 1e-4, 3e-4, 1e-3, 2e-3)
      algorithm.kl_warmup_frac: choice(0.0, 0.05, 0.1, 0.2, 0.3)
      algorithm.encoder.nodes: choice([16,4],[16,8],[24,4],[24,8],[32,8],[32,16],[24,8,4],[24,8,8],[32,16,4],[32,16,8],[48,16,8],[48,24,8],[32,16,16],[48,24,16],[64,32,16],[48,24,24],[64,32,24],[64,32,32])
      algorithm.encoder.activation: choice(relu, gelu, silu)
