apiVersion: v1
kind: Pod
metadata:
  name: adl1t-l40s-session
spec:
  containers:
    - name: container
      image: registry.cern.ch/adl1t/adl1t_lab:dev
      imagePullPolicy: Always
      command: ["sleep", "infinity"]
      resources:
        requests:
          cpu: "6"
          memory: "64Gi"
          nvidia.com/gpu: "1"
        limits:
          cpu: "6"
          memory: "64Gi"
          nvidia.com/gpu: "1"
  nodeSelector:
    nvidia.com/gpu.product: NVIDIA-L40S