# @package hydra.launcher
defaults:
  - submitit_slurm

submitit_folder: ${hydra.sweep.dir}/.submitit/%j

account: a0166
qos: null

partition: normal
timeout_min: 60
cpus_per_task: 3
gpus_per_node: 1
tasks_per_node: 1
nodes: 1
mem_gb: null

name: ${hydra.job.name}

additional_parameters: {}
signal_delay_s: 120
max_num_timeout: 0
