# @package hydra.launcher
defaults:
  - submitit_slurm

submitit_folder: ${hydra.sweep.dir}/.submitit/%j

account: a0166
partition: normal
qos: null

timeout_min: 240
cpus_per_task: 64
gpus_per_node: 1
tasks_per_node: 1
nodes: 1
mem_gb: null

name: ${hydra.job.name}

# important on CSCS: run the Slurm step inside the EDF container
srun_args:
  - --environment=adl1t

# optional, but often useful
additional_parameters: {}
signal_delay_s: 120
max_num_timeout: 0
