#!/usr/bin/env python3
"""Harvest per-epoch and per-phase wall-clock times from the Pareto retrainings.

Every Pareto retraining ran as its own slurm job on a clariden GH200 with a
single training process, so these runs -- unlike the hyperparameter sweeps --
give a clean, uncontended timing baseline. This script reduces each run to a
per-epoch cost plus the fixed overheads around the fit.

Timing comes from the ``epoch_idx`` metric, logged once per epoch in
``ADLightningModule.on_validation_epoch_end`` for every model and every
strategy. Because it does not depend on which callbacks are active, it is
directly comparable across strategies -- unlike the total job time, whose
post-fit evaluation phase is far heavier for the semi-supervised runs (they
evaluate ~24 checkpoints against ~3 for the agnostic ones).

Per run::

    sec_per_epoch  median gap between consecutive epoch_idx points
    setup_s        run start -> first epoch  (imports, data loading)
    fit_s          first epoch -> last epoch
    post_fit_s     last epoch -> run end     (the Evaluator phase)

The median is used rather than the mean so that the warm-up first epoch and the
occasional scheduler hiccup do not shift the number.

Runs are kept only when they actually trained: an ``epoch_idx`` history must
exist, which excludes the eval-only (``train=false``) resubmissions, and the
history must be the full 200 epochs, which excludes cancelled jobs. Where a run
name occurs more than once -- duplicate eval waves, ``*_retry`` scripts -- the
newest run wins. Experiments are collected by name across all experiment
directories, because a driver race created two experiment ids sharing the name
``physics_vae_q99_pareto``; both must be read.

The MLflow file store is read directly rather than through ``MlflowClient``.
``search_runs`` eagerly parses every metric key of every run, and the physics
runs carry one metric directory per validation dataset, which makes that route
orders of magnitude slower than reading the two files actually needed
(``meta.yaml`` and ``metrics/epoch_idx``). The layout is stable and documented,
and this keeps the script dependency-free, so it runs anywhere the ``mlruns``
folder has been copied -- the same portability ``harvest_pareto_effs.py``
assumes.

One CSV per experiment is written to ``notebooks/run_times/``.

Usage (on clariden, or anywhere holding a copy of the mlruns folder; see this
directory's README)::

    python scripts/runtime_study/harvest_run_times.py \\
        --tracking-uri file:/iopsstor/scratch/cscs/podagiu/logs/mlflow/mlruns
"""
from __future__ import annotations

import argparse
import csv
import re
import statistics
from pathlib import Path

# Logged once per epoch by ADLightningModule.on_validation_epoch_end.
EPOCH_KEY = "epoch_idx"

# Experiment names: <domain>_<model>[_q99]_pareto.
EXPERIMENT_RE = re.compile(r"^(physics|cifar10|robustad)_([a-z0-9]+?)(_q99)?_pareto$")

# Run names: <strategy>_t<trial>, as generated by make_pareto_scripts.py.
RUN_NAME_RE = re.compile(r"^([a-z0-9]+)_t(\d+)$")

# mlflow.entities.RunStatus: 1 RUNNING, 2 SCHEDULED, 3 FINISHED, 4 FAILED, 5 KILLED.
FINISHED = 3

MS_PER_S = 1000.0


def find_repo_root(start: Path) -> Path:
    for p in [start, *start.parents]:
        if (p / ".project-root").exists():
            return p
    return start


def strategy_of(run_name: str):
    m = RUN_NAME_RE.match(run_name)
    return m.group(1) if m else None


def read_meta(path: Path) -> dict:
    """Parse an MLflow file-store meta.yaml (a flat 'key: value' mapping)."""
    meta = {}
    for line in path.read_text().splitlines():
        key, sep, value = line.partition(":")
        if not sep or key.startswith((" ", "-", "#")):
            continue
        meta[key.strip()] = value.strip().strip("'\"")
    return meta


def epoch_timestamps(metric_path: Path) -> list[int]:
    """Milliseconds of each '<timestamp> <value> <step>' record, sorted."""
    stamps = []
    for line in metric_path.read_text().splitlines():
        parts = line.split()
        if parts:
            stamps.append(int(parts[0]))
    return sorted(stamps)


def run_times(run_dir: Path, meta: dict) -> dict | None:
    """Per-epoch and per-phase seconds for one run, or None if it never trained."""
    metric_path = run_dir / "metrics" / EPOCH_KEY
    if not metric_path.is_file():
        return None
    stamps = epoch_timestamps(metric_path)
    if len(stamps) < 2:
        return None

    start, end = int(meta["start_time"]), int(meta["end_time"])
    gaps = [(b - a) / MS_PER_S for a, b in zip(stamps, stamps[1:])]
    return {
        "n_epochs": len(stamps),
        "sec_per_epoch": statistics.median(gaps),
        "setup_s": (stamps[0] - start) / MS_PER_S,
        "fit_s": (stamps[-1] - stamps[0]) / MS_PER_S,
        "post_fit_s": (end - stamps[-1]) / MS_PER_S,
        "total_s": (end - start) / MS_PER_S,
    }


def harvest_experiment(name, exp_dirs, expected_epochs, outdir) -> int:
    """Write one CSV for an experiment name; returns the number of runs kept."""
    m = EXPERIMENT_RE.match(name)
    domain, model, tier = m.group(1), m.group(2), ("q99" if m.group(3) else "250")

    kept, skipped_eval_only, skipped_short = {}, 0, 0
    for exp_dir in exp_dirs:
        for run_dir in sorted(exp_dir.iterdir()):
            meta_path = run_dir / "meta.yaml"
            if not run_dir.is_dir() or not meta_path.is_file():
                continue
            meta = read_meta(meta_path)
            if int(meta.get("status", 0)) != FINISHED or not meta.get("end_time"):
                continue

            times = run_times(run_dir, meta)
            if times is None:
                skipped_eval_only += 1
                continue
            if expected_epochs and times["n_epochs"] != expected_epochs:
                skipped_short += 1
                print(f"  note: {meta['run_name']} ran {times['n_epochs']} epochs "
                      f"(expected {expected_epochs}), skipped")
                continue

            run_name = meta["run_name"]
            prev = kept.get(run_name)
            # Keep the newest run of a given name.
            if prev is None or int(meta["start_time"]) > prev[0]:
                kept[run_name] = (int(meta["start_time"]), meta, times)

    if not kept:
        print(f"  {name}: nothing kept")
        return 0

    rows = []
    for run_name, (_, meta, times) in sorted(kept.items()):
        rows.append({
            "domain": domain,
            "model": model,
            "tier": tier,
            "strategy": strategy_of(run_name) or "",
            "run_name": run_name,
            "run_id": meta["run_id"],
            "n_epochs": times["n_epochs"],
            "sec_per_epoch": f"{times['sec_per_epoch']:.4f}",
            "setup_s": f"{times['setup_s']:.2f}",
            "fit_s": f"{times['fit_s']:.2f}",
            "post_fit_s": f"{times['post_fit_s']:.2f}",
            "total_s": f"{times['total_s']:.2f}",
        })

    out_path = outdir / f"{name}.csv"
    with open(out_path, "w", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)

    note = f", {skipped_eval_only} eval-only" if skipped_eval_only else ""
    note += f", {skipped_short} wrong-length" if skipped_short else ""
    print(f"  wrote {out_path.name}: {len(rows)} runs{note}")
    return len(rows)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("experiments", nargs="*",
                        help="MLflow experiment names (default: every *_pareto one).")
    parser.add_argument("--tracking-uri", default=None,
                        help="MLflow store, 'file:<path>' or a plain path "
                             "(default: file:<repo>/logs/mlflow/mlruns).")
    parser.add_argument("--outdir", default=None,
                        help="Output dir for CSVs (default: <repo>/notebooks/run_times).")
    parser.add_argument("--expected-epochs", type=int, default=200,
                        help="Drop runs that did not complete this many epochs "
                             "(0 to keep all).")
    args = parser.parse_args()

    repo = find_repo_root(Path(__file__).resolve().parent)
    uri = args.tracking_uri or f"file:{repo / 'logs' / 'mlflow' / 'mlruns'}"
    root = Path(uri[len("file:"):] if uri.startswith("file:") else uri)
    if not root.is_dir():
        raise SystemExit(f"mlruns store not found: {root}")
    outdir = Path(args.outdir) if args.outdir else repo / "notebooks" / "run_times"
    outdir.mkdir(parents=True, exist_ok=True)

    # One name can own several experiment dirs (a driver race created two
    # 'physics_vae_q99_pareto' experiments), so group rather than overwrite.
    by_name: dict[str, list[Path]] = {}
    for exp_dir in sorted(root.iterdir()):
        meta_path = exp_dir / "meta.yaml"
        if not exp_dir.is_dir() or not meta_path.is_file():
            continue
        name = read_meta(meta_path).get("name", "")
        if EXPERIMENT_RE.match(name):
            by_name.setdefault(name, []).append(exp_dir)

    wanted = args.experiments or sorted(by_name)
    total = 0
    for name in wanted:
        exp_dirs = by_name.get(name)
        if not exp_dirs:
            print(f"experiment {name!r} not found in {root}")
            continue
        extra = f" ({len(exp_dirs)} experiment ids)" if len(exp_dirs) > 1 else ""
        print(f"harvesting {name}{extra}...")
        total += harvest_experiment(name, exp_dirs, args.expected_epochs, outdir)
    print(f"\ntotal runs: {total}")


if __name__ == "__main__":
    main()
